### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by rpx99** [lem-project/lem#1031]
I like autosave files as e.g. in [Idea](https://www.jetbrains.com/help/idea/saving-and-reverting-changes.html?keymap=emacs) 

Think in [Emacs](https://www.emacswiki.org/emacs/AutoSave#:~:text=By%20default%2C%20Emacs%20automatically%20saves,%2Dvisited%2Dmode'%20) it's called

`M-x auto-save-visited-mode`

**Comment by fukamachi** [comment]
Have you tried `lem/auto-save`?

https://github.com/fukamachi/.lem/blob/d5c4ad167607cb7eb898fbf9f09afbcf1215c046/modes/10-auto-save.lisp#L7-L10

**Comment by rpx99** [comment]
Ah, cool! Seems AS needs to be set for each single file ? Can it be globally activated ? Thanks!

**Comment by fukamachi** [comment]
Right, it is a minor mode, so you need to enable each buffer every time you open a file.
I did it automatically to add a function to `*find-file-hook*`.

**Comment by cxxxr** [comment]
https://github.com/lem-project/lem/commit/667756291a979c2bbb9da61f5144b0e2e0121833
I have made this change.
This allows you to simply activate the mode and it will be enabled on all buffers.

**Comment by rpx99** [comment]
Thank you. Got this message after pulling to latest:
```

; Loading "lem-sdl2"
..................................................
[package lem/auto-save].
debugger invoked on a UNDEFINED-FUNCTION @22D35BB3 in thread
#<THREAD "main thread" RUNNING {1002150113}>:
  The function LEM/AUTO-SAVE::ENABLE is undefined
```

**Comment by cxxxr** [comment]
Oh, I rushed it too much.
I have just fixed it.

**Comment by cxxxr** [comment]
Thank you for the feedback.
Global minor modes were not included in the modeline, but I did so because it was better to include them.

**Comment by rpx99** [comment]
Great! AS now shows up. Thank you.

Btw. is `M-x toggle-auto-save` somehow related or what does it do ?

**Comment by cxxxr** [comment]
Maybe `toggle-auto-save` is unnecessary now.

**Comment by rpx99** [comment]
Sorry, I don't know how I can activate the `auto-save-mode` in my init file, e.g. like paredit...

`(lem-paredit-mode:paredit-mode)`

How to do that ?

**Comment by fukamachi** [comment]
JFYI, here's my new config code.

https://github.com/fukamachi/.lem/blob/bb4fcd83986fa25ccd72344a21dbc5d73f955c20/modes/10-auto-save.lisp#L7-L10

**Comment by rpx99** [comment]
Thanks a lot!

**Comment by rpx99** [comment]
> Maybe `toggle-auto-save` is unnecessary now.

Think it's still good to have it. Seems it works when I use it, but the AS symbol stays in the modeline when toggled to "off".
