### ISSUE TITLE
Can't invoke built-in commands with M-x (release binaries)

### ISSUE THREAD

**Issue by underfarm** [lem-project/lem#1032]
Hi, 

I¨m having difficulties invoking several commands and getting strange error messages. 

1. When I try to invoke for instance `load-library` (M-x load-library), I get the error "Component "lem-contrib" not found"

<img width="528" alt="image" src="https://github.com/lem-project/lem/assets/11059403/f2cea766-7f82-48a8-ba9f-439d5ef2a4d0">

2. When I invoke `help` (M-x help)", I get the error "Component "lem" not found":

<img width="446" alt="image" src="https://github.com/lem-project/lem/assets/11059403/426fd056-c52a-475a-bd29-6de45c9b13eb">

I downloaded the release binaries from https://github.com/lem-project/lem/releases/tag/v2.1.0 extracted the files and started the executables/binaries.  On Windows I just start the "lem.bat" and on Linux I just executed the lem binary.  Same behaviour on both platforms.

**Comment by Sasanidas** [comment]
Seems like it's trying to load the systems with asdf, and asdf cannot find it (maybe it's doing it programatically, so asdf is looking for the path of them).

Dod you tried to copy the lem project to quicklisp/local-projects? (probably with the same tag as the release)

**Comment by underfarm** [comment]
Thanks, @Sasanidas, that did the trick!

I guess it's not supposed to be like this, and the components should be packaged with the released binaries?

**Comment by Sasanidas** [comment]
Indeed, I think probably the contrib files should be loaded differently, right now is complicated, but we are planning to move them externally to a package manager (https://github.com/ultralisp/ultralisp/issues/205).

Regarding the the last error, it's weird that it cannot find the Lem project, maybe it's a bug :thinking:

**Comment by underfarm** [comment]
It found the lem-project when i created ~/quicklisp/local-projects/lem, where the lem folder was the git repo.

**Comment by Sasanidas** [comment]
Ping @underfarm , from the last comment, maybe this issue is solved?
