### ISSUE TITLE
Lisp find definition doesn't always work

### ISSUE THREAD

**Issue by Sasanidas** [lem-project/lem#1052]
So, I was trying to build a simple command to go to the definition of the major mode of the current buffer:
```
(define-command fer/goto-major-mode () ()
  (lem-lisp-mode/internal::display-xref-locations
   (lem-lisp-mode/internal::find-definitions-by-name
      (symbol-name  (lem:buffer-major-mode (lem:current-buffer))))))
```
The thing is, it wasn't reliable, in some buffers will work, not in others.

So I realize that when launching `find-definitions-by-name` somethings the result was NIL, when there is clearly a major mode with that exact name.

https://github.com/lem-project/lem/assets/26670956/00069b85-0464-4080-bb4e-448e40eca820

**Comment by cxxxr** [comment]
This is because the package you are currently running (lem-lisp-mode/internal) and the package of the target symbol (lem-lisp-mode/inspector) are different.

**Comment by cxxxr** [comment]
To do this, I suppose the following two phases are necessary.
- Finding a specific symbol by mode name (e.g. Add find-major-mode-by-name)
- Fetch the location of the symbol definition

**Comment by Sasanidas** [comment]
I see, seems like I overlook the find reference function (indeed without the full name with package makes sense that it cannot find it).

I think I found a "good-enough" way of doing it (even tho it's a little bit hackish):
```
(define-command fer/goto-major-mode () ()
  (let ((current-mode (lem:buffer-major-mode (lem:current-buffer))))
    (lem-lisp-mode/internal::display-xref-locations
        (lem-lisp-mode/internal::find-definitions-by-name
         (format nil "~a::~a"
                 (package-name (symbol-package current-mode))
                 (symbol-name current-mode))))))
```

**Comment by Sasanidas** [comment]
I think this solution works well enough, so I'll close the issue :+1:
