### ISSUE TITLE
async-process broken on SDL2 frontend

### ISSUE THREAD

**Issue by resttime** [lem-project/lem#1068]
```
M-x start-lisp-repl
(async-process:create-process "ls")
```
1. Succeeds on ncurses
2. Hangs on SDL2

Various code depends on `async-process` such as `lem-process` package or `lsp-mode` for running asynchronous processes. Might be how SDL2 frontend has things running in different threads causing async to break.

**Comment by resttime** [comment]
![image](https://github.com/lem-project/lem/assets/2598904/ff5a9857-7ca0-4698-a4ac-d6c996af8d2b)

**Comment by cxxxr** [comment]
https://github.com/lem-project/async-process/commit/1d9e9c250ba44cff889c23df4415ec44b448fa1a
This change should have fixed it, but what do you think?

**Comment by resttime** [comment]
I am using latest changes from the `main` branch. Can see in the REPL modeline it is stuck on `Evaluating...` It's possible to `C-c C-c` and interrupt from editor although. Unsure with what the reason is, appears to be blocking. However I notice the memory fault printed in `CORRUPTION-WARNING` is always same location `0x7fae2626f990`

```
CORRUPTION WARNING in SBCL pid 24830 tid 24830:
Memory fault at 0x7fae2626f990 (pc=0x7fae39f2e5ce, fp=0x7fae2c4da548, sp=0x7fadfb0bd870) tid 24830
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
```


![image](https://github.com/lem-project/lem/assets/2598904/bf64844a-e765-4e44-8593-a7ec01f57367)

**Comment by resttime** [comment]
![image](https://github.com/lem-project/lem/assets/2598904/760b1142-86d0-4e77-a19f-7f9ec305c33b)
Also noted that there's an orphaned thread/process even after exiting the editor and SBCL

**Comment by resttime** [comment]
Not sure if this is correct, but the problem went away when I removed `static` from the function declaration `my_exit`

https://github.com/lem-project/async-process/blob/859db12e7f8bf3546487ea4fd7681d07c767306a/src/async-process.c#L32

**Comment by cxxxr** [comment]
Thank you very much for resolving this issue.
