### ISSUE TITLE
Confirmation Prompt on Recursive Deletion

### ISSUE THREAD

**Issue by resttime** [lem-project/lem#1075]
In Emacs dired prompts once if deleting a directory, and then prompts a second time for further options on recursive deletion. Lem only prompts once, just adding the second prompt for (y or n) can be an additional safety guard.

Reporting this issue for now, I'll work on it and create PR

# Emacs
```
Trash foo (y or n)
y
Recursively trash foo? (y, n, !, q, ?)
?

Type:
`y' (yes) to delete recursively the current directory,
`n' (no) to skip to next,
`!' (all) to delete all remaining directories with no more questions,
`q' (quit) to exit,
`?' (help) to show this help message.
```

**Comment by resttime** [comment]
Specifically the behaviour is defined in `dired.el` as such https://github.com/emacs-mirror/emacs/blob/a2f977d94e0356c7414876e988adedd2ab7b52f2/lisp/dired.el#L3646

**Comment by cxxxr** [comment]
Thank you for the feedback.
Personally, I do not prefer multiple prompts because it complicates the UI.
I think that a common filer (GUI explorer), for example, would ever ask recursively.
It is also undesirable to add features for compatibility with GNU Emacs.

**Comment by resttime** [comment]
Ok that makes sense :ok_hand:
