### ISSUE TITLE
C-x e problem

### ISSUE THREAD

**Issue by rpx99** [lem-project/lem#1095]
`C-x e` does not seem to work properly.

It evaluates a form inline. How can I get rid of the evaluated result?

Additionally, it seems it stops working after a couple of times using it?

Don't get an error message.

![image](https://github.com/lem-project/lem/assets/70011162/27ac369c-d218-4be5-8289-82aca3fc4732)

**Comment by cxxxr** [comment]
The evaluation results can be deleted by selecting "Clear eval results" from M-h (M-x show-context-menu).

> Additionally, it seems it stops working after a couple of times using it?

Hmm, I am not sure about this.

**Comment by rpx99** [comment]
Thanks, that was very helpful! Think now there is no bug.
