### ISSUE TITLE
completion-mode bug

### ISSUE THREAD

**Issue by rpx99** [lem-project/lem#1096]
`M-x completion-mode` seems to be broken?

![image](https://github.com/lem-project/lem/assets/70011162/2f287710-4501-4ff2-9f7b-779cda17e1e0)

**Comment by Sasanidas** [comment]
Thanks for the report! Indeed seems like there is a problem with completion-mode.

Can you provide more context about the issue? (lem version (or git commit), current buffer, major-mode)

**Comment by rpx99** [comment]
I used sdl2 and
```
$ git branch
* commonization-of-graphical-text-buffer
```
with the latest code pulled.

![image](https://github.com/lem-project/lem/assets/70011162/879ea932-0f72-4475-b87d-20e3bad04b75)

**Comment by seanfarley** [comment]
Can you not make a generic issue while using a WIP branch that hasn't been merged yet? It's really distracting to the other developers and volunteers to the project because you're using unfinished code that has been explicitly labeled "doesn't work yet."
