### ISSUE TITLE
Tabs buffer-v1 vs. buffer-v2

### ISSUE THREAD

**Issue by rpx99** [lem-project/lem#1099]
Buffer v1:
![image](https://github.com/lem-project/lem/assets/70011162/855014f0-c1e6-40cf-8444-262ad256ede4)

Buffer v2:
![image](https://github.com/lem-project/lem/assets/70011162/40bd1cd5-f655-41ab-ba66-a6d0eb89bd5a)

**Comment by rpx99** [comment]
I used sdl2 and
```
$ git branch
* commonization-of-graphical-text-buffer
```
with the latest code pulled.

![image](https://github.com/lem-project/lem/assets/70011162/879ea932-0f72-4475-b87d-20e3bad04b75)


With buffer-v1 you can create tabs.
With buffer-v2 you only get the squares for a tab.

**Comment by cxxxr** [comment]
There are functions where new renderings have not yet been implemented.
The display of tabs was one such example.

**Comment by cxxxr** [comment]
I believe this issue has been resolved.
What do you think?

**Comment by rpx99** [comment]
Yes, I confirm it is gone now for v1 and v2!

![image](https://github.com/lem-project/lem/assets/70011162/17deeb52-2648-4aca-aeea-b003cea352a3)

![image](https://github.com/lem-project/lem/assets/70011162/55263873-bfb0-4124-8abd-768691be4a67)

Many thanks!
