### ISSUE TITLE
Prompt color changes when lem is closed.

### ISSUE THREAD

**Issue by masahiko-ofgp** [lem-project/lem#1100]
;; My environment
OS: Manjaro i3 (urxvt, bash)
SBCL+Quicklisp, lem(from source)

;; Problem
My prompt color is **light grey**. However, when I start lem, finishing using it, and close it, my prompt color tuned **green**. 
What's the cause?

**Comment by t-sin** [comment]
The ncurses library cannot restore original color before starting ncurses because the ncurses does not provide an interface to know current color settings.

cf: https://stackoverflow.com/questions/36051061/color-not-ended-in-curses

**Comment by masahiko-ofgp** [comment]
It may be an issue other than lem. Sorry.
