### ISSUE TITLE
Installation with sbcl doesn't work anymore

### ISSUE THREAD

**Issue by ilya-fiveisky** [lem-project/lem#1111]
[These instructions](https://lem-project.github.io/lem-page/installation/getting-started/#installation-with-sbcl) do not work anymore. Which is expectable after removing submodules. It just cannot load micros:

```
* (ql:quickload :lem-sdl2)
To load "lem-sdl2":
  Load 1 ASDF system:
    lem-sdl2
; Loading "lem-sdl2"
...
debugger invoked on a QUICKLISP-CLIENT:SYSTEM-NOT-FOUND in thread
#<THREAD "main thread" RUNNING {1004E6C1B3}>:
  System "micros" not found

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE               ] Try again
  1: [ABORT                  ] Give up on "micros"
  2:                           Give up on "lem-sdl2"
  3: [REGISTER-LOCAL-PROJECTS] Register local projects and try again.
  4:                           Exit debugger, returning to top level.

((LABELS QUICKLISP-CLIENT::RECURSE :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) "micros")
   source: (CERROR "Try again" 'SYSTEM-NOT-FOUND :NAME NAME)
0]
```

**Comment by seanfarley** [comment]
Yep, you'll need to run [the instructions from the repo](https://github.com/lem-project/lem#install) since the website is for the latest released version.

**Comment by swapneils** [comment]
Does this mean Roswell installation is no longer supported? Both ros install lem and ros install lem-project/lem produce this behavior for me.

**Comment by seanfarley** [comment]
It seems it's an issue with roswell, more info here:

https://github.com/lem-project/lem/pull/1121
