### ISSUE TITLE
v2.1.0 binary does not work on macOS Sonoma

### ISSUE THREAD

**Issue by skyizwhite** [lem-project/lem#1113]
According to the SBCL release notes, older versions of SBCL cause errors on macOS Sonoma.
Therefore, you must use SBCL v2.3.8 or later to build lem-sdl2.

> on Mac OS X Sonoma, loading the memory image no longer fails. ([#2029430](https://bugs.launchpad.net/sbcl/+bug/2029430), reported by cladur)

http://www.sbcl.org/news.html#2.3.8

**Comment by cxxxr** [comment]
Thank you for the useful information.
I hope to release the new version within the next month.

**Comment by rcarmo** [comment]
Any updates?

**Comment by cxxxr** [comment]
I declare that I will release it on February 10 to discourage the habit of stretching it out forever.

**Comment by sooheon** [comment]
This is marked as completed, but I'm still getting the error (Sequoia):

```
mmap: Operation not permitted
fatal error encountered in SBCL pid 26869 pthread 0x1f1356940:
load_core_bytes(3,0x74b0000,0x300000000,10000) failed
```
