### ISSUE TITLE
Calling `slime` command gives "Error running timer"

### ISSUE THREAD

**Issue by ilya-fiveisky** [lem-project/lem#1122]
When I try to run `slime` command in Lem I get:
```
Error running timer "(LABELS INTERVAL IN RUN-SLIME)": Condition USOCKET:CONNECTION-REFUSED-ERROR was signalled.
Backtrace for: #<SB-THREAD:THREAD "editor" RUNNING {100061C363}>
0: ((LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE))
1: ((FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX))
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<FUNCTION (FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX) {7FAEC091DECB}>)
3: (UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE) {1007320D7B}> :PACKAGE :CL)
4: (LEM-CORE:POP-UP-BACKTRACE #<LEM/COMMON/TIMER:TIMER-ERROR {100731F543}>)
5: ((FLET "H0" :IN LEM-CORE:COMMAND-LOOP) #<LEM/COMMON/TIMER:TIMER-ERROR {100731F543}>)
6: (SB-KERNEL::%SIGNAL #<LEM/COMMON/TIMER:TIMER-ERROR {100731F543}>)
7: (ERROR LEM/COMMON/TIMER:TIMER-ERROR :TIMER #<LEM/COMMON/TIMER:TIMER "(LABELS INTERVAL IN RUN-SLIME)" {1005EBBEA3}> :CONDITION #<LEM-BASE:EDITOR-ERROR {1006D0E4C3}>)
8: (LEM/COMMON/TIMER::CALL-TIMER-FUNCTION #<LEM/COMMON/TIMER:TIMER "(LABELS INTERVAL IN RUN-SLIME)" {1005EBBEA3}>)
9: ((LAMBDA NIL :IN LEM/COMMON/TIMER:SEND-TIMER-NOTIFICATION))
10: (LEM-CORE:RECEIVE-EVENT NIL)
11: (LEM-CORE::READ-EVENT-INTERNAL :ACCEPT-KEY T :ACCEPT-MOUSE T)
12: (LEM-CORE::READ-EVENT-WITH-RECORDING-AND-RUN-HOOKS :ACCEPT-KEY T :ACCEPT-MOUSE T)
13: (LEM-CORE:READ-COMMAND)
14: (LEM/COMMON/TIMER::CALL-WITH-IDLE-TIMERS #<FUNCTION (LAMBDA NIL :IN LEM-CORE::COMMAND-LOOP-BODY) {52CD7F7B}>)
15: (LEM-CORE::COMMAND-LOOP-BODY)
16: (LEM-CORE:COMMAND-LOOP)
17: (LEM-CORE::TOPLEVEL-COMMAND-LOOP #<FUNCTION (LAMBDA NIL :IN LEM-CORE::RUN-EDITOR-THREAD) {1005D83EAB}>)
18: ((LAMBDA NIL :IN LEM-CORE::RUN-EDITOR-THREAD))
19: ((LAMBDA NIL :IN LEM-CORE::RUN-EDITOR-THREAD))
20: ((LABELS BORDEAUX-THREADS::%BINDING-DEFAULT-SPECIALS-WRAPPER :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
21: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
22: ((FLET "WITHOUT-INTERRUPTS-BODY-10" :IN SB-THREAD::RUN))
23: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
24: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-THREAD::RUN))
25: (SB-THREAD::RUN)
26: ("foreign function: call_into_lisp")
27: ("foreign function: funcall1")

```

**Comment by cxxxr** [comment]
Thank you for the feedback.
I ran into this problem myself.

One of the causes seems to be that sbcl is not successfully started within the slime command.
And let me check a few things.

- Do you have both roswell and sbcl installed?
- Is lem running via roswell and sbcl with slime command running without roswell?

**Comment by ilya-fiveisky** [comment]
I don't have roswell and have sbcl 2.1.11
About running lem: I cloned it from github, called `make` and then `./lem`. That's it.

**Comment by cxxxr** [comment]
Hmm, I can't figure it out, but is there any output in the buffer named `*Run Lisp swank/...*`?

**Comment by ilya-fiveisky** [comment]
`*Run Lisp swank/...*` content:
```
This is SBCL 2.1.11.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* 
debugger invoked on a QUICKLISP-CLIENT:SYSTEM-NOT-FOUND in thread
#<THREAD "main thread" RUNNING {1004E741B3}>:
  System "micros" not found

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE               ] Try again
  1: [ABORT                  ] Give up on "micros"
  2: [REGISTER-LOCAL-PROJECTS] Register local projects and try again.
  3:                           Exit debugger, returning to top level.

((LABELS QUICKLISP-CLIENT::RECURSE :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) "micros")
   source: (CERROR "Try again" 'SYSTEM-NOT-FOUND :NAME NAME)
0] 
```

**Comment by ilya-fiveisky** [comment]
I should note that lem is placed in `~/projects/` directory which is not in asdf source-registry for global quicklisp.

**Comment by ilya-fiveisky** [comment]
Also if I clone lem in ~/common-lisp directory then it works.
But if I use 
```
(push ".qlot" asdf::*default-source-registry-exclusions*)
(asdf:initialize-source-registry)
```
in .sbclrc as advised on [qlot page](https://github.com/fukamachi/qlot#optional-settings) then it doesn't work again.

**Comment by cxxxr** [comment]
Oh, I understand.
Thank you for the debug information.

sbcl runned from the slime command must read micros.
But when you install lem with qlot, it doesn't know where micros is.
As a workaround for the current situation, we need to do the way you commented.
Alternatively, we can install github.com/lem-project/micros in the $HOME/common-lisp directory, for example.
In any case, it looks like we need a smarter solution.

**Comment by ilya-fiveisky** [comment]
I would suggest that workaround with installing micros in ~/common-lisp (or any other asdf source-registry directory) is better than installing entire lem in ~/common-lisp (as I did before) because in latter case all asdf systems from lem's .qlot sub-directory will be accessible for global quicklisp which is not good.

**Comment by Sasanidas** [comment]
Ping to @ilya-fiveisky , did the issue got solve with https://github.com/lem-project/lem/pull/1135?

**Comment by ilya-fiveisky** [comment]
I cloned latest lem version (commit 914a1126), then `make`, then removed micros from ~/common-lisp, then started `./lem`, then `slime` command and got same "Error running timer" error with same message in the `*Run Lisp swank/...*`.

**Comment by Sasanidas** [comment]
Umm, since September we changed the way that Lem compiles, would you mind to clone it from scratch and try the installation instructions here? https://lem-project.github.io/installation/ncurses/linux/#installation-from-scratch 

Sorry about the inconvenience

**Comment by ilya-fiveisky** [comment]
After removing lem's directory, re-cloning and invoking `make ncurses` instead of just `make` it works now. Don't know what was the problem before. Maybe lem's directory already existed before cloning (I didn't check), maybe it was because of `make` instead of `make ncurses`, maybe something else. But anyway, it works now.

**Comment by novemberist** [comment]
I'm having the exact same issue with lem installed from Arch's AUR. The REPL seems to work fine as soon as I run M-x slime, but the mode line still shows "Slime is starting up" for a couple of seconds until the error message mentioned above appears. It doesn't seem to affect the functionality of the REPL, though. What's also weird is that 1 out of 3 times the slime REPL starts with "NIL>" insted of the usual "CL-USER>" prompt (may or may not be related to this issue)
