### ISSUE TITLE
Key not found error when pressing C-c in Lem ncurses

### ISSUE THREAD

**Issue by pamoroso** [lem-project/lem#1125]
When I press `C-c` under Crostini Linux Lem displays the error `Key not found: C-c`:

![Lem-C-c-Crostini](https://github.com/lem-project/lem/assets/10342479/a922b576-47e4-4357-b1e8-1cac36053677)

The only message in the log file is:

```
 <INFO> [14:12:53] lem-core lem.lisp (lem) - Starting Lem
```

I'm using SBCL 2.3.8 built from source and Lem ncurses installed as [per the documentation](https://lem-project.github.io/lem-page/installation/getting-started/). Crostini Linux is the Debian-based Linux container (Buster on my system) of chromeOS, which I use on an ASUS Chromebox 3 under chromeOS Stable  117.0.5938.115.

The issue occurs both in Crostini's system Terminal tool, to which the above screenshots refers, and the Zutty terminal emulator. Pressing `C-c` works as expected in the shell in Terminal and Zutty. I have no Lem initialization files.

**Comment by cxxxr** [comment]
The buffer displayed at startup is not in lisp-mode, so commands beginning with C-c are not assigned.
If you want to use commands for lisp, run M-x lisp-mode.
Also, please open a file with a lisp extension.

**Comment by pamoroso** [comment]
Doh, you're totally right. I created a Lisp mode buffer and everything worked as expected. Thanks.
