### ISSUE TITLE
step doesn't seem to work

### ISSUE THREAD

**Issue by felipebubu** [lem-project/lem#1130]
so I'm trying to use (step (function)), however, it doesn't seem to work. My function is steppable, see: 
```
 ; processing (SB-EXT:DESCRIBE-COMPILER-POLICY)
  Basic qualities:
COMPILATION-SPEED = 1
DEBUG = 3
SAFETY = 1
SPACE = 1
SPEED = 1
```
however, whenever I try to step by using (step (function)), even though it stops the application, none of the options below work:
```
Restarts:
 0: [STEP-CONTINUE] Resume normal execution
 1: [STEP-OUT] Resume stepping after returning from this function
 2: [STEP-NEXT] Step over call
 3: [STEP-INTO] Step into call
 4: [ABORT] abort thread (#<THREAD tid=3449 "hunchentoot-worker-127.0.0.1:56338" RUNNING {10013106C3}>)
```
It just resumes execution. I tested that on 2.0.0 and 2.1.0, it doesn't step into.

EDIT: if that matters, it pops up a tiny message box saying "evaluation aborted on NIL."

**Comment by vindarel** [comment]
Try with speed 0, safety 3 ?

This works for me:

```lisp

(defun adder (n)
  (declare (optimize (speed 0) (safety 3) (debug 3)))
  (let ((a 1))
    (incf a n)
    (print a)
    (print a)
    ))

(step (adder 3))
```

I can step into, step next, etc.

What's your snippet?

**Comment by felipebubu** [comment]
@vindarel it worked... I feel stupid, I didn't know declare had to be in the function scope 🤦 sorry for wasting your time

**Comment by felipebubu** [comment]
actually, I used declaim, but in a separated file because I thought it'd be loaded in all files when doing asdf:load-system.

**Comment by vindarel** [comment]
no worries. I discovered that C-u C-c C-c in Lem doesn't add the debug settings, as in Slime, which replaces the need to write the declare form.
