### ISSUE TITLE
Update Lem and it stopped working properly

### ISSUE THREAD

**Issue by daninus14** [lem-project/lem#1133]
I don't know which version I was using before, but I've updated lem and now it stopped working properly. I waited about a couple of weeks and updated again to the latest version with `ros update lem` but it's still broken.

```
; file: /Users/myusername/.roswell/lisp/quicklisp/quicklisp/http.lisp
; in: DEFUN PROCESS-HEADER
;     (ERROR "Unable to process HTTP header")
;
; note: deleting unreachable code

; file: /Users/myusername/.roswell/lisp/quicklisp/quicklisp/dist.lisp
; in: DEFUN CONFIG-FILE-INITARGS
;     (INTERN (FUNCALL QL-DIST::*INITARG-CASE-CONVERTER* STRING) 'KEYWORD)
;
; note: deleting unreachable code
;
; compilation unit finished
;   printed 2 notes
```

```
Don't know how to REQUIRE PACKAGE.
See also:
  The SBCL Manual, Variable SB-EXT:*MODULE-PROVIDER-FUNCTIONS*
  The SBCL Manual, Function REQUIRE
Backtrace for: #<SB-THREAD:THREAD "editor" RUNNING {100515B133}>
0: ((LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE))
1: ((FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX))
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<FUNCTION (FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX) {80CE9CB}>)
3: (UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE) {100698CABB}> :PACKAGE :CL)
4: (LEM-CORE:POP-UP-BACKTRACE #<SB-INT:EXTENSION-FAILURE "Don't know how to ~S ~A." {1006558CF3}>)
5: ((FLET "H0" :IN LEM-CORE::TOPLEVEL-COMMAND-LOOP) #<SB-INT:EXTENSION-FAILURE "Don't know how to ~S ~A." {1006558CF3}>)
6: (SB-KERNEL::%SIGNAL #<SB-INT:EXTENSION-FAILURE "Don't know how to ~S ~A." {1006558CF3}>)
7: (ERROR SB-INT:EXTENSION-FAILURE :FORMAT-CONTROL "Don't know how to ~S ~A." :FORMAT-ARGUMENTS (REQUIRE PACKAGE) :REFERENCES ((:SBCL :VARIABLE SB-EXT:*MODULE-PROVIDER-FUNCTIONS*) (:SBCL :FUNCTION REQUIRE
8: (REQUIRE PACKAGE NIL)
9: (SB-INT:SIMPLE-EVAL-IN-LEXENV (REQUIRE (QUOTE PACKAGE)) #<NULL-LEXENV>)
10: (SB-EXT:EVAL-TLF (REQUIRE (QUOTE PACKAGE)) 0 NIL)
11: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (REQUIRE (QUOTE PACKAGE)) 0)
12: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (REQUIRE (QUOTE PACKAGE)) :CURRENT-INDEX 0)
13: (SB-C::%DO-FORMS-FROM-INFO #<FUNCTION (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {100649451B}> #<SB-C::SOURCE-INFO {10064944E3}> SB-C::INPUT-ERROR-IN-LOA
14: (SB-INT:LOAD-AS-SOURCE #<SB-INT:FORM-TRACKING-STREAM for "file /Users/myusername/.lem/init.lisp" {1006492B13}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
15: ((LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) #<SB-INT:FORM-TRACKING-STREAM for "file /Users/myusername/.lem/init.lisp" {1006492B13}> NIL)
16: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) {80CF5EB}> #<SB-INT:FORM-TRACKING-STREAM for "file /Users/myusername/.lem/init.lisp" {1006492B13}> NIL #<SB-
17: (LOAD #P"/Users/myusername/.lem/init.lisp" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
18: ((FLET LEM-CORE::MAYBE-LOAD :IN LEM-CORE::LOAD-INIT-FILE) #P"/Users/myusername/.lem/init.lisp")
19: (LEM-CORE::LOAD-INIT-FILE)
20: (LEM-CORE::INIT #S(LEM-CORE::COMMAND-LINE-ARGUMENTS :ARGS NIL :DEBUG NIL :LOG-FILENAME NIL :NO-INIT-FILE NIL))
21: (LEM-CORE::TOPLEVEL-COMMAND-LOOP #<FUNCTION (LAMBDA NIL :IN LEM-CORE::RUN-EDITOR-THREAD) {1006319A6B}>)
22: ((LAMBDA NIL :IN LEM-CORE::RUN-EDITOR-THREAD))
23: ((LAMBDA NIL :IN LEM-CORE::RUN-EDITOR-THREAD))
24: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
25: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
26: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
27: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
28: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
29: (SB-THREAD::RUN)
30: ("foreign function: call_into_lisp")
31: ("foreign function: funcall1")
```

Any ideas on how I can fix it? Is there a way for roswell to completely remove lem to try reinstalling it? I'm using an old MacOS. I just tried updating ros from 2.3.7 to 2.3.9 but the issue remains.

Thanks for the help in advance

**Comment by vindarel** [comment]
Hi, do you have code in your `/.lem/init.lisp` and if so, does Lem start without it?

(then the SBCL and ASDF versions could be useful, I guess)

**Comment by daninus14** [comment]
Hi, there is something there, though I don't remember editing this file. I would assume it's there by default. 

This is what I found:

```common-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
;; and `package-pinned-packages`. Most users will not need or want to do this.
;;(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)
```

I just remembered that on running the `ros update lem` there was a git pull saying certain files couldn't be deleted from the local version after pulling from git. 

I tried `ros delete lem` but it seems the `ros delete` command only works for lisp implementations, not for systems, yet lem is installed with ros per the docs with `ros follow-dependency=t install lem-project/lem`. I think there should be some docs or instructions on how to uninstall. Can you please explain to me how to uninstall lem to try and do a fresh install? Maybe that will solve the issue...

Thanks for your help!

**Comment by daninus14** [comment]
I don't know if this will help, but I just updated roswell to version 23.10.14.114 and got a warning I got before when trying to use lem `WARNING: :SB-EVAL is no longer present in *FEATURES*`

**Comment by cxxxr** [comment]
>Hi, there is something there, though I don't remember editing this file. I would assume it's >there by default.
>
>This is what I found:

That file is from emacs, please delete it.


> I tried ros delete lem but it seems the ros delete command only works for lisp implementations, not for systems, yet lem is installed with ros per the docs with ros follow-dependency=t install lem-project/lem. I think there should be some docs or instructions on how to uninstall. Can you please explain to me how to uninstall lem to try and do a fresh install? Maybe that will solve the issue...

It is probably stored under $HOME/.roswell/local-projects.
It should be possible to uninstall by deleting this directory.

In addition, the current lem dependency library is managed by qlot.
https://github.com/fukamachi/qlot

Also I use lem in the following way.
I hope this will be helpful.
```
git clone https://github.com/lem-project/lem.git
cd lem
qlot install
qlot exec ros -l scripts/build-ncurses.lisp
./lem
```

if you are using sbcl instead of roswell, README.md is helpful.

**Comment by vindarel** [comment]
That explains. We can spot on line 17 that the error comes from your lem init file, and on line 12 we see

    (REQUIRE (QUOTE PACKAGE)

which is indeed `(require 'package)`,  from an Emacs config, and is coherent with the top level error "Don't know how to REQUIRE PACKAGE."

I'll close, happy to talk more about uninstallation if required.

**Comment by daninus14** [comment]
@cxxxr Thanks for the explanation! Very helpful!
