### ISSUE TITLE
Problems loading the tmLanguage definition of lua

### ISSUE THREAD

**Issue by Sasanidas** [lem-project/lem#1155]
I was working to adding to support to the Lua programming language and I thought that similar to `sql-mode` I can maybe use the TexMate grammars that vscode provide to get the syntax highlight quite easily.

I got the grammar from https://github.com/microsoft/vscode/blob/main/extensions/lua/syntaxes/lua.tmLanguage.json

To test the grammar, I call in the REPL:
```lisp
(lem/tmlanguage:load-tmlanguage #P"/home/fermin/quicklisp/local-projects/lem/extensions/lua-mode/lua.tmLanguage.json")
``` 

But it doesn't work automatically, it triggers the error: `Variable length look-behind not implemented (yet)`.

Seems like the problem is `(?<![^.]\\.|:)` at the beginning of some regex, removing then solves the above error but the parsing is not correct (basically it draws most of the symbols with the constant color).
![error_tmlanguage](https://github.com/lem-project/lem/assets/26670956/209c3ef7-ccf3-4c01-89ea-d36b784e4311)

**Comment by RedCMD** [comment]
`(?<![^.]\\.|:)` is supported by PCRE, Onigmo and oniguruma 
otherwise you can just change it to `(?<![^.]\\.)(?<!:)`
