### ISSUE TITLE
SDL install instructions builds ncurses version, not SDL

### ISSUE THREAD

**Issue by mmontone** [lem-project/lem#1161]
Hi.

If I follow SDL2 install instructions: https://lem-project.github.io/lem-page/installation/sdl2/linux/

An ncurses version of Lem is built, not SDL2.

**Comment by mmontone** [comment]
I think you need to replace `make ncurses` by `make sdl2` in the instructions on that page.

**Comment by Sasanidas** [comment]
Ups! Indeed that was a type, I'll fix it :+1:

**Comment by Sasanidas** [comment]
Funny enough, I got it right on the MacOS installation.

Fixed here https://github.com/lem-project/lem-page/commit/f3e145d9cf01e75b3411045bab3005ff4b75dc49

**Comment by mmontone** [comment]
Great :)
