### ISSUE TITLE
[SDL2] Lem freezes when running recenter command on floating prompt

### ISSUE THREAD

**Issue by daboddo** [lem-project/lem#1163]
## Description
Lem freezes completely when using the recenter command (`C-l`) when a floating window is active

## Steps to reproduce
On the SDL2 frontend of Lem, running the `find-file` command (`C-x C-f`), and before opening a file, execute recenter (`C-l`)

## Current result
Lem freezes and forces the user to kill the process. In addition to that, it doesn't report any error on the error.log file.

**Comment by cxxxr** [comment]
Thank you for your report.
This issue was raised earlier (https://github.com/lem-project/lem/issues/911) but I had forgotten about it.
This is a stopgap measure, but the behavior itself should have been corrected.
