### ISSUE TITLE
Comment region doesn't work on vi-mode

### ISSUE THREAD

**Issue by Sasanidas** [lem-project/lem#1166]
I think the command comment-region doesn't work using vi-mode

https://github.com/lem-project/lem/assets/26670956/89946489-4afa-4fd3-b6c3-870b5c65d683

**Comment by swapneils** [comment]
This isn't about comment-region specifically. The `vi-mode` visual state isn't being accounted for in region-based commands like `lisp-eval-region`; if you use the mark to select text then region commands (including `comment-region`) work as expected.

**Comment by Sasanidas** [comment]
I propose a solution for it, https://github.com/lem-project/lem/pull/1176
