### ISSUE TITLE
LEM error 

### ISSUE THREAD

**Issue by rpx99** [lem-project/lem#1178]
I start a repl and enter:

`(funcall (lambda (x) (+ x 100)) 2)`

When I mistakenly miss the 2, i.e.

` (funcall (lambda (x) (+ x 100)) )`

the error occurs.

`SDL Error (#SDL-SURFACE {#X00000000}>): Text h`

LEM freezes "evaluating" and takes more and more CPU.

**Comment by rpx99** [comment]
When LEM tries to start the debugger it seems to start another process. But there is an infinite loop that creates more and more processes in the background.

**Comment by Sasanidas** [comment]
Maybe we are using a different sdl2 version? That's quite an odd behaviour

**Comment by rpx99** [comment]
`tron$ doas pkg_info sdl2`
Information for inst:sdl2-2.28.5

Comment:
cross-platform multimedia library

Required by:
ffmpeg-4.4.4p2v1
sdl2-image-2.6.3
sdl2-ttf-2.20.2p2

sbcl:

* (ql:quickload :sdl2)
To load "sdl2":
  Load 1 ASDF system:
    sdl2
; Loading "sdl2"
...................
(:SDL2)
* (ql:quickload :sdl2-ttf)
To load "sdl2-ttf":
  Load 1 ASDF system:
    sdl2-ttf
; Loading "sdl2-ttf"

(:SDL2-TTF)
* (ql:quickload :sdl2-image)
To load "sdl2-image":
  Load 1 ASDF system:
    sdl2-image
; Loading "sdl2-image"

(:SDL2-IMAGE)
* (sdl2-ttf:init)
0
* (sdl2-ttf:linked-version)
2
20
2

`

**Comment by rpx99** [comment]
![screenshot_2023-12-11_16-41-12](https://github.com/lem-project/lem/assets/70011162/ce5c2d5e-5caa-4ce9-80e6-1de8da49a183)

Is it something like a null pointer in sdl2-ttf ?

**Comment by Sasanidas** [comment]
Maybe the version is sdl2 is too high?

In my case, the output of the above command is:
```
CL-USER> (sdl2-ttf:linked-version)
2
0
15
CL-USER> 
```

**Comment by rpx99** [comment]
<DEBUG> [20:01:38] lem-sdl2 main.lisp (delete-view sdl2) - lem-if:delete-view
<DEBUG> [20:01:38] lem-sdl2 main.lisp (display-width sdl2) -
  lem-if:display-width
<DEBUG> [20:01:38] lem-sdl2 main.lisp (display-height sdl2) -
  lem-if:display-height
<DEBUG> [20:01:38] lem-sdl2 main.lisp (display-height sdl2) -
  lem-if:display-height
<DEBUG> [20:01:38] lem-sdl2 main.lisp (make-view sdl2) -
  lem-if:make-view LEM-SDL2::WINDOW: #<LEM/POPUP-WINDOW::POPUP-WINDOW {1003B16903}>
  LEM-SDL2::X: 1 LEM-SDL2::Y: 16 LEM-SDL2::WIDTH: 47 LEM-SDL2::HEIGHT: 1
  LEM-SDL2::USE-MODELINE: NIL 
<DEBUG> [20:01:38] lem-sdl2 main.lisp (display-width sdl2) -
  lem-if:display-width
<DEBUG> [20:01:38] lem-sdl2 main.lisp (display-height sdl2) -
  lem-if:display-height
<DEBUG> [20:01:38] lem-sdl2 main.lisp (display-height sdl2) -
  lem-if:display-height
<DEBUG> [20:01:38] lem-sdl2 main.lisp (set-view-size sdl2) -
  lem-if:set-view-size LEM-SDL2::VIEW: #<LEM-SDL2/VIEW::VIEW {1003B16A73}>
  LEM-SDL2::WIDTH: 47 LEM-SDL2::HEIGHT: 1 
<DEBUG> [20:01:38] lem-sdl2 main.lisp (set-view-pos sdl2) -
  lem-if:set-view-pos LEM-SDL2::VIEW: #<LEM-SDL2/VIEW::VIEW {1003B16A73}>
  LEM-SDL2::X: 1 LEM-SDL2::Y: 16 
<DEBUG> [20:01:38] lem-sdl2 main.lisp (redraw-view-before sdl2) -
  lem-if:redraw-view-before LEM-SDL2::VIEW: #<LEM-SDL2/VIEW::VIEW {1003B16A73}> 
<DEBUG> [20:01:38] lem-sdl2 main.lisp (get-background-color sdl2) -
  lem-if:get-background-color
<DEBUG> [20:01:38] lem-sdl2 main.lisp (get-background-color sdl2) -
  lem-if:get-background-color
<DEBUG> [20:01:38] lem-sdl2 main.lisp (redraw-view-after sdl2) -
  lem-if:redraw-view-after LEM-SDL2::VIEW: #<LEM-SDL2/VIEW::VIEW {1003B16A73}> 
<DEBUG> [20:01:38] lem-sdl2 main.lisp (update-display sdl2) -
  lem-if:update-display
<DEBUG> [20:01:38] lem-sdl2 main.lisp (will-update-display sdl2) -
  will-update-display
<DEBUG> [20:01:38] lem-sdl2 main.lisp (display-width sdl2) -
  lem-if:display-width
<DEBUG> [20:01:38] lem-sdl2 main.lisp (display-height sdl2) -
  lem-if:display-height
<DEBUG> [20:01:38] lem-sdl2 main.lisp (redraw-view-before sdl2) -
  lem-if:redraw-view-before LEM-SDL2::VIEW: #<LEM-SDL2/VIEW::VIEW {1008E69133}> 
<DEBUG> [20:01:38] lem-sdl2 main.lisp (redraw-view-after sdl2) -
  lem-if:redraw-view-after LEM-SDL2::VIEW: #<LEM-SDL2/VIEW::VIEW {1008E69133}> 
<DEBUG> [20:01:38] lem-sdl2 main.lisp (redraw-view-before sdl2) -
  lem-if:redraw-view-before LEM-SDL2::VIEW: #<LEM-SDL2/VIEW::VIEW {1008E5A2C3}> 
<DEBUG> [20:01:38] lem-sdl2 main.lisp (redraw-view-after sdl2) -
  lem-if:redraw-view-after LEM-SDL2::VIEW: #<LEM-SDL2/VIEW::VIEW {1008E5A2C3}> 
<DEBUG> [20:01:38] lem-sdl2 main.lisp (redraw-view-before sdl2) -
  lem-if:redraw-view-before LEM-SDL2::VIEW: #<LEM-SDL2/VIEW::VIEW {10090683C3}> 
<DEBUG> [20:01:38] lem-sdl2 main.lisp (redraw-view-after sdl2) -
  lem-if:redraw-view-after LEM-SDL2::VIEW: #<LEM-SDL2/VIEW::VIEW {10090683C3}> 
<DEBUG> [20:01:38] lem-sdl2 main.lisp (redraw-view-before sdl2) -
  lem-if:redraw-view-before LEM-SDL2::VIEW: #<LEM-SDL2/VIEW::VIEW {10085B8D73}> 
<ERROR> [20:01:38] lem-core physical-line.lisp (call-with-display-error) -
  SDL Error (#<SDL-SURFACE {#X00000000}>): Text has zero width
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10014680A3}>
0: ((LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE))
1: ((FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX))
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<FUNCTION (FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX) {53B7415612B}>)
3: (UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE) {1003E4560B}> :PACKAGE :CL)
4: ((FLET "log-stmt1" :IN LEM-CORE::CALL-WITH-DISPLAY-ERROR) #<SB-PRETTY:PRETTY-STREAM {1003E453C3}>)
5: ((LAMBDA (STREAM LOG4CL-IMPL::FMT-INFO LOG4CL-IMPL::LOGGER LOG4CL-IMPL::LOG-LEVEL LOG4CL-IMPL::LOG-FUNC) :IN "/home/rpx/common-lisp/lem/.qlot/dists/quicklisp/software/log4cl-20230618-git/src/appender/pattern-layout.lisp") #<SB-PRETTY:PRETTY-STREAM {1003E453C3}> #<LOG4CL-IMPL::FORMAT-INFO {1008D14E03}> #<unused argument> #<unused argument> #<FUNCTION (FLET "log-stmt1" :IN LEM-CORE::CALL-WITH-DISPLAY-ERROR) {53B74156D8B}>)
6: ((LAMBDA (STREAM LOG4CL-IMPL::LOGGER LOG4CL-IMPL::LEVEL LOG4CL-IMPL::LOG-FUNC) :IN LOG4CL-IMPL::COMPILE-PATTERN-FORMAT) #<SB-PRETTY:PRETTY-STREAM {1003E453C3}> #<LOG4CL-IMPL::FILE-LOGGER LEM-CORE.CALL-WITH-DISPLAY-ERROR /home/rpx/common-lisp/lem/src/display/physical-line.lisp {10061903C3}> 2 #<FUNCTION (FLET "log-stmt1" :IN LEM-CORE::CALL-WITH-DISPLAY-ERROR) {53B74156D8B}>)
7: ((FLET "WITH-PRETTY-STREAM0" :IN SB-PRETTY::CALL-LOGICAL-BLOCK-PRINTER) #<SB-PRETTY:PRETTY-STREAM {1003E453C3}>)
8: (SB-PRETTY::CALL-LOGICAL-BLOCK-PRINTER #<FUNCTION (FLET "PPRINT-BLOCK" :IN "/home/rpx/common-lisp/lem/.qlot/dists/quicklisp/software/log4cl-20230618-git/src/appender/pattern-layout.lisp") {53B741565EB}> #<SB-SYS:FD-STREAM for "file /home/rpx/common-lisp/lem/lem.log" {1008A66AF3}> NIL NIL "" NIL)
9: ((LAMBDA (STREAM LOG4CL-IMPL::FMT-INFO LOG4CL-IMPL::LOGGER LOG4CL-IMPL::LOG-LEVEL LOG4CL-IMPL::LOG-FUNC LOG4CL-IMPL::WRAP) :IN "/home/rpx/common-lisp/lem/.qlot/dists/quicklisp/software/log4cl-20230618-git/src/appender/pattern-layout.lisp") #<SB-SYS:FD-STREAM for "file /home/rpx/common-lisp/lem/lem.log" {1008A66AF3}> #<LOG4CL-IMPL::PATTERN-PRETTY-FMT-INFO {1008C3EC13}> #<LOG4CL-IMPL::FILE-LOGGER LEM-CORE.CALL-WITH-DISPLAY-ERROR /home/rpx/common-lisp/lem/src/display/physical-line.lisp {10061903C3}> 2 #<FUNCTION (FLET "log-stmt1" :IN LEM-CORE::CALL-WITH-DISPLAY-ERROR) {53B74156D8B}> #<FUNCTION (LAMBDA (STREAM LOG4CL-IMPL::LOGGER LOG4CL-IMPL::LEVEL LOG4CL-IMPL::LOG-FUNC) :IN LOG4CL-IMPL::COMPILE-PATTERN-FORMAT) {1008CC336B}>)
10: ((LAMBDA (STREAM LOG4CL-IMPL::LOGGER LOG4CL-IMPL::LEVEL LOG4CL-IMPL::LOG-FUNC) :IN LOG4CL-IMPL::COMPILE-PATTERN-FORMAT) #<SB-SYS:FD-STREAM for "file /home/rpx/common-lisp/lem/lem.log" {1008A66AF3}> #<LOG4CL-IMPL::FILE-LOGGER LEM-CORE.CALL-WITH-DISPLAY-ERROR /home/rpx/common-lisp/lem/src/display/physical-line.lisp {10061903C3}> 2 #<FUNCTION (FLET "log-stmt1" :IN LEM-CORE::CALL-WITH-DISPLAY-ERROR) {53B74156D8B}>)
11: ((:METHOD LOG4CL-IMPL:LAYOUT-TO-STREAM (LOG4CL-IMPL:PATTERN-LAYOUT T T T T)) #<LOG4CL-IMPL:PATTERN-LAYOUT {1008A66AE3}> #<SB-SYS:FD-STREAM for "file /home/rpx/common-lisp/lem/lem.log" {1008A66AF3}> #<LOG4CL-IMPL::FILE-LOGGER LEM-CORE.CALL-WITH-DISPLAY-ERROR /home/rpx/common-lisp/lem/src/display/physical-line.lisp {10061903C3}> 2 #<FUNCTION (FLET "log-stmt1" :IN LEM-CORE::CALL-WITH-DISPLAY-ERROR) {53B74156D8B}>) [fast-method]
12: ((:METHOD LOG4CL-IMPL:APPENDER-DO-APPEND (LOG4CL-IMPL::FIXED-STREAM-APPENDER-BASE T T T)) #<LOG4CL-IMPL:DAILY-FILE-APPENDER {1004EE10B3}> #<LOG4CL-IMPL::FILE-LOGGER LEM-CORE.CALL-WITH-DISPLAY-ERROR /home/rpx/common-lisp/lem/src/display/physical-line.lisp {10061903C3}> 2 #<FUNCTION (FLET "log-stmt1" :IN LEM-CORE::CALL-WITH-DISPLAY-ERROR) {53B74156D8B}>) [fast-method]
13: ((SB-PCL::EMF LOG4CL-IMPL:APPENDER-DO-APPEND) #<unused argument> #<unused argument> #<LOG4CL-IMPL:DAILY-FILE-APPENDER {1004EE10B3}> #<LOG4CL-IMPL::FILE-LOGGER LEM-CORE.CALL-WITH-DISPLAY-ERROR /home/rpx/common-lisp/lem/src/display/physical-line.lisp {10061903C3}> 2 #<FUNCTION (FLET "log-stmt1" :IN LEM-CORE::CALL-WITH-DISPLAY-ERROR) {53B74156D8B}>)
14: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
15: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<FUNCTION (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN LOG4CL-IMPL:APPENDER-DO-APPEND) {53B741569EB}> #<SB-THREAD:MUTEX "Log4CL serialized appender lock" taken owner=main thread> T NIL)
16: ((:METHOD LOG4CL-IMPL:APPENDER-DO-APPEND :AROUND (LOG4CL-IMPL:SERIALIZED-APPENDER T T T)) #<LOG4CL-IMPL:DAILY-FILE-APPENDER {1004EE10B3}> #<LOG4CL-IMPL::FILE-LOGGER LEM-CORE.CALL-WITH-DISPLAY-ERROR /home/rpx/common-lisp/lem/src/display/physical-line.lisp {10061903C3}> 2 #<FUNCTION (FLET "log-stmt1" :IN LEM-CORE::CALL-WITH-DISPLAY-ERROR) {53B74156D8B}>) [fast-method]
17: ((LABELS LOG4CL-IMPL::LOG-TO-LOGGER-APPENDERS :IN LOG4CL-IMPL::LOG-WITH-LOGGER) #<LOGGER +ROOT+ {1005CB8433}> #<LOG4CL-IMPL::FILE-LOGGER LEM-CORE.CALL-WITH-DISPLAY-ERROR /home/rpx/common-lisp/lem/src/display/physical-line.lisp {10061903C3}> 2 #<FUNCTION (FLET "log-stmt1" :IN LEM-CORE::CALL-WITH-DISPLAY-ERROR) {53B74156D8B}>)
18: ((LABELS LOG4CL-IMPL::LOG-TO-LOGGER-APPENDERS :IN LOG4CL-IMPL::LOG-WITH-LOGGER) #<LOG4CL-IMPL::FILE-LOGGER LEM-CORE NIL {100666AF23}> #<LOG4CL-IMPL::FILE-LOGGER LEM-CORE.CALL-WITH-DISPLAY-ERROR /home/rpx/common-lisp/lem/src/display/physical-line.lisp {10061903C3}> 2 #<FUNCTION (FLET "log-stmt1" :IN LEM-CORE::CALL-WITH-DISPLAY-ERROR) {53B74156D8B}>)
19: ((LABELS LOG4CL-IMPL::LOG-TO-LOGGER-APPENDERS :IN LOG4CL-IMPL::LOG-WITH-LOGGER) #<LOG4CL-IMPL::FILE-LOGGER LEM-CORE.CALL-WITH-DISPLAY-ERROR /home/rpx/common-lisp/lem/src/display/physical-line.lisp {10061903C3}> #<LOG4CL-IMPL::FILE-LOGGER LEM-CORE.CALL-WITH-DISPLAY-ERROR /home/rpx/common-lisp/lem/src/display/physical-line.lisp {10061903C3}> 2 #<FUNCTION (FLET "log-stmt1" :IN LEM-CORE::CALL-WITH-DISPLAY-ERROR) {53B74156D8B}>)
20: (LOG4CL-IMPL::LOG-WITH-LOGGER #<LOG4CL-IMPL::FILE-LOGGER LEM-CORE.CALL-WITH-DISPLAY-ERROR /home/rpx/common-lisp/lem/src/display/physical-line.lisp {10061903C3}> 2 #<FUNCTION (FLET "log-stmt1" :IN LEM-CORE::CALL-WITH-DISPLAY-ERROR) {53B74156D8B}> #<PACKAGE "LEM-CORE">)
21: ((LAMBDA (LEM-CORE::E) :IN LEM-CORE::CALL-WITH-DISPLAY-ERROR) #<SDL2-TTF::SDL-TTF-ERROR {1003E44D23}>)
22: (SB-KERNEL::%SIGNAL #<SDL2-TTF::SDL-TTF-ERROR {1003E44D23}>)
23: (ERROR SDL2-TTF::SDL-TTF-ERROR :RC #<SDL2-FFI:SDL-SURFACE {#X00000000}> :STRING "Text has zero width")
24: (SDL2-TTF:RENDER-UTF8-BLENDED #<SDL2-FFI:TTF-FONT {#X53AC070E000}> #.(SB-SYS:INT-SAP #X53A8DFB4DE0) 255 255 255 0)
25: (LEM-SDL2/DRAWING::MAKE-TEXT-SURFACE #<LEM-SDL2/DISPLAY:DISPLAY {10080B7C13}> "🔒" #<LEM-CORE:ATTRIBUTE (white #404040) bold {1008DE8CA3}> :EMOJI)
26: (LEM-SDL2/DRAWING::MAKE-TEXT-SURFACE-WITH-CACHE #<LEM-SDL2/DISPLAY:DISPLAY {10080B7C13}> "🔒" #<LEM-CORE:ATTRIBUTE (white #404040) bold {1008DE8CA3}> :EMOJI)
27: ((:METHOD LEM-SDL2/DRAWING::GET-SURFACE :AROUND (T T)) #<LEM-CORE/DISPLAY:EMOJI-OBJECT {1003D97953}> #<LEM-SDL2/DISPLAY:DISPLAY {10080B7C13}>) [fast-method]
28: ((:METHOD LEM-SDL2/DRAWING::DRAW-OBJECT (LEM-CORE/DISPLAY:TEXT-OBJECT T T T T)) #<LEM-CORE/DISPLAY:EMOJI-OBJECT {1003D97953}> 27 420 #<LEM-SDL2/DISPLAY:DISPLAY {10080B7C13}> #<LEM-SDL2/VIEW::VIEW {10085B8D73}>) [fast-method]
29: (LEM-SDL2/DRAWING::REDRAW-PHYSICAL-LINE #<LEM-SDL2/DISPLAY:DISPLAY {10080B7C13}> #<LEM-SDL2/VIEW::VIEW {10085B8D73}> 0 399 (#<LEM-CORE/DISPLAY:TEXT-OBJECT {1003D97813}> #<LEM-CORE/DISPLAY:TEXT-OBJECT {1003D978B3}> #<LEM-CORE/DISPLAY:EMOJI-OBJECT {1003D97953}> #<LEM-CORE/DISPLAY:TEXT-OBJECT {1003D979F3}> #<LEM-CORE/DISPLAY:TEXT-OBJECT {1003D97AF3}>) 21)
30: ((LAMBDA (LEM-SDL2/DRAWING::DISPLAY) :IN LEM-INTERFACE:RENDER-LINE-ON-MODELINE) #<LEM-SDL2/DISPLAY:DISPLAY {10080B7C13}>)
31: ((LAMBDA NIL :IN LEM-CORE:REDRAW-BUFFER))
32: (LEM-CORE::CALL-WITH-DISPLAY-ERROR #<FUNCTION (LAMBDA NIL :IN LEM-CORE:REDRAW-BUFFER) {1003E3D6FB}>)
33: (SDL2::HANDLE-MESSAGE (#<FUNCTION (LAMBDA NIL :IN LEM-CORE:REDRAW-BUFFER) {1003B5BD7B}> . #S(TRIVIAL-CHANNELS:CHANNEL :QUEUE #S(TRIVIAL-CHANNELS.QUEUE:QUEUE :HEAD NIL :TAIL NIL) :Q-CONDITION #<SB-THREAD:WAITQUEUE Anonymous condition variable {1003B5BDD3}> :Q-MUTEX #<SB-THREAD:MUTEX "Anonymous lock" free owner=0>)))
34: (SDL2::GET-AND-HANDLE-MESSAGES)
35: ((LAMBDA NIL :IN LEM-SDL2::EVENT-LOOP))
36: ((LAMBDA NIL :IN LEM-SDL2::CREATE-DISPLAY))
37: (LEM-SDL2::CREATE-DISPLAY #<FUNCTION (FLET LEM-SDL2::THUNK :IN LEM-INTERFACE:INVOKE) {1007BBEB6B}>)
38: ((LAMBDA NIL :IN LEM-INTERFACE:INVOKE))
39: (SDL2::HANDLE-MESSAGE (#<FUNCTION (LAMBDA NIL :IN LEM-INTERFACE:INVOKE) {1007BBF3CB}>))
40: (SDL2::SDL-MAIN-THREAD)
41: (SB-INT:SIMPLE-EVAL-IN-LEXENV (LEM-CORE:LEM "--debug" "--log-filename" "lem.log") #<NULL-LEXENV>)
42: (EVAL (LEM-CORE:LEM "--debug" "--log-filename" "lem.log"))
43: (SB-EXT:INTERACTIVE-EVAL (LEM-CORE:LEM "--debug" "--log-filename" "lem.log") :EVAL NIL)
44: (SB-IMPL::REPL-FUN NIL)
45: ((LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL))
46: (SB-IMPL::%WITH-REBOUND-IO-SYNTAX #<FUNCTION (LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL) {53B74157C1B}>)
47: (SB-IMPL::TOPLEVEL-REPL NIL)
48: (SB-IMPL::TOPLEVEL-INIT)
49: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
50: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
51: (SB-IMPL::%START-LISP)

**Comment by rpx99** [comment]
Here the complete log file: [lem.log](https://github.com/lem-project/lem/files/13664692/lem.log)

**Comment by rpx99** [comment]
Okay, I find this symbol in src / lem / modeline.lisp:

`(defun modeline-write-info (window)
  (let ((buffer (window-buffer window)))
    (cond ((buffer-read-only-p buffer)
           " 🔒 ")
          ((buffer-modified-p buffer)
           " * ")
          (t
           "   "))))`

There is a method:

`(defmethod object-width ((drawing-object emoji-object) display)
  (* (display:display-char-width display) 2 (length (text-object-string drawing-object))))`

in src / frontends / sdl2 / drawing.lisp

I wonder why it needs to get multiplied by the length of the text-object string of the drawing-object....

Suspect that it is 0...

**Comment by rpx99** [comment]
I am at the right spot. If I replace the lock symbol in modeline with an ordinary Character the issue is gone and I get into the debugger. The replacement character is then shown in the modeline of the debugger.

Still looking into the real issue, i.e. why the lock symbol causes so much trouble...

**Comment by Sasanidas** [comment]
Interesting! Thanks for doing the research, indeed this seems like a very specific sdl2 problem... I'm not that familiar with, so I'll ping @cxxxr so he maybe help in this error.

**Comment by rpx99** [comment]
In html here it looks "ok", but when I see my screenshot the LOCK character does not look properly (like an additional space is used as a second symbol).

@Sasanidas What does this show on your system? 

* (make-string 1 :initial-element #\GREEK_CAPITAL_LETTER_SIGMA)
"Σ"
* (SDL2-TTF:RENDER-UTF8-BLENDED (sdl2-ttf:open-font #P"/home/rpx/common-lisp/lem/frontends/sdl2/resources/fonts/NotoColorEmoji.ttf" 15) (make-string 1 :initial-element #\GREEK_CAPITAL_LETTER_SIGMA) 255 255 255 0)
#<SDL2-FFI:SDL-SURFACE {#X929E5262360}>
* (make-string 1 :initial-element #\LOCK)
"🔒"
* (SDL2-TTF:RENDER-UTF8-BLENDED (sdl2-ttf:open-font #P"/home/rpx/common-lisp/lem/frontends/sdl2/resources/fonts/NotoColorEmoji.ttf" 15) (make-string 1 :initial-element #\LOCK) 255 255 255 0)

debugger invoked on a SDL2-TTF::SDL-TTF-ERROR in thread
#<THREAD "main thread" RUNNING {1001480003}>:
  SDL Error (#<SDL-SURFACE {#X00000000}>): Text has zero width


![Screenshot_2023-12-18_09-34-42](https://github.com/lem-project/lem/assets/70011162/4fc5420e-fe76-41bd-95a5-b9bbcbd11faf)

**Comment by Sasanidas** [comment]
For me, it works correctly, it doesn't trigger any error:
```
CL-USER> (make-string 1 :initial-element #\GREEK_CAPITAL_LETTER_SIGMA)
"Σ"
CL-USER> (SDL2-TTF:RENDER-UTF8-BLENDED (sdl2-ttf:open-font #P"/home/f/common-lisp/lem/frontends/sdl2/resources/fonts/NotoColorEmoji.ttf" 15) (make-string 1 :initial-element #\GREEK_CAPITAL_LETTER_SIGMA) 255 255 255 0)
CL-USER> (SDL2-TTF:RENDER-UTF8-BLENDED (sdl2-ttf:open-font #P"/home/fermin/quicklisp/local-projects/lem/frontends/sdl2/resources/fonts/NotoColorEmoji.ttf" 15) (make-string 1 :initial-element #\GREEK_CAPITAL_LETTER_SIGMA) 255 255 255 0)
#<SDL2-FFI:SDL-SURFACE {#X7F8ABC00F210}>
CL-USER> (make-string 1 :initial-element #\LOCK)
"🔒"
CL-USER> (SDL2-TTF:RENDER-UTF8-BLENDED (sdl2-ttf:open-font #P"/home/fermin/quicklisp/local-projects/lem/frontends/sdl2/resources/fonts/NotoColorEmoji.ttf" 15) (make-string 1 :initial-element #\LOCK) 255 255 255 0)
#<SDL2-FFI:SDL-SURFACE {#X7F8ABC009F00}>
```

![sdl2_lock](https://github.com/lem-project/lem/assets/26670956/51ba08bc-3fd2-4072-85f5-362e9440ed01)

**Comment by Sasanidas** [comment]
(ignore the second line of t he screenshot, I just press enter with the path not fully changed)

**Comment by rpx99** [comment]
Thanks a lot for testing!

Well, I did a (hopefully) clean debian 12 installation following the instructions using qlot.

Get the same error as I have with OpenBSD.

It seems your sdl2 is older and you have not the "official" qlot version installed / some files mixed in from your quicklisp installation?

**Comment by badmrfrosty** [comment]
Hello,

I have the same problem as rpx99 : 
![pic-selected-231218-1954-14](https://github.com/lem-project/lem/assets/49749436/826e0df8-5824-4e67-91e7-3df53905aeb0)

**Comment by rpx99** [comment]
@badmrfrosty Yes, that is when you use this command. If you type in "inspect" it should get into a loop (You can abort with pressing q). Which OS do you have?

**Comment by badmrfrosty** [comment]
Yeah, more or less same behaviour but I had to kill the lem process (see pictures)

`uname -r
6.6.7-arch1-1`

`CL-USER> (sdl2-ttf:linked-version)
2
20
2`

![pic-selected-231219-2040-58](https://github.com/lem-project/lem/assets/49749436/663dd0cf-bb79-4e68-b48a-f4a95db06c5c)
![pic-selected-231219-2042-22](https://github.com/lem-project/lem/assets/49749436/09a98b68-cf2c-453b-868e-998139cfdb06)

**Comment by rpx99** [comment]
Found out how to work around it on OpenBSD.

Followed this instructions on [Reddit](https://www.reddit.com/r/openbsd/comments/1atanzd/comment/kr4003n/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) in order to recompile Xenocara. 

Additionally I recompiled the **SDL2-TTF** port with added **CONFIGURE_ARGS += --disable-freetype-builtin** parameter in the Makefile.

Quite time consuming build process but at least a success...

```
* (SDL2-TTF:RENDER-UTF8-BLENDED (sdl2-ttf:open-font #P"/home/rpx/common-lisp/lem/frontends/sdl2/resources/fonts/NotoColorEmoji.ttf" 15) (make-string 1 :initial-element #\LOCK) 255 255 255 0)
#<SDL2-FFI:SDL-SURFACE {#XB3CB9A21960}>

```
