### ISSUE TITLE
https://lem-project.github.io/GUI/SDL2/ Grammar Error

### ISSUE THREAD

**Issue by tmheath** [lem-project/lem#1180]
In the below line there is an error bad enough that I cannot understand exactly what is meant.
"Lem developpers are investigated to interface with Trial, the game engine of the Kandria game."
If I'm told what is meant then I'll go ahead and fix this, I'm not trying to be rude or picky, it's just a one word issue.
Possible corrections, non-exhaustive:
- "Lem developers are invested in interfacing to Trial, the game engine of the Kandria game."
- "Lem developers are interested in interfacing to Trial, the game engine of the Kandria game."
- "Lem developers are working on interfacing to Trial, the game engine of the Kandria game."
- "Lem developers are investigating interfacing to Trial, the game engine of the Kandria game."
The issue primarily is that the word is past tense and kind of similar to another word. Included here is
a fix for a minor typo.

Thanks, Timothy

**Comment by Sasanidas** [comment]
Indeed that doesn't sound good.. I guess maybe I translate it from japanese or something.

From the context, I add the latest phrase that you propose https://github.com/lem-project/lem-project.github.io/commit/e3df486d12b6f249e3732deae6cbbb53edd8b39c

**Comment by Sasanidas** [comment]
I'll close this issue now, given that I think a fix it correctly. Feel free to open it again if that wasn't the case :+1:
