### ISSUE TITLE
[Performance][Windows] High resource use even when idle.

### ISSUE THREAD

**Issue by tmheath** [lem-project/lem#1181]
I noticed while messing around earlier that the new binary
release (2.1) of Lem running on Windows 10 only idled
around 3% as compared to 0% from the old version. My
hunch is that some feature that tracks the mouse constantly
on a single thread was added because when I move the mouse,
even with Lem minimized, the processing of Lem increases to
a maximum of a bit over 6%. The reason that I think this is a
hundred divided by the number of threads in this laptop is the
maximum resource usage. I don't know if Lem itself is single
threaded but this might still be a single newly added feature
because the last binary release idled at 0% irrespective of
other workings, while the new release idles variable against
what the mouse is doing.

I will not investigate this potential performance bug as I don't
have the time but I figured it'd be good to document it at least.
Not certain this is in fact a problem.

**Comment by Sasanidas** [comment]
Thanks for  commenting the issue, I don't have any windows machine to test, so if someone with windows read this issue, feel free to test it :+1:

**Comment by vindarel** [comment]
Do you notice a performance hit or even a lag when you run M-x commands (or do anything really)? I did and found a workaround: https://github.com/lem-project/lem/issues/1092
