### ISSUE TITLE
installer

### ISSUE THREAD

**Issue by MarcRohrer** [lem-project/lem#1187]
Hi,

I wanted to try lem, as it sounds very interesting.
But I am too stupid to find the windows binaries.
Could you give me a hint please?

Best wishes!

Marc

**Comment by rpx99** [comment]
Hi Marc, welcome and indeed it is. Here you go:

https://github.com/lem-project/lem/releases/download/v2.1.0/lem-windows-v2.1.0.zip

https://github.com/lem-project/lem/releases/tag/v2.1.0

**Comment by MarcRohrer** [comment]
Hi,

perfect, thanx!
Wouldn't it make sense to link it here?

https://lem-project.github.io//installation/sdl2/windows/

I went back and forth from there, suspecting I don't understand the structure of the page...

Marc

**Comment by rpx99** [comment]
Yeah, we need to ask one of the devs.
