### ISSUE TITLE
vi-mode: Visual block not showing changes until I press ESC

### ISSUE THREAD

**Issue by olnw** [lem-project/lem#1188]
In vi-mode, I can select a visual block using `C-v`, then press `I` or `A`. After typing some text, `ESC` will insert it at the start or end of each line.

However, no changes are shown until I hit `ESC`, meaning I cannot see what I am typing. This is contrary to the behaviour of Vim and Neovim.

Happens in both SDL2 and ncurses. I'm using lem commit be98202b2001fad07e3b108ce190a017d7a3ba3b

**Comment by cxxxr** [comment]
merge with https://github.com/lem-project/lem/issues/278
