### ISSUE TITLE
vi-mode: exit with Z Q

### ISSUE THREAD

**Issue by olnw** [lem-project/lem#1189]
In Vim, you can exit the editor with `Z Q` (quit without saving).

https://vimdoc.sourceforge.net/htmldoc/editing.html#ZQ

Edit: realised `Z Z` is already implemented https://github.com/lem-project/lem/pull/91

**Comment by Sasanidas** [comment]
Seems then this is solved, I'll close the issue then, feel free to open it again if is not the case :+1:
