### ISSUE TITLE
Mmap error when using the arm64 release in a Macbook Pro M3

### ISSUE THREAD

**Issue by joaogui1** [lem-project/lem#1202]
Hi!
I downloaded lem 2.1 from the release pages, but when I tried running either the sdl2 or the ncurses versions I get an mmap error
```shell
mmap: Operation not permitted
fatal error encountered in SBCL pid 71282 pthread 0x1e2f69000:
load_core_bytes(3,0x66b0000,0x300000000,10000) failed
``
`
Any ideas what the error could be?

**Comment by cxxxr** [comment]
https://github.com/lem-project/lem/issues/1113
As per this issue.
Sorry we haven't been able to release...
