### ISSUE TITLE
Collaborative editing

### ISSUE THREAD

**Issue by cxxxr** [lem-project/lem#1235]

**Comment by Sasanidas** [comment]
I think https://code.librehq.com/qhong/crdt.el can be an interesting inspiration :100:

**Comment by appetrosyan** [comment]
I think rewriting it would require some infrastructure. We used quite a bit of Emacs' async shell, and I don't recall `lem` having those facilities.

**Comment by cxxxr** [comment]
This will be done in a separate project from lem.
