### ISSUE TITLE
Error when opening a file on MacOS

### ISSUE THREAD

**Issue by solanav** [lem-project/lem#1246]
Just compiled lem-sdl2 for the M1 Pro with Sonoma 14.2.1 and got this error when trying to open a lisp file. Is there a debug mode that I can use to see whats causing this?

![image](https://github.com/lem-project/lem/assets/32469597/966eab71-8f2f-4c5d-85f1-2d56bb399a61)

**Comment by mychris** [comment]
Are you sure you are using the recent revision? This looks like #1240 
The error message is the same as in the stack trace.

**Comment by solanav** [comment]
It does seem like that was the problem, thanks and sorry for bothering!
