### ISSUE TITLE
Docker container issues

### ISSUE THREAD

**Issue by blakemcbride** [lem-project/lem#1271]
I have two problems with using a docker container as follows:

Problem n°1

```
$ docker build -t lem .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

```

Problem n°2

When I try to save a file to /shared I get permission denied.  I tried starting it up in /tmp and got the same error.  (/tmp is 777).

**Comment by blakemcbride** [comment]
The second problem is fixed by running:  `docker run --rm -it --privileged -v .:/shared lem`

**Comment by elken** [comment]
Seems neither are related to Lem, but:

1. `docker buildx build -t lem .` (assuming you're on docker 19.03 or higher, otherwise follow the link for install instructions)

2.  As you said, it's a permissions issue

I can try to spend some time on the Docker setup & integrating ghcr soon :smile:
