### ISSUE TITLE
Eval keybindings not working on ncurses version (macOS Sonoma, M1)

### ISSUE THREAD

**Issue by wyan** [lem-project/lem#1284]
I have built the `ncurses` version according to the instructions, on an M1 laptop (aarch64) running macOS Sonoma 14.2.1 and SBCL 2.4.1 installed via Homebrew.

When I run `lem` and type in a Lisp form followed by `C-x C-e` I get a `Key not found: C-x C-e` popup message, instead of having Lem evaluate the form.

**Comment by cxxxr** [comment]
It is probably because the startup buffer is in fundamental-mode.
You can use c-x c-e by doing M-x lisp-mode or opening a lisp file.

**Comment by cxxxr** [comment]
Thanks for trying lem, Happy hacking!

**Comment by wyan** [comment]
Indeed, that was the problem, sorry about the inconvenience and thanks for your help! :)

I guess I can add `(lisp-mode)` to the startup file to automatically start in lisp-mode?

**Comment by cxxxr** [comment]
> I guess I can add (lisp-mode) to the startup file to automatically start in lisp-mode?

Yes.
However, this behavior is just a coincidence of timing, and there is no guarantee that it will not change with future changes.

Please let the permanent solution be a matter for the future.
