### ISSUE TITLE
quri on lem not loading during quickload

### ISSUE THREAD

**Issue by rabbibotton** [lem-project/lem#1285]
When using lem (and no other installation of sbcl) I receive the following error related to quri while quickloading my projects (on any platform, this particular quote from windows)

[package quri.etld]
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     The file
;     #P"C:/msys64/home/g23tl/quicklisp/dists/quicklisp/software/quri-20221106-git/data/effective_tld_names.dat"
;     does not exist:
;       The system cannot find the file specified.
;   
;     (in form starting at line: 34, column: 0, position: 1332)

This is a LEM specific issue.

**Comment by rabbibotton** [comment]
The inability to load a project you quri is using the binary packages for Ubuntu and Windows of Lem. 

M-x start-lisp-repl
(ql:quickload :quri)

![image](https://github.com/lem-project/lem/assets/11616789/c3d44082-6a20-441f-bffc-a597d08cb518)

**Comment by rabbibotton** [comment]
here is same error on Ubuntu

![image](https://github.com/lem-project/lem/assets/11616789/98fcda74-778f-49d7-9a6a-28d4a2bde082)

**Comment by rabbibotton** [comment]
Is this just broken in your release versions?

**Comment by vindarel** [comment]
Strange it's related only to quri. Can you not use it straight away?

     (quri:uri "http:hello.com") 

and can you quickload another library?

**Comment by rabbibotton** [comment]
Yes loading other libraries work and the parts of quri that are there work. This may help more;

Couldn't load
#P"/home/dbotton/.lem/quicklisp/dists/quicklisp/software/quri-20230618-git/src/etld.fasl":
file does not exist.
   [Condition of type SB-INT:SIMPLE-FILE-ERROR]

The compiled version is missing some of quri but not all. I assume convincing quicklisp to erase any cache for quri and reloading and compiling would solve this. I'll see if I can find what needs to be done.

I would be super neat to use lem on Windows and really any platform as an answer instead of portacle

**Comment by rabbibotton** [comment]
M-x start-lisp-repl

is that the best way to get a repl for dev? Or am I supposed to install my own lisp and slime?

**Comment by vindarel** [comment]
Is there a mismatch between your QL version and the one Lem refers to? (I'm not sure what comes with Lem but that may be a clue)

> M-x start-lisp-repl
> 
> is that the best way to get a repl for dev? Or am I supposed to install my own lisp and slime?

yes and no, that's the way! No need to install something else.

> Windows and really any platform

That's the goal! And so far Lem has impressively delivered. Binaries for the three platforms: https://github.com/lem-project/lem/releases/tag/v2.1.0

**Comment by rabbibotton** [comment]
"That's the goal! And so far Lem has impressively delivered. Binaries for the three platforms: https://github.com/lem-project/lem/releases/tag/v2.1.0"

That is what I am using - on any one of those try - (ql:quickload :quri) to reproduce my error

**Comment by rabbibotton** [comment]
Using (ql:uninstall :quri)  (again in one for the release tarballs) and then (ql:quickload :quri) produces same error as well

I assume the issues is in the actual lisp image being delivered in your releases.

**Comment by rabbibotton** [comment]
Any news on this?

**Comment by cxxxr** [comment]
I think there are too many restrictions to work on the release version of the lem runtime.
I think you need to start a new sbcl with the M-x slime command and quickload in it, or build lem yourself.
