### ISSUE TITLE
What are the command line options for the Lem editor?

### ISSUE THREAD

**Issue by vonHabsi** [lem-project/lem#1292]
What are the command line options for the Lem editor?

Does Lem provide  the Emacs option which opens the editor in a particular X-Window, `ie --parent-d=xid`?

Does it provide the `--daemon` of starting Emacs in the background and attaching a frame using an `emacsclient` equivalent?

**Comment by cxxxr** [comment]
Hi, thanks for trying lem.
Basically, it is different from GNU emacs and does not provide such functionality.
The help can be seen below.
```
$ lem -h
Usage: lem [ OPTION-OR-FILENAME ] ...
Options:
        -q, --no-init-file      do not load ~/.lem/init.lisp
        --slime PORT            start slime on PORT
        --eval EXPR             evaluate lisp expression EXPR
        --debug                 enable debugger
        --log-filename FILENAME file name of the log file
        --kill                  immediately exit
        -v, --version           print the version number and exit
        -h, --help              display this help and exit
```
