### ISSUE TITLE
Severe rendering performance issues with SDL2 in WSL

### ISSUE THREAD

**Issue by daedsidog** [lem-project/lem#1332]
Performance in the SDL2 version in WSL grinds to a halt when the screen is filled with text. Less than a single frame per second is rendered when I just fill my screen with characters. Doesn't happen with the ncurses or Windows version.

I would usually disregard this as a WSL issue (which it probably still is) but other GUI apps are okay (Emacs) and I've tried some other SDL2 programs (at least I think they were) and they were okay.

It's possible it could be a problem with my `SDL2_ttf`?

```
OS: Arch Linux on Windows 10 x86_64
Kernel: 5.15.146.1-microsoft-standard-WSL2
Uptime: 12 mins
Packages: 904 (pacman)
Shell: bash 5.2.26
Theme: Adwaita [GTK3]
Icons: Adwaita [GTK3]
Terminal: Relay(12)
CPU: Intel i7-9750H (12) @ 2.591GHz
GPU: c532:00:00.0 Microsoft Corporation Basic Render Driver
Memory: 419MiB / 7871MiB
```

![ttf](https://github.com/lem-project/lem/assets/41439659/10d1019a-3ca7-4655-ab44-f7eb33b33aed)

**Comment by daedsidog** [comment]
I've done some profiling and experimentation & came to the conclusion this isn't an SDL2 bug, but a WSL bug.

The culprit of the slowdown is `sdl2:create-texture-from-surface`.

Turns out having hardware acceleration enabled in SDL2 programs causes some problems. There's an issue about it (https://github.com/libsdl-org/SDL/issues/6333), which is closed.

However, inspired by https://github.com/libsdl-org/SDL/issues/6333#issuecomment-1293872149, disabling hardware acceleration for SDL2 via

```
export SDL_RENDER_DRIVER=software
```

completely and totally fixes the issue.

This can be closed now as this isn't a Lem-specific bug, but a WSL one. GTK programs suffer from this too (to a lesser extent).

**Comment by cxxxr** [comment]
@daedsidog Thank you!
I will quote the link to your comment in the document and close this issue.
