### ISSUE TITLE
Rounding error in mouse coordinates on SDL2 filer interface

### ISSUE THREAD

**Issue by mantacid** [lem-project/lem#1342]
When using the SDL2 binary on X11, the filer pane has a small error in how the mouse coordinates are calculated, resulting in vertical inaccuracy that compounds as the mouse moves closer to the bottom of the window. This inaccuracy doesn't happen anywhere else (such as in the buffer editor or the REPL); it only occurs in the filer pane.
![Screenshot_20240320_140628](https://github.com/lem-project/lem/assets/123284210/7da27db4-ab67-4091-8ae9-40b5d75510aa)

**Comment by cxxxr** [comment]
I think it is solved by this commit.
https://github.com/lem-project/lem/commit/6b26859ad1cc34f8ae2e46b8355ce7f15f729574
