### ISSUE TITLE
Mouse offset in sidebar/filer

### ISSUE THREAD

**Issue by BierLiebHaber** [lem-project/lem#1365]
When using the filer in the sdl2 version the apparent mouse position gets more and more out of sync the further down I go.
Here are some screenshots to illustrate:
This is correct (The mouse is at the mouse is close to the top edge of the window):
![Screenshot_correct](https://github.com/lem-project/lem/assets/432988/6a36a0a9-c21d-4132-820d-e8c9105c23cd)
This is incorrect (the mouse is close to the bottom edge of the window):
![Screenshot_incorrect](https://github.com/lem-project/lem/assets/432988/45c8787b-5b47-44d6-9f1e-b968a63c27df)

I think the problem is caused by the rendering error (the boxes instead of arrows on the left), since the boxes are bigger than any other text.
If I scroll down to the files the problem is less severe (here to mouse is closer to the bottom than in the 2. screenshot):
![Screenshot_bonus](https://github.com/lem-project/lem/assets/432988/d0f396fa-537a-435c-a17b-ae0c2eabefe6)

**Comment by BierLiebHaber** [comment]
Duplicate of #1342

**Comment by cxxxr** [comment]
The fundamental issue lies elsewhere, but this fix should have resolved it.
https://github.com/lem-project/lem/commit/6b26859ad1cc34f8ae2e46b8355ce7f15f729574
