### ISSUE TITLE
Empty window on both sdl2 and ncurses

### ISSUE THREAD

**Issue by BierLiebHaber** [lem-project/lem#1382]
I get an empty (black) window on both ncurses and sdl2 after https://github.com/lem-project/lem/commit/acb910afc36b8d97c93c2e39aa41253921669ad3

**Comment by BierLiebHaber** [comment]
The reason is https://github.com/lem-project/lem/blob/26583dad15d11efc56857283717a102e2296790d/src/defcommand.lisp#L25
I don't think we should `break` here. I think a `warn` is fine but breaking all custom commands seems extreme 😅

**Comment by cxxxr** [comment]
Yes, I have changed it.
