### ISSUE TITLE
LEM dissect error

### ISSUE THREAD

**Issue by rpx99** [lem-project/lem#1393]
After a while I am back on LEM. 

Updated LEM to latest git version and used qlot install.

When I run `(ql:quickload :lem-sdl2)` using SBCL 2.4.5.openbsd.sbcl-2.4.5 I run into:

[package dissect]...; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Lock on package SB-DI violated when interning DEBUG-VAR-INFO while in package
;     DISSECT.
;   See also:
;     The SBCL Manual, Node "Package Locks"
;   
;     (in form starting at line: 38, column: 0, position: 1539)

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD tid=491958 "main thread" RUNNING {1000DF0003}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "dissect" "backend" "sbcl">

Any suggestions ?

**Comment by cxxxr** [comment]
I think it will probably be fixed by updating to the latest version of dissect.
It doesn't reproduce on my ubuntu and sbcl 2.4.5, though.

**Comment by rpx99** [comment]
Oh, here it is:
https://github.com/Shinmera/dissect/issues/18

**Comment by rpx99** [comment]
I put it into my common-lisp folder. Works! Thanks again.

**Comment by cxxxr** [comment]
I'm glad it was resolved.
I also recommend using qlot.
