### ISSUE TITLE
Warnings in sdl2-examples

### ISSUE THREAD

**Issue by rpx99** [lem-project/lem#1394]
[package sdl2-examples]...........................
..................................................
..................................................
..............................; pkg-config libffi --cflags
-I/usr/local/include
; cc -o /home/rpx/.cache/common-lisp/sbcl-2.4.5.openbsd.sbcl-2.4.5-bsd-x64/home/rpx/common-lisp/lem/.qlot/dists/quicklisp/software/cffi-20231021-git/libffi/libffi-types__grovel-tmp1HKLMSTH.o -c -O2 -pipe -g -g -Wall -Wundef -Wsign-compare -Wpointer-arith -I/usr/local/include -fno-omit-frame-pointer -I/usr/local/include -I/usr/local/include -fPIC -I/home/rpx/common-lisp/lem/.qlot/dists/quicklisp/software/cffi-20231021-git/ /home/rpx/.cache/common-lisp/sbcl-2.4.5.openbsd.sbcl-2.4.5-bsd-x64/home/rpx/common-lisp/lem/.qlot/dists/quicklisp/software/cffi-20231021-git/libffi/libffi-types__grovel.c
/home/rpx/.cache/common-lisp/sbcl-2.4.5.openbsd.sbcl-2.4.5-bsd-x64/home/rpx/common-lisp/lem/.qlot/dists/quicklisp/software/cffi-20231021-git/libffi/libffi-types__grovel.c:11:7: warning: unused variable 'autotype_tmp' [-Wunused-variable]
  int autotype_tmp;
      ^
1 warning generated.
; cc -o /home/rpx/.cache/common-lisp/sbcl-2.4.5.openbsd.sbcl-2.4.5-bsd-x64/home/rpx/common-lisp/lem/.qlot/dists/quicklisp/software/cffi-20231021-git/libffi/libffi-types__grovel-tmpEWG5XJ53 -g -Wl,--export-dynamic -Wl,-z,wxneeded /home/rpx/.cache/common-lisp/sbcl-2.4.5.openbsd.sbcl-2.4.5-bsd-x64/home/rpx/common-lisp/lem/.qlot/dists/quicklisp/software/cffi-20231021-git/libffi/libffi-types__grovel.o
; /home/rpx/.cache/common-lisp/sbcl-2.4.5.openbsd.sbcl-2.4.5-bsd-x64/home/rpx/common-lisp/lem/.qlot/dists/quicklisp/software/cffi-20231021-git/libffi/libffi-types__grovel /home/rpx/.cache/common-lisp/sbcl-2.4.5.openbsd.sbcl-2.4.5-bsd-x64/home/rpx/common-lisp/lem/.qlot/dists/quicklisp/software/cffi-20231021-git/libffi/libffi-types__grovel.grovel-tmp.lisp

**Comment by cxxxr** [comment]
Please be assured that the warning about the dependent library is not a problem with LEM and will not affect its operation.

**Comment by rpx99** [comment]
Thank you.
