### ISSUE TITLE
Micro dependency

### ISSUE THREAD

**Issue by BrunoCiccarino** [lem-project/lem#1412]
What is this micro dependency? Because I've been trying to configure cl-lsp for a day, but it doesn't work because the lem.asd file is asking for a dependency called micros, but I can't find it anywhere to download it... How do I find it to download it? Or can I edit my lem.asd file to remove it?

**Comment by cxxxr** [comment]
Here is it
https://github.com/lem-project/lem/blob/2c6a0da38594d4eb2c28a0151326bc19994fecb9/qlfile#L1C12-L1C53

**Comment by BrunoCiccarino** [comment]
Thanks
