### ISSUE TITLE
SDL2:  Remapped Capslock->CTRL key doesn't act like CTRL when in VI-MODE

### ISSUE THREAD

**Issue by xedrac** [lem-project/lem#1417]
I map my CAPSLOCK key to an additional CTRL key in Linux.  When using Lem/SDL2 with VI-MODE, this mapping is not honored.  It works correctly in Lem+ncurses, but incorrectly in Lem/SDL2.

To reproduce this, open a file with Lem/SDL2, put the editor in vi-mode (M-x: vi-mode), then press CTRL-d to scroll down a page.  Using the default CTRL key works, but the remapped CAPS->CTRL key does not.

It is worth noting that the remapped CAPSLOCK->CTRL key works correctly outside of vi-mode, at least on latest main (but it was broken in 2.2.0).

Tested on:
   Date:  July 2, 2024
   Commit:  34843b3a7f97a118c6c9691e4eba43d2c0f1b5f8

**Comment by garlic0x1** [comment]
How are you remapping keys? Xmodmap seems to work fine for me on the main branch of Lem

**Comment by xedrac** [comment]
I switched to a lower lever mechanism to remap the keys (https://github.com/xremap/xremap) and now it works.  I'm guessing that SDL2 gets the keyboard events before Gnome's keyboard modifier tweaks are applied.  But now that it's done with evdev and uinput, it works universally, including on the console.
