### ISSUE TITLE
clim paste problem

### ISSUE THREAD

**Issue by rpx99** [lem-project/lem#1464]
@cnickh Not totally sure, but there seems to be a paste problem in the clim version ?

![image](https://github.com/user-attachments/assets/3a7fc78d-8612-4d3f-b7a7-decb5b577e1f)

**Comment by cxxxr** [comment]
Please refrain from raising issues in lem about features that are only available in forked repositories.

**Comment by rpx99** [comment]
Understand. Thanks.
