### ISSUE TITLE
Standard document/non-programming attributes

### ISSUE THREAD

**Issue by jfaz1** [lem-project/lem#1468]
I'll do this one if you guys think it's a good idea.

We should consider coming up with some standard attributes for document/non-programming modes, for both consistency and to make life easier for extension writers and theme creators.

If you look at `markdown-mode`, several programming attributes are used so that it works with themes out of the box. For example, `syntax-constant-attribute` is used for titles. 

I propose lem include a set of generic attributes specifically for non-programming or presentation formats (e.g. markdown, org-mode, legit commit messages, etc.) that cover most bases. For example, something like 6 header/title attributes, a hyperlink attribute, bold/italic attributes, etc.

This way, we can make it easier for themes to have customized styling for text that doesn't bleed into programming modes, and extension writers have defaults they can rely on to work with most themes. 

@cxxxr @vindarel any thoughts?

**Comment by cxxxr** [comment]
I think it's a good idea.
