### ISSUE TITLE
Add SDL2 dependencies to instructions for installing from scratch

### ISSUE THREAD

**Issue by pamoroso** [lem-project/lem#1470]
The [instructions for installing Lem from scratch](https://lem-project.github.io/installation/ncurses/linux) on Linux don't mention the following dependencies required by the SDL2 version, without which the build fails with an error:

• libsdl2-dev
• libsdl2-ttf-dev
• libsdl2-image-dev

This confused me more than once, so it would be helpful to add the list to the instructions.

**Comment by cxxxr** [comment]
https://lem-project.github.io/installation/sdl2/linux/
It appears to be here.

**Comment by pamoroso** [comment]
Thanks, I had missed it.
