### ISSUE TITLE
hangs when inserting large amounts of text with universal argument

### ISSUE THREAD

**Issue by mattheson** [lem-project/lem#1488]
When prefixing text insertion with "C-u 50000" or any very large number (~50,000 seems to be where this problem starts for me) after which you can type any key such as 'a', space, C-o, etc. results in Lem hanging.

I'm on macOS Sonoma using SBCL and Lem built from main with `make sdl2`/`make ncurses`. Happens with ncurses and sdl2 versions.

I get many different memory-related errors (sometimes after hitting C-c in my terminal) suggesting this causes an overflow somewhere.
```
INFO: Control stack guard page unprotected
INFO: Alien stack guard page unprotected
INFO: Control stack guard page reprotected
INFO: Binding stack guard page unprotected
fatal error encountered in SBCL pid 61383 pthread 0x16fca7000:
misuse of mprotect() on dynamic space @ 0x70030418e0

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
(GC in progress, oldspace=0, newspace=7)
ldb>
```

```
INFO: Control stack guard page unprotected
CORRUPTION WARNING in SBCL pid 64509 pthread 0x16d1df000:
Memory fault at 0x11aad0000 (pc=0x102f13dc4)
The integrity of this image is possibly compromised.
Exiting.
Welcome to LDB, a low-level debugger for the Lisp runtime environment.
(GC in progress, oldspace=0, newspace=7)
ldb>
```

**Comment by cxxxr** [comment]
You probably used more memory than the dynamic-space-size (1GB by default).
I believe this is not a lem problem but a memory management problem with sbcl.
I am sure lispworks, for example, does not have this kind of problem.

**Comment by mattheson** [comment]
You're right, running lem with ```./lem --dynamic-space-size 2048 --control-stack-size 128``` seems to be enough to resolve this issue for me. Thanks for the great project :)
