### ISSUE TITLE
Add alias `legit` to `legit-status`?

### ISSUE THREAD

**Issue by nmccamish** [lem-project/lem#1526]
In Magit, there's a built-in [function alias](https://github.com/magit/magit/blob/0aa26864e3fc4e6949711a4821caf6819e7ab171/lisp/magit-status.el#L292) to `magit-status` called `magit`. Should we add an equivalent alias? It would save on some typing, for instance.

**Comment by vindarel** [comment]
\+1 yes the command is available.
