### ISSUE TITLE
Install on OpenBSD; unable to load ASYNC-PROCESS

### ISSUE THREAD

**Issue by krsanky** [lem-project/lem#1539]
Hi!,

I am trying to install ncurses lem:
gmake ncurses

and get this:

.While evaluating the form starting at line 1, column 0
  of #P"/disk1/home/wise/code/cl/lem/scripts/build-ncurses.lisp":

debugger invoked on a CFFI:LOAD-FOREIGN-LIBRARY-ERROR in thread
#<THREAD "main thread" RUNNING {1001488003}>:
  Unable to load foreign library (ASYNC-PROCESS).
  Error opening shared object "libasyncprocess.so":
  File not found.

I have qlot working with other common-lisp projects. 
I'm guessing it's some kind of building the ASYNC-PROCESS manually and putting the *.so somewhere ?  
Or set some env vars to tell the build where to find them?

I am happy to try things.

**Comment by cxxxr** [comment]
https://github.com/lem-project/async-process/blob/master/bootstrap
We use this.

**Comment by krsanky** [comment]
Thanks!

I am able to build async-process.
I configure'd it with --prefix=~/root  (I do this a lot.)

 ls ~/root/lib/async-process/                                                                                    
libasyncprocess.a  libasyncprocess.la libasyncprocess.so

Where should I put that 
libasyncprocess.so so that the lem install will see it ?

**Comment by cxxxr** [comment]
There are several methods, but I think the following method is the easiest.

```
(cffi:use-foreign-library #p"<directory>/libasyncprocess.so")
```

**Comment by krsanky** [comment]
Yay!

![lem-2024-09-25_20-12](https://github.com/user-attachments/assets/c02b4333-f452-4f25-a648-b0daa66c57f7)

**Comment by krsanky** [comment]
I got it to work in a hack way, but pointing qlot to a local repo of async-process that builds more simply on OpenBSD.
And it hardcodes the location of the *.so file int /tmp/.  So it's not like a general solution, but I can now build and run Lem.

**Comment by rpx99** [comment]
Hi Paul, glad it works. Does `M-x slime` work for you? I copied the lib into the .qlot directory, c.f. [1493](https://github.com/lem-project/lem/issues/1493#issuecomment-2302402100)

**Comment by krsanky** [comment]
No. I have the lib in /tmp/* and that's where I have async-process look for it.  It must load the *.so file at a minimum, because it wasn't compiling when it didn't.
(I just did that to get it to work, not saying that's a solution.)

Just for fun, I should try putting that on a wxallowed partition.

create-process failed: ("sbcl")
Backtrace for: #<SB-THREAD:THREAD "editor" RUNNING {10069580A3}>
0: ((LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE))
1: ((FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX))
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<FUNCTION (FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX) {47DAF60ED4B}>)
3: (UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE) {100564C3DB}> :PACKAGE :CL)
4: (LEM-CORE:POP-UP-BACKTRACE #<SIMPLE-ERROR "create-process failed: ~S" {100564C2A3}>)
5: ((LAMBDA (CONDITION) :IN LEM-CORE:COMMAND-LOOP) #<SIMPLE-ERROR "create-process failed: ~S" {100564C2A3}>)
6: (SB-KERNEL::%SIGNAL #<SIMPLE-ERROR "create-process failed: ~S" {100564C2A3}>)
7: (ERROR "create-process failed: ~S" ("sbcl"))
8: (ASYNC-PROCESS:CREATE-PROCESS ("sbcl") :NONBLOCK NIL :ENCODE NIL :DIRECTORY "/disk1/home/wise/code/cl/lem/")
9: (LEM-PROCESS:RUN-PROCESS ("sbcl") :NAME NIL :OUTPUT-CALLBACK #<FUNCTION (LABELS LEM-LISP-MODE/INTERNAL::OUTPUT-CALLBACK :IN LEM-LISP-M
10: (LEM-LISP-MODE/INTERNAL::RUN-LISP :COMMAND "sbcl" :PORT 65045 :DIRECTORY "/disk1/home/wise/code/cl/lem/")
11: (LEM-LISP-MODE/INTERNAL:RUN-SLIME "sbcl" :DIRECTORY NIL)
12: (LEM-CORE:CALL-COMMAND #<LEM-LISP-MODE/INTERNAL:SLIME {1002CC8033}> NIL)
13: (LEM-CORE:CALL-COMMAND LEM-CORE/COMMANDS/OTHER:EXECUTE-COMMAND NIL)
14: (LEM-CORE::COMMAND-LOOP-BODY)
15: (LEM-CORE:COMMAND-LOOP)
16: (LEM-CORE::TOPLEVEL-COMMAND-LOOP #<FUNCTION (LAMBDA NIL :IN LEM-CORE::RUN-EDITOR-THREAD) {100531139B}>)
17: ((LAMBDA NIL :IN LEM-CORE::RUN-EDITOR-THREAD))
18: ((LAMBDA NIL :IN LEM-CORE::RUN-EDITOR-THREAD))
19: ((FLET BORDEAUX-THREADS-2::RUN-FUNCTION :IN BORDEAUX-THREADS-2::ESTABLISH-DYNAMIC-ENV))
20: ((LABELS BORDEAUX-THREADS-2::%ESTABLISH-DYNAMIC-ENV-WRAPPER :IN BORDEAUX-THREADS-2::ESTABLISH-DYNAMIC-ENV))
21: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
22: ((FLET "WITHOUT-INTERRUPTS-BODY-173" :IN SB-THREAD::RUN))
23: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
24: ((FLET "WITHOUT-INTERRUPTS-BODY-166" :IN SB-THREAD::RUN))
25: (SB-THREAD::RUN)
26: ("foreign function: call_into_lisp_")
27: ("foreign function: funcall1")

**Comment by rpx99** [comment]
Hm, so you are saying it is a permission problem in OpenBSD that is causing the sbcl process creation to fail?

**Comment by krsanky** [comment]
It was a guess.  I don't know.

**Comment by rpx99** [comment]
The Problem is due to O_CLOEXEC used in https://github.com/lem-project/async-process/blob/3b16b91d417530dac03559980fb5703206e20c55/src/async-process.c#L7

O_CLOEXEC is not supported in OpenBSD, c.f.: https://man.openbsd.org/posix_openpt

This fixed it for me (recompile with bootstrap and copy like so `cp static/amd64/OpenBSD/libasyncprocess.so /usr/local/lib`):


```
static const char* open_pty(int *out_fd)
{
  int fd = posix_openpt(O_RDWR | O_NOCTTY);
  if (fd < 0) return NULL;
  if (fcntl(fd, F_SETFD, FD_CLOEXEC) == -1) {
    close(fd);
    return NULL;
  }
  
  if (grantpt(fd) == -1 || unlockpt(fd) == -1) {
    close(fd);
    return NULL;
  }
  //if (grantpt(fd) == -1 || unlockpt(fd) == -1) return NULL;
  //fcntl(fd, F_SETFD, FD_CLOEXEC);
  const char *name = ptsname(fd);
  if (name == NULL) {
    close(fd);
    return NULL;
  }
  *out_fd = fd;
  return name;
}
```
