### ISSUE TITLE
Cyclic dependency with lem-base16-themes

### ISSUE THREAD

**Issue by jgarte** [lem-project/lem#1548]
Hi,

There is a cyclic dependency with [lem-base16-themes]( https://github.com/lem-project/lem-base16-themes).

What do you think if we just include/integrate that code base directly in lem?

**Comment by jgarte** [comment]
If the lem developers are ok with this idea, I can submit a pull request with the changes for it.

**Comment by cxxxr** [comment]
I think it's good.
