### ISSUE TITLE
`rainbow-delimiters` port - integrate into showparen?

### ISSUE THREAD

**Issue by nmccamish** [lem-project/lem#1564]
[rainbow-delimiters](https://github.com/Fanael/rainbow-delimiters) is an Emacs mode that could be potentially easy to port over. `showparen` looks like it could relatively easily integrate said port. We already have `showparen-attribute`, so we would need to expand it to something akin to `rainbow-delimiters-depth-N-face`, though perhaps as a list and not separate attributes for each depth level?

I'd also like to see more integration with themes. Currently I cannot find a theme that sets `showparen-attribute`, even.

**Comment by cxxxr** [comment]
https://github.com/lem-project/lem/blob/main/extensions/lisp-mode/ext/paren-coloring.lisp
There is a feature to make parentheses colorful.

**Comment by nmccamish** [comment]
I missed that! I might actually like it better than rainbow-delimiters!
