### ISSUE TITLE
question: how to configure the dyanimic space size of `lisp repl` while using `roswell` in `lem`.

### ISSUE THREAD

**Issue by sakurawald** [lem-project/lem#1586]
I am using the `sdl2 version of lem`.
I start `lem` via `/home/sakurawald/common-lisp/lem/lem --dynamic-space-size 4Gb`.
I type `M-x slime` to start a `lisp repl`
![image](https://github.com/user-attachments/assets/eef0616c-f37c-4861-a28f-c08a9c4099f7)

However, the `dynamic space size` of this `lisp repl` is the default value `1Gb`.

I also read the manual and try to use `Ctrl u Alt x`, and enter `slime`, but there is no other prompt to ask me input the `rest command arguments`, the `lisp repl` start after I enter:
```
C-u M-x slime <RET>(The `lisp repl` start here, and there is no a prompt to ask me input the args following.) sbcl --dynamic-space-size 4GiB
```

So, the question is: I am using `M-x slime <ret>` to start `lisp repl` in `lem`, my host os is using `roswell`, how can i configure the `--dynamic-space-size` for the `lisp repl` in `lem`.

**Comment by sakurawald** [comment]
By the way, i am using `vi-mode`, it seems that the `key sequence` `C-u` is bind to: 
![image](https://github.com/user-attachments/assets/582dc9f3-8a22-4168-9b5d-2d41c6d74763)

How can i set the `default --dyanmic-space-size` for all `slime` command.

**Comment by sakurawald** [comment]
I seems like the `C-u` key sequence is **consumed by vi-mode**.

**Comment by sakurawald** [comment]
So currently, i have to use `M-x emacs-mode` to use `C-u M-x slime <ret> ros run -- --dyanmic-space-size 4Gb`, and then use `M-x vi-mode` to switch back to vi-mode.

**Comment by sakurawald** [comment]
I found a solution to workaround: `M-4 <ret> M-x <ret> slime <ret> ros run -- --dynamic-space-size 4Gb`.

However, i still want to know how to set the `default dynamic space size`, i want to run `lisp repl` with `M-x <ret> slime <ret>` simply.

**Comment by cxxxr** [comment]
How about defining commands?

```lisp
;; $HOME/.lem/init.lisp or $HOME/.config/lem/init.lisp
(in-package :lem-user)

(define-command slime* () ()
  (lem-lisp-mode:run-slime "ros dynamic-space-size=4GiB run"))
```

**Comment by cxxxr** [comment]
Alternatively, there may be a way to set the default dynamic-space-size in roswell.

**Comment by sakurawald** [comment]
> How about defining commands?
> 
> ```commonlisp
> ;; $HOME/.lem/init.lisp or $HOME/.config/lem/init.lisp
> (in-package :lem-user)
> 
> (define-command slime* () ()
>   (lem-lisp-mode:run-slime "ros dynamic-space-size=4GiB run"))
> ```

The defined new command `slime*` works, thank you!
