### ISSUE TITLE
feature: add new commands to `switch to` or `create` a specific frame-multiplexer.

### ISSUE THREAD

**Issue by sakurawald** [lem-project/lem#1595]
Taken this example, you can see here are 6 frame-multiplexers, which are indexde from 0 to 5.
![image](https://github.com/user-attachments/assets/9af604a2-b32a-450b-81b2-2afa8dcea167)

I would like some new commands like `frame-multiplexer-switch-0`, `frame-multiplexer-switch-1`, `frame-multiplexer-switch-2`, instead of using `frame-multiplexer-next` and `frame-multiplexer-prev` continuously.

These shortcut command will make the switch of frame-multiplexer much easier and smooth.
For example, in `vi-mode`, i can just press `Space 4` to switch to the frame-multiplexer whose index is 4.

**Comment by cxxxr** [comment]
There is a `M-x frame-multiplexer-switch` command.

**Comment by cxxxr** [comment]
OK, I added those commands.
https://github.com/lem-project/lem/pull/1596

**Comment by sakurawald** [comment]
Thank you, now i didn't need to use `prev` and `next` continuously.
I can say that the lem editor makes the learning of common lisp much funny and easier.

**Comment by cxxxr** [comment]
Thanks for the feedback, and please keep it coming
