### ISSUE TITLE
improve the `default prompt value` for `lisp-quickload` command.

### ISSUE THREAD

**Issue by sakurawald** [lem-project/lem#1605]
In source code https://github.com/lem-project/lem/blob/c4fcbf033935b22f6091ce67111047e65d9c00a3/extensions/lisp-mode/lisp-mode.lisp#L766,
the `default prompt value` for `lisp-quickload` command is to `search package definition in current buffer`.

**However, the `asdf manual` suggests that `don't use package-realted lisp forms inside a .asd file`.**

![image](https://github.com/user-attachments/assets/40c1c7c8-1dec-4597-9cce-f25d5f6b4493)
 
Another think is that, since the `.asd` file is used to define **the system border**, and `package-related forms, like (defpackage...) and (in-package...)` is used to define logical structure **inside system border**. So there is no point to use `(defpackage...)` or `(in-package...)` inside a `.asd file`.

The better `default prompt value` for `lisp-quickload` command maybe leaving it `empty`.

**Comment by cxxxr** [comment]
This command assumes that you are using package-inferred-system.
