### ISSUE TITLE
feature: the `ignorecase` option for `isearch`.

### ISSUE THREAD

**Issue by sakurawald** [lem-project/lem#1610]
In [17639f2](https://github.com/lem-project/lem/commit/17639f26c3ed5d7c0f34a85798e79e25829f6478) version, start isearch via the key `/`, and type in the letters.

The search process is case-sensitive.

A typical searching options for vim users may be:
```
set incsearch
set ignorecase
set smartcase
set hisearch
```

**Comment by cxxxr** [comment]
> In [17639f2](https://github.com/lem-project/lem/commit/17639f26c3ed5d7c0f34a85798e79e25829f6478) version

Is the link correct?

**Comment by sakurawald** [comment]
> > In [17639f2](https://github.com/lem-project/lem/commit/17639f26c3ed5d7c0f34a85798e79e25829f6478) version
> 
> Is the link correct?

Yes, i git clone the `lem` repository into my `~/common-lisp/lem`, and git pull the latest commit, `make sdl2` to get the binary file.

The `isearch` function still be `case-sensitive`. It woule be fine to have an option to set the `ignore case` feature.

**Comment by cxxxr** [comment]
I implemented ignorecase.
I am not sure if the result is what I expect as I am not familiar with vim.
Could you please try this PR?

https://github.com/lem-project/lem/pull/1613

**Comment by sakurawald** [comment]
> I implemented ignorecase. I am not sure if the result is what I expect as I am not familiar with vim. Could you please try this PR?
> 
> #1613

It looks good.
The spec for `ignorecase` can be read in https://neovim.io/doc/user/usr_27.html#:~:text=Ignoring%20case,-By%20default%2C%20Vim's&text=If%20you%20want%20to%20ignore,their%20value%20doesn't%20matter.

**Comment by sakurawald** [comment]
After set the config
```
(setf (lem-vi-mode:option-value "ignorecase") t)
```

It's smooth to search a upper-case string without pressing the `shift key`.
