### ISSUE TITLE
feature: add the missing binding for `~` character in `vi-mode`.

### ISSUE THREAD

**Issue by sakurawald** [lem-project/lem#1621]
In `vim edtiro`, the `~` character is bind to `swapcase and forward next character`.

In `lem editor`, there is a command named `lem-vi-mode/binds::vi-swapcase`, however, this command requires a motion action, which doesn't fit the need.

There should be a new command to do something like `swap-case on cursor, and forward character`.

And add the missing binding:
```
(define-key lem-vi-mode:*normal-keymap* "~" '<the new command name>)
```

**Comment by cxxxr** [comment]
If you like, please make a PR.
