### ISSUE TITLE
improve: the `vi"` and `va"` in `vi-mode` will freeze the lem editor inside an escaped string.

### ISSUE THREAD

**Issue by sakurawald** [lem-project/lem#1657]
To-reproduce:
1. Input `"\"` string.
2. Type `viw` or `vaw` in `vi-mode`
3. The lem editor stucked.

![image](https://github.com/user-attachments/assets/f9b10479-af3a-49c2-8f58-495fd297a482)

**Comment by sakurawald** [comment]
The `vi(` result, it seems like the `escaped close character` is ignored.

![image](https://github.com/user-attachments/assets/1483298d-4c2e-49fa-b9b6-c50351db9d6e)

**Comment by LeeLaffan** [comment]
I can reproduce this issue too. viw/vaw doesn't freeze it for me, but vi" and va" do cause the freeze. Need to restart Lem then.

**Comment by LeeLaffan** [comment]
This is fixed now :)
