### ISSUE TITLE
一部の端末でBackSpaceキーを押すとDeleteの挙動をする

### ISSUE THREAD

**Issue by kuuote** [lem-project/lem#176]
# 実行環境
Linux上のKonsoleで 9c65f8f を
`ros roswell/lem-ncurses.ros`で実行して確認しています。

# 原因
問題の環境ではBackSpaceを押すとエスケープシーケンス`^H(0x08)`ではなく`^?(0x7F)`を送出する。
これがlem内部でDelete扱いされるため発生。

```diff
diff --git a/lem-frontend-ncurses/ncurses.lisp b/lem-frontend-ncurses/ncurses.lisp
index 49a3c900..0941ff3c 100644
--- a/lem-frontend-ncurses/ncurses.lisp
+++ b/lem-frontend-ncurses/ncurses.lisp
@@ -60,7 +60,7 @@
 (defkeycode "C-^" 30 (make-key :ctrl t :sym "^"))
 (defkeycode "C-_" 31 (make-key :ctrl t :sym "_"))
 (defkeycode "Spc" #x20 (make-key :sym " "))
-(defkeycode "[del]" #x7F (make-key :sym "Delete"))
+(defkeycode "[backspace]" #x7F (make-key :sym "Backspace"))
 
 (loop :for code :from #x21 :below #x7F
       :do (let ((string (string (code-char code))))
```

これで直ります。

# 質問
[Wikipediaの削除文字の項](https://ja.wikipedia.org/wiki/%E5%89%8A%E9%99%A4%E6%96%87%E5%AD%97)にはこのエスケープシーケンスはUNIX系OSではBackSpaceに使われていると書いてあったのと、Emacs内で実際にBackSpaceに使われていたため、このパッチを書きましたが、問題ないでしょうか。

**Comment by cxxxr** [comment]
ありがとうございます。
問題無いようなのでこの変更でコミットしました。
