### ISSUE TITLE
[vi-mode] `:buffer` command to switch to another buffer

### ISSUE THREAD

**Issue by utatatata** [lem-project/lem#319]
There are some abbreviations as `:b`, `:bu` and `:buf` in Vim.

**Comment by fukamachi** [comment]
Is it okay to be same as `C-x C-b`?

**Comment by utatatata** [comment]
Yes, it's same as switch-to-buffer in emacs.

**Comment by fukamachi** [comment]
I’d like to fix the requirements which you need.
Check out C-x b on lem and it’s still what you expect since lem provides
the feature in a different way from Emacs’s.
2018年9月3日(月) 8:51 Takuma Uda <notifications@github.com>:

**Comment by fukamachi** [comment]
Added by #898.
