### ISSUE TITLE
Hints/Tutorial on writing custom modes ?

### ISSUE THREAD

**Issue by the-drunk-coder** [lem-project/lem#364]
So, i was thinking of writing a custom mode for lem, but i don't really find any info on how to do it. Basically, it'd be just a derivative of the lisp mode with a few modifications:

* evaluate a block of code on `C-Return` instead of `C-M-x` (i tried replacing this in the keymap, but it doesn't work)
* use paredit automatically
* start mode when loading a file with a specific extension
* run some bootstrap code when starting the mode

I don't really know where to start right now, just poking around the code, but maybe somebody can give me a hint where to start ? I'd be really grateful ...

**Comment by cxxxr** [comment]
`C-Return` can not be used at terminal. but it can use `M-Return` instead.

Please refer to lem/modes/ for how to define major-mode.
https://github.com/cxxxr/lem/blob/master/modes/python-mode/python-mode.lisp
https://github.com/cxxxr/lem/blob/master/modes/diff-mode/diff-mode.lisp


> * start mode when loading a file with a specific extension

Please change `*auto-mode-alist*`


> * use paredit automatically
> * run some bootstrap code when starting the mode

Please write it in the body of `define-major-mode`.

I want to prepare a document, but I can't possibly manage it yet.

**Comment by the-drunk-coder** [comment]
No problem, i'm willing to do some trial and error ...

So, i got the basic mode part and the starting done. 

But when i try to load my bootstrap code file, i get a `Heap exhasted` type error ? When i load the file from a lisp buffer, it works fine ... 

Also, what's the function to enable a minor mode called ? `(toggle-minor-mode 'paredit-mode)` doesn't really do anything in the body of `define-major-mode`.

**Comment by cxxxr** [comment]
It may be a problem of lem that "Heap exhasted" comes out.
It may be resolved if it can be reproduced.

Please evaluate `(mode-name)` to enable mode (e.g. `(foo-mode)`)

To enable syntax highlighting, you need to write `(setf (variable-value 'enable-syntax-highlight) t)` in the body.

https://github.com/cxxxr/lem/blob/b4b7732ff016cf8eab782e2f3f880d92e3f2d8b7/modes/python-mode/python-mode.lisp#L79
