### ISSUE TITLE
[Windows] windows support for lem?

### ISSUE THREAD

**Issue by SerialDev** [lem-project/lem#371]
I wanted to request windows support leveraging the ros ecosystem if possible. 
This  would make the barrier of entry to lisp for windows users basically non-existent.
Any suggestions on how I could proceed on this would also be appreciated.
Thanks!

**Comment by cxxxr** [comment]
I think need a sufficient GUI front end to support Windows.
I recently found a project called https://github.com/acheronfail/xi-electron, so I would like to refer to it.

**Comment by SerialDev** [comment]
I noticed a frontend attempt using CAPI in the codebase, would this be a suitable cross platform option?

**Comment by cxxxr** [comment]
It may be good, but there is a problem in that you can not use CAPI without purchasing lispworks.

**Comment by pupcraft** [comment]
[lem-opengl](https://github.com/pupcraft/lem-opengl) works on windows, it uses GLFW, but it's alpha quality

**Comment by Hamayama** [comment]
Hello. I made a wiki page.
https://github.com/cxxxr/lem/wiki/Windows-Platform

**Comment by Sasanidas** [comment]
I'll close this issue, as now Lem does support windows https://lem-project.github.io/installation/ncurses/windows/
