### ISSUE TITLE
Add C-h b do call describe-bindings and C-h k to call describe-key

### ISSUE THREAD

**Issue by svetlyak40wt** [lem-project/lem#407]
I know there is a `C-x ?` bound to `describe-key`, but mappings mentioned in the title are default in Gnu Emacs, and I think those who come from it will be happy to find these ways to learn about Lem's commands.

It would be nice to have describe-mode bound to `C-h m` as well, but I don't see such interactive command now.

**Comment by snmsts** [comment]
It might come from my custom of using ``C-h`` as ``delete-previous-char``...
I would prefer keys which start multi stroke command should be lessen than Emacs default.
How about sacrifice ``C-x ?`` instead of ``C-h`` so ``C-x ? b`` for bindings ``C-x ? k`` for key. m for mode.

**Comment by svetlyak40wt** [comment]
This will be ok if we let people know about these important commands with making an onboarding by providing a tips:

https://github.com/cxxxr/lem/issues/410

**Comment by snmsts** [comment]
with approval from @cxxxr I'll do...

**Comment by svetlyak40wt** [comment]
Let me make this change in my pull:

https://github.com/cxxxr/lem/pull/408

**Comment by cxxxr** [comment]
At lem, I would like to achieve this in a different way to emacs.
