### ISSUE TITLE
Operator, text object and vim-surround

### ISSUE THREAD

**Issue by kenoss** [lem-project/lem#425]
c.f. https://github.com/cxxxr/lem/issues/424

I think we need more general framework for vi-mode.  Current design lacks extensibility for, e.g. text object plugins and additional action like https://github.com/tpope/vim-surround.

I'm considering to introduce concepts "operator" and "text object", using something like `define-text-object-command` and feature that handle "continuous command" like `continue-flag`.

**Comment by kenoss** [comment]
link https://github.com/cxxxr/lem/issues/278

**Comment by fukamachi** [comment]
ref #1012

**Comment by fukamachi** [comment]
Operator-pending state, and text objects are introduced by #1012 and #1013.
