### ISSUE TITLE
Conform to XDG Base Directory Specification

### ISSUE THREAD

**Issue by kenoss** [lem-project/lem#434]
https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html
https://qiita.com/lighttiger2505/items/440c32e40082dc310c1e#nvim-configuration

I prefer that lem forces users to place config files into `$XDG_CONFIG_HOME/lem`.

**Comment by kenoss** [comment]
I mean "not selectable".  Config dir should be `$XDG_CONFIG_HOME/lem`, not `$XDG_CONFIG_HOME/lem` "and" `$HOME/.lem`.

**Comment by appetrosyan** [comment]
I second this.
