### ISSUE TITLE
Please join GitHub Sponsors!

### ISSUE THREAD

**Issue by Hexstream** [lem-project/lem#491]
Congratulations for creating such a relevant and successful project!
(I really wish I had time to try it out, but I'm too busy...)
(And I see you have other good Common Lisp projects, too...)

I realize you're already making some money [on Open Collective](https://opencollective.com/lem), but I've found that [GitHub Sponsors](https://github.com/sponsors) is simply the best platform for Common Lisp Open Source funding. (I'm still pretty obscure and I'm already making 600$/month!)

I realize this project has multiple contributors, but [you are still overwhelmingly the primary contributor](https://github.com/cxxxr/lem/graphs/contributors), so I'm sure people will be eager to support you directly.

Note that 92% of [Common Lispers list](https://common-lispers.hexstreamsoft.com/) members are already on GitHub, so most of your potential funders are already on GitHub!

Please join [GitHub Sponsors](https://github.com/sponsors) as soon as possible!

**Comment by snunez1** [comment]
Interesting idea. Is there a way to sponsor specific issues with GitHub Sponsors? I didn't see one. BountySource did this, but I see they've fallen out of favour lately. Being able to sponsor specific issues also serves as a voting system of sorts for what the community thinks is important.

**Comment by Hexstream** [comment]
GitHub Sponsors does not natively support such a mechanism.

That said, one might generally expect that the beneficiary may be motivated to be extra responsive to the wishes of their major sponsors, in part out of gratitude and perhaps in the hopes of helping motivate them to sustain and/or increase their sponsorship over time.

Some people explicitly list increased responsiveness to issues as benefits in their perks, while others explicitly disclaim such. Some people severely limit their tiers in part to reduce expectations of paid influence, which is probably a pretty bad idea if you're not extremely popular and want to make a lot of money. ([My current approach](https://github.com/sponsors/Hexstream) is "unlimited" tiers with no explicit guarantees of service, but I definitely take good care of my major sponsors. ;))

**Comment by garlic0x1** [comment]
Sponsoring cxxxr is now the way to get access to lem-cloud

**Comment by Hexstream** [comment]
Thank you, I already made [a token donation](https://sponsors.hexstreamsoft.com/log/paying-the-love-forward/#ch_3P9I5EEQsq43iHhX0bkm5OBp) a while ago. :)
