### ISSUE TITLE
Lem on Nyxt?

### ISSUE THREAD

**Issue by jmercouris** [lem-project/lem#543]
What would it take to port Lem to work on Nyxt? Was it hard to port to electron? Do we need to support some sort of ncurses emulation layer?

**Comment by aartaka** [comment]
> What would it take to port Lem to work on Nyxt? Was it hard to port to electron? Do we need to support some sort of ncurses emulation layer?

Oh hi @jmercouris :D 

Looking at the Lem code, it seems that we only need to properly implement some thirty five methods from https://github.com/lem-project/lem/blob/master/lib/core/interface.lisp and use `interface` mixin from the same file.

It could well be integratable with Nyxt's `editor-mode`. The only problem I can think of is keyboard handling, but that can be hacked too :)

However, I was unable to build Roswell and, consequently, Lem, so I cannot experiment with it xD

**Comment by jmercouris** [comment]
Hm doesn't seem too hard indeed. Could be very doable.

**Comment by pdelfino** [comment]
A user said the following in a private conversation after being prompted: _Also, if you were a developer of Nyxt (beyond just a user) what would you like to build for yourself?_

> Integrating the LEM editor and giving it BIDI and opentype abilities.

**Comment by Sasanidas** [comment]
I'll close this issue as seems more like a conversation. Feel free to open it again if that's not the case :+1:
