### ISSUE TITLE
Please, no electron

### ISSUE THREAD

**Issue by 173duprot** [lem-project/lem#551]
This project conforms to K1SS and Unix philosophy principles, why ever have *electron* as a frontend?!

**Comment by BlueFlo0d** [comment]
Sorry Electron sucks but uNiX sucks more [Unix and C are the ultimate computer viruses.](https://www.dreamsongs.com/RiseOfWorseIsBetter.html) 

Please replace Electron and UNIX spinoff and copycats support with Lisp Machine supports and CLOSOS port.

**Comment by acgollapalli** [comment]
I agree with BlueFlo0d.

Building a CLOSOS may need to become a subproject of this project so the editor has a proper environment to run in. I would also recommend a separate hardware project so that CLOSOS has something to run on.
