### ISSUE TITLE
"Redo Error"

### ISSUE THREAD

**Issue by jgc37** [lem-project/lem#553]
Whenever I try to to undo something with the key binding "C-/" I get "Redo Error"

Anyone know what causes this? 

Haven't seen anyone else with this issue

**Comment by cxxxr** [comment]
Sorry for my late reply.

The standard undo key binding for lem is "C-x \"
The key binding for redo is "C-x /"

**Comment by cxxxr** [comment]
Key bindings can be listed with `M-x describe-bindings`
