### ISSUE TITLE
cant open files

### ISSUE THREAD

**Issue by hunar1997** [lem-project/lem#554]
When i C-x C-f a file it shows this

```
:UTF-8 c-string decoding error: the octet sequence #(194 253) cannot be decoded
Backtrace for: #<SB-THREAD:THREAD "editor" RUNNING {1002E27863}>
0: ((LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE))
1: ((FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX))
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<FUNCTION (FLET "THUNK" :IN UIOP/STREAM:
3: (UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:
4: (LEM:POP-UP-BACKTRACE #<SB-INT:C-STRING-DECODING-ERROR {10043A78C3}>)
5: ((FLET "H0" :IN LEM::COMMAND-LOOP) #<SB-INT:C-STRING-DECODING-ERROR {10043A7
_____________________________________ Top _____________________________________
```
What should i do
EDIT: I just tried `lem-ncurses-ccl` it doesn't have this problem

**Comment by cxxxr** [comment]
Can you open that file with sbcl by itself?

for example
```common-lisp
(with-open-file (in "file name")
  (loop :while (read-line in nil nil)))
```

**Comment by hunar1997** [comment]
I can, i tried both my system sbcl and roswell's sbcl 

but it's not only that file, every file (existing or not) has this problem

Wait, i tried it using a live-usb of my distro (manjaro) and it doesn't have this problem .. what does that error mean? how can i solve it :(

**Comment by cxxxr** [comment]
Looking at the 14th line of the stack trace, it seems that you are looking at the file list of the target directory. 
Does the `/user/hunar/` directory contain a filename that is not utf-8?

**Comment by hunar1997** [comment]
Ooooo that's weird, it doesn't have this problem if the file was in `/tmp` or `/home` it looks like when the path contains `hunar` then it has this problem. But they are all ASCII characters, i don't understand :/

**Comment by hunar1997** [comment]
Solved :D 
There was a file that wasn't shown using `ls` but the file explorer showed it as `P▯▯▯` i deleted it and everything works now :|  i cant reproduce the problem anymore, since i don't know where to get non-utf-8 characters
Thanks :D

**Comment by cxxxr** [comment]
I'm glad I solved it!
