### ISSUE TITLE
Get an error about libasyncprocess.so not existing

### ISSUE THREAD

**Issue by Elentirith** [lem-project/lem#560]
Trying to install on sbcl 2.1.9 on an arm32 board, I get this error. Is this related to being on arm not x86?

(CFFI::FL-ERROR "Unable to load foreign library (~A).~%  ~A" ASYNC-PROCESS "Error opening shared object \"libasyncprocess.so\":
  libasyncprocess.so: cannot open shared object file: No such file or directory.")

**Comment by cxxxr** [comment]
Thank you for your report.
I am aware that arm32 does not currently work.
The only problem is that I don't have enough resources and would like to get help from others (and you).

**Comment by cxxxr** [comment]
Thanks for the report.
Currently, there are probably other things besides async-process that arm32 does not support (e.g. thread support).
But since there seems to be a demand for it, I'd like to solve it if I can.

**Comment by avysk** [comment]
```
❯ ros install lem-project/lem cxxxr/cl-lsp
[blah]
Unhandled CFFI:LOAD-FOREIGN-LIBRARY-ERROR:
  Unable to load foreign library (ASYNC-PROCESS).
  Error opening shared object "libasyncprocess.so"
[blah]
❯ uname -msrv
FreeBSD 13.1-RELEASE-p6 FreeBSD 13.1-RELEASE-p6 GENERIC amd64
❯ ros --version
roswell 22.12.14.113(NO-GIT-REVISION)
❯ .roswell/impls/x86-64/freebsd/sbcl/2.3.1/bin/sbcl --version
SBCL 2.3.1
```

This is not arm32, and the installation fails because of `libasyncprocess.so` too.

**Comment by rpx99** [comment]
I found this [instructions](https://github-wiki-see.page/m/lem-project/lem/wiki/FreeBSD-Platform):

The part that solved it for me was to do this in my $HOME/common-lisp folder:

> git clone https://github.com/lem-project/async-process.git
> cd async-process/
> sudo pkg install libtool gmake autotools
> sh bootstrap
> sudo cp .libs/libasyncprocess.so /usr/lib/
