### ISSUE TITLE
Improper resizing of Electron window with tiling window manager

### ISSUE THREAD

**Issue by kjinho** [lem-project/lem#572]
When I load lem-electron while using a tiling window manager, the lem-electron window will constantly attempt to resize itself. I suspect that the problem arises from lem-electron being unable to display fractional columns or rows (and not having margins when the chosen window size does not correspond to an exact column/row size).

The constant resizing results in flashing visual artifacts that make the electron frontend unusable, unless I disable the tiling window manager.

lem using ncurses in a terminal does not suffer from the same issue.

**Comment by Sasanidas** [comment]
https://github.com/lem-project/lem/issues/539#issuecomment-1845538388
