### ISSUE TITLE
GUI frontend

### ISSUE THREAD

**Issue by cxxxr** [lem-project/lem#582]
goal
- That I can use on a daily basis.
- electron frontend or something else

**Comment by lambdart** [comment]
How about and SDL2 frontend?

**Comment by appetrosyan** [comment]
I could try snd create a Qt frontend if people don't mind the Qt.

**Comment by alphapapa** [comment]
Has any consideration been given to using McCLIM for a frontend?

**Comment by appetrosyan** [comment]
> Has any consideration been given to using McCLIM for a frontend?

That looks promising. It seems like making it look good is going to be a challenge, though.
