### ISSUE TITLE
Need to re-defined UNDO key on German keyboard

### ISSUE THREAD

**Issue by gnusupport** [lem-project/lem#593]
Please help me, how do I redefine `undo´ as I want it to be `C--´ ? 

I have tried following in `~/.lem/init.lisp` 

```
(defpackage #:lem-my-init
  (:use #:cl
        #:lem))
(in-package :lem-my-init)

(define-key *global-keymap* "C--" 'lem:undo)
```

**Comment by cxxxr** [comment]
As far as I have tried in my environment, `C--` seems to be entered as `C-_` in the terminal.

**Comment by gnusupport** [comment]
```
(define-key *global-keymap* "C-_" 'lem:undo)
```

that made `C-shift- -` work as undo, but not `Control and -`. Is there solution?

**Comment by cxxxr** [comment]
I think it is not possible due to the constraints of the terminal.
How about assigning it to another keybind?

**Comment by Sasanidas** [comment]
How's the status of the issue? Did assigning other keybind worked? (ping @gnusupport )

**Comment by cxxxr** [comment]
Perhaps the use of SDL2 frontend could work around this problem.
