### ISSUE TITLE
Unable to Launch Post-installation

### ISSUE THREAD

**Issue by hjozwiak** [lem-project/lem#594]
Hello,

When trying to launch lem for the first time, I get the following: "unknown frontend: ncurses".
# System Particulars
- Arch Linux
- ncurses 6.3
- - roswell 21.10.14.111

**Comment by jedth** [comment]
Hey I ran into the same issue but noticed that I had forgotten to add `~/.roswell/bin` to my path.
After that everything worked. 
Hope this helps.

**Comment by hjozwiak** [comment]
That did the trick.
