### ISSUE TITLE
The variable LEM::*IMPLEMENTATION* is unbound.

### ISSUE THREAD

**Issue by theangelperalta** [lem-project/lem#604]
![image](https://user-images.githubusercontent.com/12777745/217390356-f53e07dc-0ad9-4438-9719-f64eeea2339b.png)
It seems like the variable *IMPLEMENTATION* is unbounded when attempting to connect swank.

**Comment by cxxxr** [comment]
What steps does this error occur?

**Comment by theangelperalta** [comment]
> What steps does this error occur?

I'm using the steps from the [Wiki](https://github.com/lem-project/lem/wiki/How-to-hack-on-lem-itself). I'm attempting to start the swank server from the built-in repl: `(swank:create-server :dont-close t)`

**Comment by cxxxr** [comment]
Thank you, I have reproduced it.
I would like to fix this.

What about setting up a server at editor startup as a workaround?
for example
```
$ ros -s swank -e '(swank:create-server :dont-close t)' -s lem-ncurses -e '(lem:lem)'
```

**Comment by theangelperalta** [comment]
@cxxxr Thank you for the quick response.

**Comment by cxxxr** [comment]
The reason for the problem is that special variables are thread-local.
It was intended, but not good in terms of convenience, so it has been corrected.
28be6a550b5228ee5b34bee0a15e9181837abc83

**Comment by cxxxr** [comment]
Hmmm, doesn't seem to be fixed.
