### ISSUE TITLE
follow-dependency=t' is not a valid target for 'install' 

### ISSUE THREAD

**Issue by rajcspsg** [lem-project/lem#605]
Hi,

I'm trying to install lem editor on fedora 38 linux.

I installed roswell. Then I'm following readme to install lem-editor but I get below error.

```
$ ros install follow-dependency=t lem-project/lem
'follow-dependency=t' is not a valid target for 'install' -- It should be a name of either:
+ a quicklisp-installable system
+ a common lisp installation 
```

What is wrong in the steps I'm doing how can I fix this issue?

**Comment by cxxxr** [comment]
I'm sorry, maybe the command in README.md was wrong

What about the following command?
```
ros follow-dependency=t install lem-project/lem
```
