### ISSUE TITLE
** Workaround for cases where lem cannot be installed **

### ISSUE THREAD

**Issue by cxxxr** [lem-project/lem#628]
Here is a summary of the most common errors that occur these days.
I hope this will work for you.
If this does not solve the problem, we would very much appreciate feedback :pray:

## case 1
If the error message contains the following string
```
compiling #<CL-SOURCE-FILE "log4cl" "src" "naming-sbcl">
```

Currently cannot build with the latest version of sbcl and log4cl.

Solution 1:
Lower the version of sbcl.
If you are using roswell, you can install it by specifying the version with the following command.
```
ros install sbcl-bin/2.3.2
```

Solution 2:
Install log4cl master
You can also solve this problem by cloning log4cl into $HOME/.roswell/local-projects/ (or $HOME/common-lisp).
```
$ git clone https://github.com/sharplispers/log4cl.git $HOME/.roswell/local-projects/sharplispers/log4cl
```

## case 2
If the error message contains the following string
```
System "lem-base16-themes" not found
```

Perhaps it's because you didn't clone it, including the git submodule.

If you are using roswell
```
cd $(ros -e '(princ (ql:where-is-system :lem))')
git submodule update --init --recursive
```

If you are using sbcl
```
cd $(sbcl --eval '(princ (ql:where-is-system :lem))')
git submodule update --init --recursive
```

**Comment by RadSpaceEd** [comment]
What about: 
```
Unhandled QUICKLISP-CLIENT:SYSTEM-NOT-FOUND in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                         {1000518083}>:
  System "micros" not found
```
I only dealt with elisp inside Emacs... so I'm still pretty new.

**Comment by cxxxr** [comment]
@RadSpaceEd

Oh, Thank you for the report.

This is due to the recent addition of a submodule.
Maybe the same method as case-2 can solve this problem.

**Comment by RadSpaceEd** [comment]
@cxxxr It worked! This should be mentioned on the readme...
I also had to run `ros follow-dependency=t install lem-project/lem` again after cloning the submodules.

**Comment by cxxxr** [comment]
@RadSpaceEd 
I'm glad it worked!
I've added an explanation to readme.md, thank you.

**Comment by techapu** [comment]
I have lem 1.9.2 installed with roswell. I love CL but I am not an expert. It seems I need to remove lem to install 2.0. When I run "ros update lem" or "ros update lem-proyect/lem" doesn't work. Even when I clone it in the dir and with submodules as adviced. What is the cleanest way to remove a previous ros installed lem? By the way, I am in debían 11 in a desktop PC, my sbcl is 2.2.1.

**Comment by androclus** [comment]
I have same problem as techapu.

**Comment by techapu** [comment]
> I have lem 1.9.2 installed with roswell. I love CL but I am not an expert. It seems I need to remove lem to install 2.0. When I run "ros update lem" or "ros update lem-proyect/lem" doesn't work: my lem is still 1.9.2. Even when I clone it in the dir and with submodules as adviced. What is the cleanest way to remove a previous ros installed lem? By the way, I am in debían 11 in a desktop PC, my sbcl is 2.2.1. Maybe I need to update sbcl?

Finally working Lem 2.1! It is a fantastic software. Thanks. I'm Sorry that I couldn't upload the logs for reporting, I barely had time these weeks. 
I noticed I had a working lem 1.9 installed time ago with "ros install cxxxr/lem" and I wonder if there was a conflict with the lem-project/lem repository, because the binaries in "~/.roswell/bin" were there when roswell tried to compile.
Whatever, I removed all the folders and files related with lem, updated my roswell sbcl installation to 2.3.6, cloned the log4cl as it says in "Case 1" suggestion. 
Then checked the dependencies needed for sdl2, and installed one more that I didn't had in my system. 
Then I used "ros follow-dependency=t install lem-project/lem". And it was all. 
Now it works

**Comment by rsm-lisper** [comment]
> @RadSpaceEd
> 
> Oh, Thank you for the report.
> 
> This is due to the recent addition of a submodule. Maybe the same method as case-2 can solve this problem.

I also had problem with missing "micros", case-2 method solved it, but only on git cloned repository. Any idea how to build lem from release tar sources? If not - maybe it would be good idea to not attach release source tar files, because they are unusable :/

**Comment by 5thWall** [comment]
I'm installing using roswell and also have the problem with missing "micros", however case-2 method did not solve it for me. Submodules don't appear to be used in the project anymore?

**Comment by cxxxr** [comment]
I think this issue was solved by using qlot.

**Comment by daninus14** [comment]
> I think this issue was solved by using qlot.

@cxxxr How? Can you please explain? I just tried `ros follow-dependency=t install lem-project/micros` and it failed for me.

**Comment by cxxxr** [comment]
@daninus14 
Now it is no longer necessary to install micros explicitly.
Please follow the readme instructions to install

**Comment by daninus14** [comment]
@cxxxr Thanks, I got confused between the readme and the website, I wrongly assumed they were the same... https://lem-project.github.io/lem-page/installation/getting-started/#installation-with-roswell has different instructions than the readme in the project
