### ISSUE TITLE
How to Fix “App Is Damaged and Can’t Be Opened” on OSX

### ISSUE THREAD

**Issue by cianoc** [lem-project/lem#635]
In case anyone else was banging their head against the wall because of incredibly annoying OSX security settings/error messages.

Copy the app file to the applications folder.

Type the following in your terminal:

`xattr -d com.apple.quarantine /Applications/lem.app`

Run it normally and it should be fine.

I think this is because the app isn't signed.

**Comment by cianoc** [comment]
It might be worth adding this somewhere, so that other apple users can experience the joy of LEM.

**Comment by JikanBae** [comment]
Thank you for the tip! I just had the same issue on MacOS Ventura 13.4 last night and almost giving up using Lem GUI.

**Comment by Sasanidas** [comment]
I added this comment on the Lem webpage (https://lem-project.github.io/installation/ncurses/macos/#using-the-binary), so I'll close this issue :+1:
