### ISSUE TITLE
Project information

### ISSUE THREAD

**Issue by Sasanidas** [lem-project/lem#640]
Helllo,
(My intention was to send an e-mail, but I couldn't found it, sorry)

I'm really curious about this project, I knew about it existence a couple of years ago but never realize the potential that it have, and the thing is that is already really good!.

I would love to contribute, I have some experience with some projects ( [CEDAR](https://gitlab.com/sasanidas/cedar), a similar project to Lem, but with the intention to be more close to the GNU Emacs API and [UnCommon](https://gitlab.com/shookakko/uncommon), a still work in progress Common Lisp IDE that is usable, but it still needs some hours to be usable).

In any case, I think Lem it's more mature and in general way more polish, so my intention is to contribute both in the original code base and (I hope) with extensions.

But first, I do have a couple of questions:

- Is the Lem API looking to be really similar to the one in GNU Emacs? or just inspired?
- Is Lem open to have a webpage similar to StumpWM or other editor project? (basically if documentation in English is needed)
- How is the project going forward? Seems like a one man effort, but maybe there are other key people involve (this is also interesting to know who I may ask)

I also checked that there were an issue regarding the Guix packaging, I'm not sure how it's going, but that can be really interesting.

In general, thanks a lot for the effort of the package, it looks and feel incredible!

(I'm starting to playing with the API and adding trying some stuff [here](https://gitlab.com/sasanidas/lem-config/-/blob/master/init.lisp))

Regards

**Comment by cxxxr** [comment]
Hello!

Thank you for showing interest in this project.
The messages from individuals who approach with enthusiasm demonstrate that my efforts are being appreciated and encourage me to continue with the project.

I have seen CEDAR and UnCommon, they are indeed wonderful!

> Is the Lem API looking to be really similar to the one in GNU Emacs? or just inspired?

The latter. While I refer to the API to a certain extent, but I don't intend to make it compatible.
Moreover, I have been strongly inspired by the APIs of Hemlock and the LispWorks editor.

> Is Lem open to have a webpage similar to StumpWM or other editor project? (basically if documentation in English is needed)

Yes! I would like to have something ready if possible, but there is still much to be done.

> How is the project going forward? Seems like a one man effort, but maybe there are other key people involve (this is also interesting to know who I may ask)

There are reliable contributors who use it daily.
There are also people who can give technical support.
And, there are people who create Pull Requests.

I have no knowledge of Guix, but if there's a way to improve it, that would be delightful.

I'd appreciate your help.

**Comment by Sasanidas** [comment]
Thanks for the quick response

>The latter. While I refer to the API to a certain extent, but I don't intend to make it compatible.
Moreover, I have been strongly inspired by the APIs of Hemlock and the LispWorks editor.

I see, I'm not that familiar with the API of Hemlock or LispWorks, but it seems Emacsy enough for me :100: 

>Yes! I would like to have something ready if possible, but there is still much to be done.

Totally understandable :+1: 

>I'd appreciate your help.

I'll try it to use it daily for CL and to improve my configuration ,learning the editor along the way, when I have more experience I hope to submit some requests.

Again, thansk for the information and for this amazing software
