### ISSUE TITLE
SDL2 highline line full white

### ISSUE THREAD

**Issue by Sasanidas** [lem-project/lem#667]
When using the SDL2 version of Lem I got this white line where the cursor is:

![Lem_001](https://github.com/lem-project/lem/assets/26670956/25d95f35-1459-43e7-982d-e890b5db25da)

**Comment by cxxxr** [comment]
Thank you for your report.

I do not know why white, but this process itself is done [here](https://github.com/lem-project/lem/blob/main/src/display.lisp#L114)
What is the value of background-color?

**Comment by cxxxr** [comment]
As a workaround, set highlight-line to nil and it will not be displayed.
```
(setf (lem:variable-value 'lem:highlight-line :global t) nil)
```

**Comment by Sasanidas** [comment]
Ooh!! I see, I tried to change the value that way but without global wasn't working

**Comment by Sasanidas** [comment]
Seems like it's working now, thanks :+1:

**Comment by cxxxr** [comment]
White color may be unintentional behavior
