### ISSUE TITLE
Run Lem with other Common Lisp implementations

### ISSUE THREAD

**Issue by Sasanidas** [lem-project/lem#680]
I know that SBCL is THE implementation of Common Lisp, still, I think there are others interesting out there that can bring some interesting things, like [ABCL](https://github.com/armedbear/abcl/) or [CLASP](https://github.com/clasp-developers/clasp) both actively maintained.

**Comment by Sasanidas** [comment]
Maybe as a first steep, make sure that if we have to use SBCL specific features, use the conditional macro to log a warning or make that command unavailable. (ping @cxxxr )

**Comment by jcs090218** [comment]
Hi, common lisp newbie here. I wonder what's the differences between these implementations. This is a great way to start off discussing different tools. 🤔 Thanks!

**Comment by Sasanidas** [comment]
> I wonder what's the differences between these implementations

Well, each implementation usually it's implemented with the platform itself in mind, for example, in the case of ABCL, it makes interoperability with Java very easy or [ECL](https://ecl.common-lisp.dev/static/manual/System-building.html#Shared-library) compatible with plain C.

In the case of CLASP, it's Common Lisp in the LLVM which itself is really interesting, so I think that even tho the main one should be SBCL (it's the fastest and more maintained by far), others implementations can give lem the ability to better adapt to someone's needs (maybe I need better Java interaction, or having a native Java profiler).

Also, in general, if it's possible writing portable ANSI Common Lisp is always nice, specially if in the future SBCL (god forbids) disappears, this projects doesn't go with it.

That's one of the strengths of Common Lisp, and why some libraries from late 90s are still possible to use/port. :smile:

**Comment by jcs090218** [comment]
Ah, now I understand it! Thank you for your explanation! 🙏

**Comment by cxxxr** [comment]
Yes, indeed.
It might be better to make it work with other promising implementations besides SBCL as well.

**Comment by cxxxr** [comment]
Yes, indeed.
it might be better to make it usable with promising implementations other than SBCL.

The reason it's not like that right now is simply because it's easier to write by depending solely on SBCL.

**Comment by Sasanidas** [comment]
So, I manage to compile ABCL with the ncurses fronted (albeit, commenting some extension code, mainly the swank code).

But I realize that the code is in general quite portable, I should be quite easy to make it work with others implementations (at least with the ncurses front-end) :+1:

**Comment by cxxxr** [comment]
I'm surprised that abcl is working.
If Java assets can be used, it's possible to use the GUI as well, so creating a frontend using that might be a good idea.

**Comment by snmsts** [comment]
Portability problem depending on sbcl is it wouldn't work with platform which sbcl can't have :sb-thread feature. I don't know is it comfortable to run lem with abcl on linux 32bit raspberrypi or not...

**Comment by Sasanidas** [comment]
> I'm surprised that abcl is working.

I mean, I manage to make it compile and "run", but it breaks constantly, was just a first try if it was possible or not. Making work as good as with SBCL is probably way more difficult :+1:

**Comment by Sasanidas** [comment]
> Portability problem depending on sbcl is it wouldn't work with platform which sbcl can't have :sb-thread feature. I don't know is it comfortable to run lem with abcl on linux 32bit raspberrypi or not...


Ummm, I mean, I'm not saying to have ABCL as a first class citizen (or other implementation), it's just that if we can manage to make the code portable (what I mean is ANSI CL compatible) it's interesting for others implementations.

Still, this still is more like a wish, than a reality

**Comment by Sasanidas** [comment]
Trying this approach here: https://github.com/lem-project/lem/pull/686
