### ISSUE TITLE
libjpeg.so.8 not included with Debian 12

### ISSUE THREAD

**Issue by aykaramba** [lem-project/lem#729]
Hi.

I just upgraded to Debian 12 so that I can run Lem because of the libc requirements.  Two points:

1) lem-ncurses works, so far no issues.

2) However, the lem binary throws the following error:

 lem-v2.0.0 $ ./lem

debugger invoked on a CFFI:LOAD-FOREIGN-LIBRARY-ERROR in thread
#<THREAD tid=59953 "main thread" RUNNING {1003BC0003}>:
  Unable to load foreign library (LIBTIFF.SO.6-455).
  Error opening shared object "/home/user/tmp/lem/lem-v2.0.0/lib/libtiff.so.6":
  libjpeg.so.8: cannot open shared object file: No such file or directory.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY    ] Try loading the foreign library again.
  1: [USE-VALUE] Use another library instead.
  2: [ABORT    ] Exit from the current thread.

(CFFI::FL-ERROR "Unable to load foreign library (~A).~%  ~A" #:LIBTIFF.SO.6-455 "Error opening shared object \"/home/user/tmp/lem/lem-v2.0.0/lib/libtiff.so.6\":
  libjpeg.so.8: cannot open shared object file: No such file or directory.")
   error finding frame source: Bogus form-number: the source file has probably
                               changed too much to cope with.
   source: NIL
0] 

I downloaded Lem from here: https://github.com/lem-project/lem/releases/tag/v2.0.0

**QUESTION: Is there a way to download and use libjpeg.so.8 the same was as all the other libraries in the local lem/lib folder?**  

Inkscape seems to ship with its own libjpeg.so.8, so not sure what is going on here on Debian 12.  According to online results, it isn't included, there is a way to install an older package but you have to enable mulitarch support and I would like to avoid that and keep a nice clean environment.  

Can someone shed some light on that error / libjpeg.so.8 requirement and possible ways to resolve it?

Thanks.

**Comment by Sasanidas** [comment]
Umm, maybe there is a problem in the binary in Debian, can you try the main branch? 

To test it out, clone the repository (https://lem-project.github.io/lem-page/installation/getting-started/#installation-with-sbcl)

You can also clone it in the quicklisp local-projects (I'm assuming you have quicklisp installed, if not https://www.quicklisp.org/beta/).


Then, to avoid a dependency error, open sbcl (in the Lem directory) and sequentially run:
```
(ql:quickload :quick-patch)

(quick-patch:register "https://github.com/sharplispers/log4cl"
		      "fe3da517147d023029782ced7cd989ba24f1e62d")


(quick-patch:register "https://github.com/scymtym/esrap.git"
		      "d806138342a6b27327649fd5f36e0fe2e0966867")

(quick-patch:checkout-all "build/quick-patch/")

(ql:quickload :lem-sdl2)
(lem:lem)

```

Also, when Lem crashes, there is usually in log in .lem/error.log that may show more information, if you can paste the content that maybe helpful :+1: 

Sorry about the inconvenience

**Comment by aykaramba** [comment]
Hey!

Thanks for taking the time to write all of that out for me, I would not have figured that out.  Details:

1) The (lem:lem) sbcl / quicklisp approach works and lem-sdl starts up.

2) I once again confirmed that ./lem-ncurses works, however ./lem does not work as per the above debugger information.

3) With respect to a log file, no file is created here:  ~/.lem/error.log.  I would love to paste it here but I don't have it.  

I have re-downloaded the .tar.gz file and the issue still remains the same.  If you have any suggestions for how I can assist with additional testing i would be happy to do so.  

No need to apologize, Lem is amazing and I am excited to learn how to use it and see how to integrate it into my workflow.

**Comment by Sasanidas** [comment]
> I have re-downloaded the .tar.gz file and the issue still remains the same. If you have any suggestions for how I can assist with additional testing i would be happy to do so.

Seems like indeed is a problem in the Linux binary, it also doesn't work for me in Linux Mint, if you want to build a binary (given that  the quicklisp approach works). At the end of the quicklisp instead of running lem, you can dump the image to an executable running:
```
(load "build.lisp")
```
Make sure that you are in the lem directory so it can find the build.lisp file (which is in the root of the project),  you can run 
```
(sb-posix:getcwd)
```
To get the current path of the REPL (in SBCL).

What I usually do i just create a symbolic link to /usr/local/bin or another path in $PATH, but that's up to you.

We have to still have better testing for binaries in the different Linux distribution (and more easy way to fix theses things), still, thanks for taking the time and let me know if it worked :+1:

**Comment by aykaramba** [comment]
Aha!  Okay, just letting you know that the dumped binary works and loads fast.  This is so cool, thank you for taking the time to follow up.

Would you mind if I point out one more item for consideration?  

./lem --> starts up really quickly (this compiled one)

./lem-ncurses --> starts up really slowly (from the .tar.gz file) even though ncurses should be really fast.

Not a show stopper or an issue by any means.  I am happy to use both as I am really keen to work toward a full common lisp environment regardless.  I am just hoping this data point is useful in some way.

If I can help, let me know.  Thank you kindly for all of the hand holding, I am bookmarking the instructions here they are super useful.

**Comment by Sasanidas** [comment]
> Would you mind if I point out one more item for consideration?
> 
> ./lem --> starts up really quickly (this compiled one)
> 
> ./lem-ncurses --> starts up really slowly (from the .tar.gz file) even though ncurses should be really fast.


Ummm interesting, I experience similar startup time in both (when opening), maybe a command like emacs-startup time could be useful.

> If I can help, let me know. Thank you kindly for all of the hand holding, I am bookmarking the instructions here they are super useful.

No problem :smile: , using the software is already a nice contribution, if in the future you want to share the configuration don't hesitate to open a pull request so other people can do the good Emacsy copy-paste (https://lem-project.github.io/lem-page/installation/configuration/)

**Comment by aykaramba** [comment]
Thanks for the help, this issue is resolved.  The sdl version is eye opening as it supports image viewing by default.  I wasn't expecting that as I always used emacs-nox, so having a nice sdl based editor that looks / works like emacs-nox is amazing.

**Comment by aykaramba** [comment]
Just following up on this once more:

1) I made some modifications to my filesystem and now my compiled Lem binary cannot find the fonts.  It is looking for the fonts in the Lem src directory in ~/common-lisp.

This is fine, I don't care, I can fix this with a symlink.  However, I tried to use the above instructions to compile a new binary and I get a compile error:

 System "micros" not found

2) I ran the following sequentially in sbcl:

```

(ql:quickload :quick-patch)

(quick-patch:register "https://github.com/sharplispers/log4cl"
		      "fe3da517147d023029782ced7cd989ba24f1e62d")


(quick-patch:register "https://github.com/scymtym/esrap.git"
		      "d806138342a6b27327649fd5f36e0fe2e0966867")

(quick-patch:checkout-all "build/quick-patch/")

(ql:quickload :lem-sdl2)

```

3) When I tried to quickload :lem-sdl2, I got the following error:

```

(ql:quickload :quick-patch)

(quick-patch:register "https://github.com/sharplispers/log4cl"
		      "fe3da517147d023029782ced7cd989ba24f1e62d")


(quick-patch:register "https://github.com/scymtym/esrap.git"
		      "d806138342a6b27327649fd5f36e0fe2e0966867")

(quick-patch:checkout-all "build/quick-patch/")

(ql:quickload :lem-sdl2)
(lem:lem)

```

4) I search for quicklisp package named "micros" and I did not find anything.  Does anyone know what "micros" is, where it should be located and how to resolve this issue?

I would like to be able to rebuild Lem as many times as necessary in order to increase my iterative testing of Lem.

By the way, Lem is pretty much my defacto text editor on my system, it is just that good.  Absolutely amazing work, everyone should be proud of what they have accomplished.

**Comment by aykaramba** [comment]
Updating this for anyone reading or following thread:

1) As of today's 2.1 release compiling works.

2) I no longer need to do this part:

```

(quick-patch:register "https://github.com/sharplispers/log4cl"
		      "fe3da517147d023029782ced7cd989ba24f1e62d")


(quick-patch:register "https://github.com/scymtym/esrap.git"
		      "d806138342a6b27327649fd5f36e0fe2e0966867")

(quick-patch:checkout-all "build/quick-patch/")

```

3) I can now just:

a) git clone --recursive https://github.com/lem-project/lem.git
b) cd into  /lem/scripts
c) sbcl
d) (ql:quickload lem:sdl2)
e) (load "build.lisp)

This will compile and dump the lem image binary and you can run this anywhere on your system.

This issue is resolved, thank you very much everyone!
