### ISSUE TITLE
lem 2.0.0 release for mac is damaged and couldn't be used

### ISSUE THREAD

**Issue by rajcspsg** [lem-project/lem#737]
Hi,

I download lem-darwin and extracted and moved application.
When I opened I get error.
<img width="259" alt="Screenshot 2023-06-14 at 11 51 07 AM" src="https://github.com/lem-project/lem/assets/10123965/34c15d73-20ab-4804-b7d5-90a91a6522a5">

**Comment by cxxxr** [comment]
Thank you for the report.
Is this the same problem?

https://github.com/lem-project/lem/issues/635
