### ISSUE TITLE
Cannot autocomplete the /home/username/common-lisp folder

### ISSUE THREAD

**Issue by aykaramba** [lem-project/lem#759]
Hi.

I have been using ~/common-lisp/ as a location to store my common lisp projects instead of ~/quicklisp/local-projects/.  When I open up lem and try to open up a file in that folder, i do C-x-f, type the first few letters (comm) and try to press tab and I get this error message:

![Untitled](https://github.com/lem-project/lem/assets/16431651/dcacf5a2-e546-409f-a00b-da31f020c334)

Apologies for the screen shot, this error message does not appear in error.log file and I am not able to either copy the text from lem-ncurses or lem-sdl.  I am also not able to save whatever buffer that appears in because the moment I touch a key that buffer dissapears.

Note: I blacked out the path on my computer for obvious reasons, please don't pay attention to that.

This issue isn't a deal breaker, I can autocomplete all other paths except this one and can manually open files by typing in the full ~/common-lisp/ path.  The issue isn't even a priority of any kind, but it might suggest that certain types of input are not being sanitized if I am understanding what might be going on here?

If I made any mistakes or errors, my apologies ahead of time.  If anyone wants me to do additional testing, please let me know, I would be happy to do so.

**Comment by cxxxr** [comment]
Thank you for your report.
I know this is not a solution to the root problem of this, I have commit a tentative fix.
https://github.com/lem-project/lem/commit/9bc2b02050aec765d751f5e3bf0ddd4aca107857

**Comment by aykaramba** [comment]
I hope to learn enough lisp to help fix these eventually.  Thank you kindly.

**Comment by aykaramba** [comment]
I need to find out if there is a reminder option in github for issues that i opened but forgot to close.  This is closed now, thanks.
