### ISSUE TITLE
linux launcher throws missing library error

### ISSUE THREAD

**Issue by rajcspsg** [lem-project/lem#761]
Hi,

I downloaded lem-2.0.0 linux installer and extracted the zip folder. I tried to launch the lem editor with `./lem` command.

This gave error for missing `libtiff.so.6`  as in the below 

![Screenshot from 2023-06-18 22-43-11](https://github.com/lem-project/lem/assets/10123965/5135fe62-69c2-4668-a9ba-f8d3ffe9cd79)

I copied /lib64/libtiff.so.5 to ./lib/libtiff.so.6 and then this error has gone but got another error of missing libjpeg.so.8. There is libjpeg.so.62 in /lib64 in my system but this didn't solve the issue

![Screenshot from 2023-06-18 22-43-42](https://github.com/lem-project/lem/assets/10123965/b45f8a0d-02c7-4303-9e5c-ecb92d52f5a7)

It is better to provide the libraries along with the lem-linux installer.

OS details - 

```bash
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 38 (Thirty Eight)
Release:        38
Codename:       ThirtyEight

```

**Comment by Sasanidas** [comment]
Thanks for the report, indeed, I think it would be more interesting to have a deb and a rpm package so it can be installed more easily.

**Comment by Sasanidas** [comment]
On Debian based distros the command to install the dependencies is:

```
sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
```

Maybe there is some equivalent in rpm base distros like Fedora

**Comment by rajcspsg** [comment]
I installed these https://chewett.co.uk/blog/2135/installing-the-sdl-2-dev-tools-on-fedora/

Also installed https://fedora.pkgs.org/38/fedora-x86_64/jbigkit-libs-2.1-25.fc38.x86_64.rpm.html and libdeflate still error persists in fedora

**Comment by Sasanidas** [comment]
Those are indeed the libraries, it's weird that CFFI is not able to locate it, I'll install Fedora in a VM and check the error, sorry about the inconvenience.

**Comment by rajcspsg** [comment]
one weird thing that I found is that, I'm able to launch lem-editor from the lem-v2.0.0 folder using command `./lem-ncurses`. If I'm in any other folder try to launch lem by absolute path command then lem couldn't find the libraries in `lem-v2.0.0/lib`.

**Comment by Sasanidas** [comment]
I wasn't been able to fix the problem in Fedora, same error, seems like CFFI cannot find the libraries

**Comment by MaxGyver83** [comment]
Same error in Arch Linux:

```
Unable to load foreign library (LIBTIFF.SO.6-455).
Error opening shared object "/media/home/max/Downloads/lem-v2.0.0/lib/libtiff.so.6":
libjbig.so.0: cannot open shared object file: No such file or directory.
```

**Comment by cxxxr** [comment]
Hmmm, now "linux" binary means "ubuntu".
