### ISSUE TITLE
"unknown frontend: ncurses" lem-editor v2.0.0 installed using roswell is not working in Fedora

### ISSUE THREAD

**Issue by rajcspsg** [lem-project/lem#782]
Hi,

I've installed lem editor version 2.0.0 in fedora 38 using roswell.

I've ncurses installed but couldn't launch lem editor.
![Screenshot from 2023-06-23 22-45-45](https://github.com/lem-project/lem/assets/10123965/6c33d917-73c8-4bfe-bd8d-fcd38b43aee7)

**Comment by Sasanidas** [comment]
It maybe an error related to https://github.com/lem-project/lem/issues/761?
