### ISSUE TITLE
Starting slime crashes sdl2 frontend

### ISSUE THREAD

**Issue by BierLiebHaber** [lem-project/lem#791]
The sdl2 frontend works since https://github.com/lem-project/lem/pull/787 but starting slime with `M-x slime` causes lem to crash. It doesn't happen when using the ncurses frontend.
In the editor window I get this error: (sorry for the screenshot but I can't interact with the window anymore)
![lem-sdl2-software-error](https://github.com/lem-project/lem/assets/432988/d8ec1c7e-da73-4268-a776-3f3d656d3326)
Additionally I get this error in the terminal:
```
WARNING: :SB-EVAL is no longer present in *FEATURES*
CORRUPTION WARNING in SBCL pid 125258 tid 125258:
Memory fault at 0x7f6784ac2910 (pc=0x7f678ee9659b, fp=0x7f678019fb10, sp=0x7f67745e5d40) tid 125258
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
[xcb] Unknown sequence number while processing queue
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
sbcl: ../../src/xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
fatal error encountered in SBCL pid 125158 tid 125202:
SIGABRT received.

   0: fp=0x1e912 pc=0x7f678ee96a7c Foreign function pthread_kill

```

I'm running on ubuntu 22.04  with an AMD gpu and Mesa version 23.1.3 (from the kisak ppa)

**Comment by cxxxr** [comment]
Thanks for the report.
The async-process modified shared library was not committed.
Could you please try again after git clone?

e.g.
```
$ mkdir ~/common-lisp
$ cd ~/common-lisp
$ git clone https://github.com/lem-project/async-process.git
```
