### ISSUE TITLE
Should we use `cp -R` instead of `cp -r`?

### ISSUE THREAD

**Issue by VitoVan** [lem-project/lem#795]
https://github.com/lem-project/lem/blob/cf1084053992ceefa1c474e0dafe6149ceb5c1c4/src/ext/directory-mode.lisp#L319

According to [this](https://unix.stackexchange.com/questions/18712/difference-between-cp-r-and-cp-r-copy-command), they say `cp -r` is not portable and the behavior is implementation-defined.

**Comment by cxxxr** [comment]
Thank you for letting me.
Fixed by https://github.com/lem-project/lem/commit/71f123bc764a5aa3377af1295de8f2403b433ea4
