### ISSUE TITLE
LEM requires macOS 13

### ISSUE THREAD

**Issue by brandelune** [lem-project/lem#796]
Is there a technical reason why LEM requires macOS 13 and can't be used with slightly earlier versions?

**Comment by VitoVan** [comment]
I didn't see that requirement in the doc, where is it?

**Comment by brandelune** [comment]
Thank you for your reply.

The requirement appears when I try to launch the application. It says it requires macOS 13.

Maybe it's a build target that's set by default in your environment?

**Comment by VitoVan** [comment]
Ah, I see.

Did you download the macOS application bundle from the release page? If so, I guess it's just because of the developers of Lem built it on macOS 13. I personally can't find any reason that Lem should requires macOS 13.

If you try installing it from SBCL, it should just work:

https://github.com/lem-project/lem#installation-with-sbcl

That's what I guess, since I don't have access to lower version of macOS right now.

**Comment by VitoVan** [comment]
> Thank you. I'll try. But I think that you can set build targets that are lower than the OS you build on. So maybe the developers should try that.

On macOS, Lem was packed with [this](https://github.com/lem-project/lem-deploy/blob/main/build-darwin-arm64-sdl2.lisp), I don't think it has a *build targets* setting.

Maybe use GitHub runners could help, they have macOS 11, 12 and 13.

**Comment by brandelune** [comment]
I tried to install with sbcl, but it was a bit too complex for someone who wants to start learning Common Lisp. Sorry.

**Comment by VitoVan** [comment]
> I tried to install with sbcl, but it was a bit too complex for someone who wants to start learning Common Lisp. Sorry.

No need to be sorry, it is indeed very complicated.

Maybe wait for a while until more mature binaries came out. Or, if you haven't ran out of your patience or curiosity, you could post the obstacles you encountered with the installation via SBCL.

**Comment by brandelune** [comment]
`Please clone lem to a location where the path to asdf is accessible.` is not clear.

I installed asdf, following the asdf site instructions, which put the thing in `~/.asdf`, and changed the path in `.profile`.

Then I run 

```
$ sbcl
* (ql:quickload :lem-ncurses)
```

which ended up with an error message telling me that ql was not available, or something like that.

So I guess there is a hidden step that's expected from users who know asdf, but for users who don't, the instructions are not sufficient, I guess.

**Comment by VitoVan** [comment]
I suppose you have [Homebrew](https://brew.sh/) installed, if so, it could save you a lot of time.

1. Install dependencies

    ```bash
    brew install sbcl sdl2 sdl2_image sdl2_ttf libffi
    ```

2. Install Quicklisp

    ```bash
    cd ~/Downloads
    curl -o ./quicklisp.lisp -L https://beta.quicklisp.org/quicklisp.lisp
    sbcl --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(ql-util:without-prompting (ql:add-to-init-file))' --eval '(quit)'
    ```

3. Clone and setup Lem

    ```bash
    cd ~/quicklisp/local-projects
    git clone --recursive https://github.com/lem-project/lem.git
    # link something not yet available in Quicklisp
    ln -s ~/quicklisp/local-projects/lem/submodules/micros micros
    # clone Lem patched libraries:
    git clone https://github.com/lem-project/cl-sdl2.git
    git clone https://github.com/lem-project/cl-sdl2-ttf.git
    git clone https://github.com/lem-project/cl-sdl2-image.git
    # use the latest log4cl
    git clone https://github.com/sharplispers/log4cl.git
    ```

4. Finally, run

    ```bash
    sbcl --eval '(ql:quickload :lem-sdl2)' --eval '(lem:lem)'
    ```


I tested the above scripts on macOS Big Sur.

<img width="1427" alt="imagen" src="https://github.com/lem-project/lem/assets/1756956/0cd96319-2832-4cc4-82ad-26a99a5cf04e">

**Comment by brandelune** [comment]
It also works on 12.6.7. Thank you for walking me through the process.

**Comment by VitoVan** [comment]
> It also works on 12.6.7. Thank you for walking me through the process.

You're welcome, I just happen to have enough time and an old enough macOS.

Thank you for letting me know it also works on 12.6.7.

**Comment by brandelune** [comment]
While in the UI, TAB completion does not seem to work. C-c C-z (compound commands, generally) don't seem to work either.

**Comment by VitoVan** [comment]
> While in the UI, TAB completion does not seem to work. C-c C-z (compound commands, generally) don't seem to work either.

I think that, might worth a new issue, and I have no idea about it, some other contributors might be more familiar with it.

**Comment by brandelune** [comment]
Of course. It's another issue. Anyway, I'd like to keep this one open until the macOS binary properly launches on versions that correspond to its real dependencies, if you don't mind.

**Comment by cxxxr** [comment]
Perhaps there is no ability to specify a version when building with sbcl.
Wouldn't we need to have an older mac version or fork sbcl itself to solve this problem?

**Comment by VitoVan** [comment]
> Perhaps there is no ability to specify a version when building with sbcl. Wouldn't we need to have an older mac version or fork sbcl itself to solve this problem?

I have done this in [CALM](https://github.com/VitoVan/calm/blob/main/.github/workflows/calm.yml), and it indeed have custom built older version of [SBCL](https://github.com/VitoVan/calm/blob/main/.github/workflows/sbcl.yml).

Lem could be easily integrated into CALM and published as a CALM application, I just tried that 5 minutes ago. But that may not be what Lem want to be.

**Comment by VitoVan** [comment]
> ~Lem could be easily integrated into CALM and published as a CALM application, I just tried that 5 minutes ago. But that may not be what Lem want to be.~

I take this back, I tried but not yet succeed.

Running on my own machine is totally different from distributing it.

Distributing Lem is damn complicated.
