### ISSUE TITLE
Lisp beginning of defun command not working correctly

### ISSUE THREAD

**Issue by Sasanidas** [lem-project/lem#807]
Seems like it moves the point even if the point is not inside any function (if it's outside) and even move the point to a comment (maybe also check if the point is inside a comment?):

https://github.com/lem-project/lem/assets/26670956/6ef11a09-3d70-47f2-8eb4-faf2c515bba8

I'm not sure this is the correct behaviour

**Comment by cxxxr** [comment]
This looks like an expected behavior, but what kind of behavior do you expect?

**Comment by Sasanidas** [comment]
Umm, well I didn't realize but GNU Emacs does the same thing. For me it seems odd that you can navigate to the beginning of the a function that you are not in. But I guess it makes sense from a command perspective of like in Emacs "Move backward to the beginning of a defun."
