### ISSUE TITLE
Release v2.1

### ISSUE THREAD

**Issue by cxxxr** [lem-project/lem#823]
- [x] Relase notes
- [ ] build application
  - [x] apple silicon mac
  - [ ] intel mac
  - [x] ubuntu 22.04
  - [x] windows

**Comment by aykaramba** [comment]
This is awesome!  Just downloaded and compiled.  So far, works great!

**Comment by cxxxr** [comment]
```common-lisp
(ql:quickload '(:com.inuoe.jzon
                :alexandria))

(defun collect-pullrequests ()
  (let ((text (uiop:run-program 
               "gh pr list -s closed -S \"merged:>=2023-05-22\" -L 1000 --json title,url,author"
               :output :string
               :directory (princ-to-string (ql:where-is-system :lem)))))
    (let ((list-by-authors (make-hash-table :test 'equal)))
      (loop :for item :across (com.inuoe.jzon:parse text)
            :unless (gethash "is_bot" (gethash "author" item))
            :do (let ((url (gethash "url" item))
                      (title (gethash "title" item))
                      (author (gethash "login" (gethash "author" item))))
                  (push (format nil "- ~A~%  ~A~%" title url)
                        (gethash author list-by-authors))))
      (maphash (lambda (author list)
                 (format t "~%`@~A`~%" author)
                 (mapc #'write-string list))
               list-by-authors))))

(collect-pullrequests)
```

`@Sasanidas`
- Fix egghead pull request series link
  https://github.com/lem-project/lem/pull/639
- Basic support for Elixir language
  https://github.com/lem-project/lem/pull/647
- Fix vi-backward-word-begin stack bug
  https://github.com/lem-project/lem/pull/654
- Add change-package REPL shorcut
  https://github.com/lem-project/lem/pull/662
- Add cd repl function and get/set current lisp directory
  https://github.com/lem-project/lem/pull/663
- Add quote in the inspector function and sort in execute command
  https://github.com/lem-project/lem/pull/664
- Remove elixir server-path variable and add a way to change the lsp spec
  https://github.com/lem-project/lem/pull/666
- Fix abbrev duplication keywords
  https://github.com/lem-project/lem/pull/679
- Lem with other CL implementations
  https://github.com/lem-project/lem/pull/686
- Add thingatp functionality
  https://github.com/lem-project/lem/pull/699
- Add some tests to thingatp and hyperspec functionality
  https://github.com/lem-project/lem/pull/701
- Update README.md
  https://github.com/lem-project/lem/pull/711
- Add repository patch as a solution for dependency hell
  https://github.com/lem-project/lem/pull/722
- Fix visual state problem
  https://github.com/lem-project/lem/pull/724
- Add lisp-eval-print-last-sexp
  https://github.com/lem-project/lem/pull/736
- Add makefile and build sdl2
  https://github.com/lem-project/lem/pull/744
- Move build.lisp to scripts
  https://github.com/lem-project/lem/pull/750
- Add test script and Make command
  https://github.com/lem-project/lem/pull/751
- Extend documentation mode to document tests
  https://github.com/lem-project/lem/pull/756
- Add support for Emacs Lisp 
  https://github.com/lem-project/lem/pull/784
- Add imenu (detective) support for Lem
  https://github.com/lem-project/lem/pull/788
- Add command prompt navigation forward and backwards
  https://github.com/lem-project/lem/pull/793
- Improve backward and forward prompt movement
  https://github.com/lem-project/lem/pull/794
- Add find defintions for elisp-mode
  https://github.com/lem-project/lem/pull/810
- Remove jsonrcp/http dependency from elisp-mode
  https://github.com/lem-project/lem/pull/825

`@seanfarley`
- sdl2: fix retina mouse coordinates
  https://github.com/lem-project/lem/pull/822

`@vindarel`
- vi-mode: add +, - and Space
  https://github.com/lem-project/lem/pull/634
- directory-mode: sort by name and mtime
  https://github.com/lem-project/lem/pull/678
- find files recursively
  https://github.com/lem-project/lem/pull/696
- help: add docstrings
  https://github.com/lem-project/lem/pull/705
- window: add commands documentation
  https://github.com/lem-project/lem/pull/712
- hyperspec: message the user if symbol not found
  https://github.com/lem-project/lem/pull/725
- Vindarel/meta is not right alt
  https://github.com/lem-project/lem/pull/726
- new command project-find-file
  https://github.com/lem-project/lem/pull/730
- README: link to downloads, mention LSP
  https://github.com/lem-project/lem/pull/731
- project: add keybindings (C-x p f)
  https://github.com/lem-project/lem/pull/741
- project: rename detele -> kill buffers
  https://github.com/lem-project/lem/pull/745
- vindarel/directory-sort-by-size
  https://github.com/lem-project/lem/pull/747
- projects: save and switch projects
  https://github.com/lem-project/lem/pull/758
- (minor) export toggle-auto-save, toggle-line-numbers
  https://github.com/lem-project/lem/pull/762
- point: translate docstrings
  https://github.com/lem-project/lem/pull/765
- point: translate docstrings (fix)
  https://github.com/lem-project/lem/pull/766
- macros: translate docstrings
  https://github.com/lem-project/lem/pull/767
- grep: add keys and help
  https://github.com/lem-project/lem/pull/768
- detective: export user-facing functions, add docstrings
  https://github.com/lem-project/lem/pull/817
- Vindarel/legit experiment
  https://github.com/lem-project/lem/pull/821

`@BierLiebHaber`
- Fixed overlays not being considered when finding the x position in a window
  https://github.com/lem-project/lem/pull/815

`@cxxxr`
- Improved display of images to buffer: added commands for scaling and display of resolution in mode line
  https://github.com/lem-project/lem/pull/629
- add a super key support in SDL2
  https://github.com/lem-project/lem/pull/633
- Avoid references to internal symbols in the lem package
  https://github.com/lem-project/lem/pull/643
- refactor command definitions
  https://github.com/lem-project/lem/pull/646
- Add command keybindings document generator
  https://github.com/lem-project/lem/pull/650
- Add docstring to each command
  https://github.com/lem-project/lem/pull/659
- Add documentation-mode
  https://github.com/lem-project/lem/pull/669
- Replace swank with micros
  https://github.com/lem-project/lem/pull/691
- Improve `M-x lisp-describe-symbol`
  https://github.com/lem-project/lem/pull/693
- Improve display of completion results
  https://github.com/lem-project/lem/pull/697
- Add sidebar
  https://github.com/lem-project/lem/pull/702
- Implement filer
  https://github.com/lem-project/lem/pull/709
- To deprecated signal-hanlder mechanism
  https://github.com/lem-project/lem/pull/716
- Update README.md: Added for error in update
  https://github.com/lem-project/lem/pull/717
- Reimplementation of the eval commands in lisp-mode
  https://github.com/lem-project/lem/pull/735
- Inspect the evaluation results
  https://github.com/lem-project/lem/pull/738
- Class Inheritance Tree
  https://github.com/lem-project/lem/pull/764
- Make `M-q` the key binding for the standard close operation
  https://github.com/lem-project/lem/pull/770
- Update readme
  https://github.com/lem-project/lem/pull/774
- Allow hover to focus
  https://github.com/lem-project/lem/pull/775
- Improve repl-shortcut UI
  https://github.com/lem-project/lem/pull/777
- Add quickload repl-shortcut
  https://github.com/lem-project/lem/pull/778
- Associate object with printed in REPL
  https://github.com/lem-project/lem/pull/783
- SDL2: change renderer option from `accelerated` to `software`
  https://github.com/lem-project/lem/pull/787
- Add trace commands to lisp-mode
  https://github.com/lem-project/lem/pull/792
- The powerful print debugger (a.k.a the watcher)
  https://github.com/lem-project/lem/pull/803
- Display loading-spinner during evaluation in REPL
  https://github.com/lem-project/lem/pull/811
- Specify by base color names
  https://github.com/lem-project/lem/pull/814

`@jsparkes`
- Add bindings for C-Home and C-End to jump to beginning and end of buffer
  https://github.com/lem-project/lem/pull/779
- Correct spelling of associate.
  https://github.com/lem-project/lem/pull/798
- Implement get-font-list for windows.
  https://github.com/lem-project/lem/pull/800

`@VitoVan`
- fix blurry text on Apple retina display
  https://github.com/lem-project/lem/pull/799

`@Neshamon`
- Document some color theme functions
  https://github.com/lem-project/lem/pull/760

`@jcs090218`
- feat(lisp-mode): Add command to eval buffer
  https://github.com/lem-project/lem/pull/668
- chore: Document some point commands
  https://github.com/lem-project/lem/pull/670
- chore: Document functions in other.lisp
  https://github.com/lem-project/lem/pull/671
- chore: Document clipboard.lisp
  https://github.com/lem-project/lem/pull/675
- chore: Document some functions in window.lisp
  https://github.com/lem-project/lem/pull/681
- chore: Document functions in echo.lisp
  https://github.com/lem-project/lem/pull/685
- chore: Document color.lisp
  https://github.com/lem-project/lem/pull/689
- chore: Document version.lisp
  https://github.com/lem-project/lem/pull/704
- chore: Document command.lisp
  https://github.com/lem-project/lem/pull/740

`@RadSpaceEd`
- Added C-S-Backspace command that kills the whole line
  https://github.com/lem-project/lem/pull/723

`@theangelperalta`
- [VI-MODE] • Enhance define-vi-state to allow expose more of the defclass CLOS functionality.
  https://github.com/lem-project/lem/pull/700

`@avitkauskas`
- fix typo in name vi-open-adove
  https://github.com/lem-project/lem/pull/655

`@snmsts`
- fix error on build
  https://github.com/lem-project/lem/pull/651

`@t-sin`
- Add a launcher script for SDL2 frontend for roswell users
  https://github.com/lem-project/lem/pull/637
