### ISSUE TITLE
Add a command to toggle line-wrap

### ISSUE THREAD

**Issue by cxxxr** [lem-project/lem#827]
### Discussed in https://github.com/lem-project/lem/discussions/826

<div type='discussions-op-text'>

<sup>Originally posted by **aykaramba** July 10, 2023</sup>
Hi.

I have been reading this page: https://github.com/lem-project/lem/releases

For [v1.9.2] it says: Rename editor variable truncate-lines to line-wrap.

When I M-x line-* I don't see line-wrap as an option to autocomplete.  Does this still exist?  Is there an alternate options that I don't understand?

Thanks.</div>

**Comment by jfaz1** [comment]
@cxxxr safe to close this one
