### ISSUE TITLE
Horizontal and vertical split frames are resizing to middle position.

### ISSUE THREAD

**Issue by aykaramba** [lem-project/lem#829]
I often use vertical and horizontal split windows.  As I am starting to use LEM for coding CLOG projects I am finding that any resized frame will reset to middle position (on both axis as appropriate).

TESTED ON: XFCE4 desktop and StumpWM window manager environment.

HOW TO REPLICATE: Start up Lem, split the buffers vertically and horizontally, move each of the splits to unique positions and resize the window.  Each of the splits will reset it self to the center.  This also happens without resizing the window as I am typing (some process triggers in the background) but I cannot replicate it.

LEM VERSIONS TESTED: 2.0, compiled LEM-SDL2 from source yesterday using the following process: 

a) git clone --recursive https://github.com/lem-project/lem.git
b) cd into /lem/scripts
c) sbcl
d) (ql:quickload :lem-sdl2)  
e) (load "build.lisp)

I tested it with LEM-NCURSES from the download files.

This is not a show stopper issue, users can just maximize to a single buffer which most people use anyway.  Only access to the Lisp REPL makes this a fun fature to have so you can jump back and forth and test ideas as you code.

PRIORITY: Low

Let me know if you have any questions about any of the above.

**Comment by cxxxr** [comment]
Thank you for the feedback.

The behavior of balancing windows when splitting is intentional.

However, it is certainly more convenient to take the ratio into account when the user adjusts the size.
This is something we would like to improve in the future.

As a workaround, change `lem-core/commands/window::*balance-after-split-window*` to nil so that it will not balance when split.

**Comment by aykaramba** [comment]
Aha!  Neat.  Let me give that a try.  I would voat for keeping splits proportional on window resize.   Looking forward to exploring Lem further.

Really amazing work.

**Comment by aykaramba** [comment]
Setting *balance-after-split-window* to NIL and recompiling doesn't resolve the issue.  This isn't a big deal, I can just switch between buffers for now.

I would like this item to go on the feature request list if there is such a thing.

For now, I am liking lem-sdl2 so much I am having a hard time going back to Emacs, Lem has a huge amount of really nice default features and behaviours that I like a lot.

What is the proper way to handle this ticket?  Do I just close this or apply some other action?

**Comment by cxxxr** [comment]
Sorry for the late reply, I've been offline for a while.

> What is the proper way to handle this ticket? Do I just close this or apply some other action?

Well, it might be better to close this issue or update the issue title.
I also appreciate your feedback, Thank you.

**Comment by aykaramba** [comment]
No problem!  Than you for Lem.  I am now doing Lisp programming in it as well and it is going really well.  There are some really great quality of life features in Lem that make it a joy to use.  I am closing the issue for now.
