### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by rpx99** [lem-project/lem#850]
Hi, I noticed a blank in the file string when loading a file. It is also present using the Lem project explorer (C-x d).

Correct: "Datenprüfung.sql"

Windows Explorer:

![windows_explorer](https://github.com/lem-project/lem/assets/70011162/4cef1e7e-4c63-421b-8153-167b541dbb95)

Wrong:  "Datenprü fung.sql"

Lem:

![img](https://github.com/lem-project/lem/assets/70011162/635a994d-6c30-42ec-9c02-c6670a3bafbd)

**Comment by t-sin** [comment]
Could you open that `Datenprü fung.sql` file? I want to know which is this problem about displaying only or not.

**Comment by t-sin** [comment]
OK. It's displaying problem. Actually that `ü` is a sequence of two letters: `u` and [combining diacritic](https://en.wikipedia.org/wiki/Diacritic#List_of_diacritics_in_Unicode). Lem simply treats that string as two letter string so that `ü` is placed two-letter width in a display.

I think text layout process with letter combining is so difficult so Lem treats simple way even that strings for now.

**Comment by seanfarley** [comment]
Welcome to encoding hell :-)

**Comment by t-sin** [comment]
I thing it's not about character encoding, it's about text rendering.

**Comment by seanfarley** [comment]
> I thing it's not about character encoding, it's about text rendering.

Oh? And what problem does the text rendering have with ASCII? Is it perhaps that rendering a different glyph (which is represented by a different encoding) is hell? jk jk, it's all in jest :-P

**Comment by t-sin** [comment]
No that diacritic letter isn't included in ASCII encoding, it's included ISO 8859 or Unicode. Off cource codepoint and combining of that differs in these character sets.

**Comment by rpx99** [comment]
Does lem support utf-8 ?Am 22.07.2023 07:05 schrieb Shinichi Tanaka ***@***.***>:
No that diacritic letter isn't included in ASCII encoding, it's included ISO 8859 or Unicode. Off cource codepoint and combining of that differs in these character sets.

**Comment by vindarel** [comment]
@rpx99 yes I can copy-paste UTF-8 symbols in a buffer.

**Comment by rpx99** [comment]
Do or can we have some info in the modeline (is it called modeline in lem ?) like so to show the encoding:

Emacs:
![modeline_encoding](https://github.com/lem-project/lem/assets/70011162/212b0a6c-92a1-4c3b-a780-92374b7c7d1b)
With details:
![modeline_encoding_details](https://github.com/lem-project/lem/assets/70011162/6c41ff4e-b772-4467-ac6a-cc4ba897b582)


Notepad++:
![nppp_encoding](https://github.com/lem-project/lem/assets/70011162/108afaf5-d3c7-4078-8ccc-41b6b4d2ce46)

The line break format should be a useful information to display, too?


![modeline_linebreak](https://github.com/lem-project/lem/assets/70011162/7ad36441-afc1-40ad-a9fb-58624b2737cf)

Next step could be to be able to actually change the encoding, line break format?

![nppp_encoding2](https://github.com/lem-project/lem/assets/70011162/b6147556-a837-4207-9122-f451175877d2)

**Comment by t-sin** [comment]
Nice idea but it's an another issue to request new feature.

This issue's problem is still remains so I think this should be still opened.

**Comment by rsm-lisper** [comment]
> I thing it's not about character encoding, it's about text rendering.

I have the same problem with polish UTF-8 characters (but only some). After some of them " " (blank space) appears and caret/cursor doesn't match actual position. It happens on both ncurses and sdl2 version. If you need some polish characters for testing, "zażółcić gęślą jaźń" sentence have them all :)

![utf-problem](https://github.com/lem-project/lem/assets/26094109/c816a4ef-41dd-433e-8467-c1b25488f496)

**Comment by rpx99** [comment]
At least I found out it only occurs with the sdl2 and not with ncurses frontend.

**Comment by rsm-lisper** [comment]
I've made some more testing and it looks like there are two issues.
1. **SDL2** version: I can type polish characters, but lem **can't display** them properly.
2. **Ncurses** version: I **can't type** some of the characters, but lem can display them correctly.

To be sure I tested it on two machines, one with Slackware 15, and sbcl compiled from sources. Second with Ubuntu, and sbcl installed from binaries. Exactly the same results on both machines.

### SDL2
Testing text (as displayed correctly by ncurses version):
![ncurses](https://github.com/lem-project/lem/assets/26094109/0da5d79b-05ff-4539-9310-b79542b9b2bd)
SDL2 issue (character ó/Ó):
![sdl2](https://github.com/lem-project/lem/assets/26094109/aa8a7868-b174-46fe-94f6-edcfa1f91bc6)
However, when cursor is on the problematic ó/Ó letter - lem displays it correctly!
![sdl2-cursor](https://github.com/lem-project/lem/assets/26094109/5eb71444-53e9-4caf-b9da-a52f9ff75131)

### ncurses
Typing issues:
`AltGr-a` (ą) => works as `C-n` / `arrow-down`
`AltGr-c` (ć) => works as `Backspace`
`AltGr-e` (ę) => works as `Shift-F5`
`AltGr-A` (Ą) => works as `C-b` / `arrow-left`
`AltGr-C` (Ć) => works as `C-a`
`AltGr-E` (Ę) => works as `Shift-F4`

Hope it helps!

**Comment by rpx99** [comment]
The situation for äöü and the @ symbol is solved by using the branch **origin/commonization-of-graphical-text-buffer** in mode `M-x change-buffer-to-v2`. I could not create the € symbol with `Alt-Gr + e`. Some Alt-Gr combinations work, others don't.

Here my keyboard output for Alt-Gr:

Should: `¹²³¼½¬{[]}\¸@ſ€¶ŧ←↓→øþ¨~æſðđŋħ ̣ĸł˝^’|»«¢„“”µ·…–`
Is (LEM): `¹²³¼½¬{[]}\@ſ¶ŧøþ~æſðđŋħĸł|»«¢µ·`

**Comment by rpx99** [comment]
This has improved in v2 buffer mode to:

LEM: ′¹²³¼½¬{[]}\@ſ€¶ŧ←↓→øþ~æſðđŋħ ̣ĸł˝^’|»«¢„“”µ·…–

![image](https://github.com/lem-project/lem/assets/70011162/877fc7c1-fe1c-4080-8c21-fa5d35cef51a)

**Comment by rpx99** [comment]
Only ALT-GR + ` = ¸ and ALT-GR + ü = ¨ need an additional "space" typed so that they appear.

For latter combination I get the character twice, i.e. ¨¨

I get this behaviour for Emacs 28.2, too, so not sure if it is really a lem issue.

**Comment by Sasanidas** [comment]
Given that the nature of the last comment, I'll close this issue for now (which doesn't seem Lem specific). Feel free to open it again if needed :+1:
