### ISSUE TITLE
how about create-file or new-empty-buffer

### ISSUE THREAD

**Issue by lewisl** [lem-project/lem#857]
I guess the "spittle-in-the-beard" unix crowd never creates files, but the rest of us do.  Even emacs has finally added commands for this (v. 27 and above).  Only took them 30+ years so you have time...!

**Comment by Sasanidas** [comment]
Hahaha, creating a file it's just creating a buffer adding some text and save it.
But indeed having a command to create an empty file is quite handy (and it should be quite easy to add).

**Comment by lewisl** [comment]
I tried that and I must have done something wrong.  Is the command to  create a buffer different than switching to another buffer.  I could not name the new buffer.

From: Fermin MF ***@***.***>
Reply-To: lem-project/lem ***@***.***>
Date: Thursday, July 20, 2023 at 5:28 PM
To: lem-project/lem ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [lem-project/lem] how about create-file or new-empty-buffer (Issue #857)


Hahaha, creating a file it's just creating a buffer adding some text and save it.
But indeed having a command to create an empty file is quite handy (and it should be quite easy to add).

**Comment by vindarel** [comment]
@lewisl I just tried: use `C-x C-f` to open a file, but give it the name of a new file. This creates a buffer with the given name, the file still doesn't exist. Write content, save the file.

If I use `C-x b` to switch buffers, I can give it a new name, it creates a new buffer, but C-x C-s did not work. I had to use M-x write-file.

**Comment by lewisl** [comment]
Good.  I’ll give that a shot.  It’s fine to have to save the buffer; that’s the goal after all.

From: vindarel ***@***.***>
Reply-To: lem-project/lem ***@***.***>
Date: Saturday, July 22, 2023 at 6:17 AM
To: lem-project/lem ***@***.***>
Cc: Lewis Levin ***@***.***>, Mention ***@***.***>
Subject: Re: [lem-project/lem] how about create-file or new-empty-buffer (Issue #857)


@lewisl<https://github.com/lewisl> I just tried: use C-x C-f to open a file, but give it the name of a new file. This creates a buffer with the given name, the file still doesn't exist. Write content, save the file.

If I use C-x b to switch buffers, I can give it a new name, it creates a new buffer, but C-x C-s did not work. I had to use M-x write-file.

**Comment by cxxxr** [comment]
Thank you for the interesting issue.
I think so if there are no files associated when `C-x C-s`, it is better to change to the behavior of `C-x C-w`.
