### ISSUE TITLE
Github pages for lem

### ISSUE THREAD

**Issue by azzamsa** [lem-project/lem#86]
@hiroki802  @cxxxr  

What if we make github pages for lem, we can add bunch of lem information there.
- goals.
- todo.
- screnshot.
- instalation guide.
- what makes lem special.
- more.

Thanks.

**Comment by Sasanidas** [comment]
We do have now a webpaga with a lot of information (https://lem-project.github.io/lem-page/).

Did it solved the issue? (ping @azzamsa )

Thanks!

**Comment by azzamsa** [comment]
Yes. I think we can safely close this 6 years old issue :)

**Comment by t-cool** [comment]
当時のやり取りを思い出しました。
懐かしいです。

**Comment by azzamsa** [comment]
@t-cool Yes. I still have very strong memories about it. Days before github sponsor was a thing.
