### ISSUE TITLE
Alt Gr key doesn't seem to work

### ISSUE THREAD

**Issue by rpx99** [lem-project/lem#860]
In Lem release 2.1 for windows the Alt Gr key doesn't seemt to work (nothing happens).

In emacs typing AltGr + Q gives me @ and AltGr + E results in € (german keyboard).

Is the AltGr key implemented at all?

**Comment by Dima-369** [comment]
See https://github.com/lem-project/lem/issues/858#issuecomment-1646651886 on how to debug which modifier key you would need. You should be able to set the modifiers you need there.

**Comment by rpx99** [comment]
This is solved in the v2 buffer of version

![image](https://github.com/lem-project/lem/assets/70011162/8b45c1e5-2e52-4b71-bae4-5c4cab7eafd1)

```
$ git branch
* commonization-of-graphical-text-buffer
```
There are some keys that don't work yet, c.f.: [https://github.com/lem-project/lem/issues/850](https://github.com/lem-project/lem/issues/850)
