### ISSUE TITLE
Request to fix extreme buffer slow down when a file is opened with German Umlaute and line jumping

### ISSUE THREAD

**Issue by Dima-369** [lem-project/lem#864]
For instance, I used this text file: 
[test.txt](https://github.com/lem-project/lem/files/12131619/test.txt)

See this video, it's hard to see the extreme slow-down though, but it is there: 

Left side is Emacs, right side is Lem. The line characters also jump around incorrectly, see the first line.

https://github.com/lem-project/lem/assets/15002298/4982086f-6e97-4ce0-af4b-67a5cb7910ed

**Comment by Sasanidas** [comment]
(ping @Dima-369 ) I tried to open the file with the latest release on Linux, and it seems that it now the space between word is the correct one:

![germ](https://github.com/lem-project/lem/assets/26670956/cf2dcef8-f03c-4f65-9233-9b9a8c06d609)

**Comment by Dima-369** [comment]
@Sasanidas Works fine now, thanks!
