### ISSUE TITLE
How to implement a centered cursor with good performance in SDL2?

### ISSUE THREAD

**Issue by Dima-369** [lem-project/lem#869]
I used this code which gives the expected outcome, an always centered cursor:

```lisp
(defun dima-recenter-on-post-command ()
  (window-recenter (current-window)))

(add-hook *post-command-hook* 'dima-recenter-on-post-command)
```

But as seen in the video is has terrible performance (compared to Emacs where I honestly don't see any drawback, I am running the same recenter code (with some more `if`s here and there to exclude certain buffers from recentering) for months):

https://github.com/lem-project/lem/assets/15002298/fec58a2a-a2a3-4587-b329-b76da9d1ba8f

**Comment by cxxxr** [comment]
Thank you for the feedback.
I'm interesting this behavior.

I've changed it now.
https://github.com/lem-project/lem/commit/9bf24e32ec8234cc28ea9cf54562f1462ce7a307
Hopefully this is a slight improvement.

**Comment by Dima-369** [comment]
> Hopefully this is a slight improvement.

Thanks for the quick implementation! Yes, this is indeed a great improvement. Overall, scrolling in Lem still feels noticably slower in Emacs, but I don't think it is related to the `(recenter)` now.
