### ISSUE TITLE
Bug: Lem cannot quickload projects NEWLY created in CLOG-Builder.

### ISSUE THREAD

**Issue by aykaramba** [lem-project/lem#870]
**LEM VERSIONS:**  LEM-sdl2 (v.2.1) and LEM-ncurses (v.2.1)

**HOST OS:** Debian 12

**LISP PACKAGES:** Lates LEM and latest CLOG packages.

**ISSUE:**  When I use CLOG-builder to create a new project in ~/common-lisp, LEM binaries cannot find it automagically.   I can load all projects created with CLOG-builder using sbcl or Emacs+SLY without any issue.

**HOW TO REPLICATE:** 

1) Load CLOG-builder:  
(ql:quickload :clog/tools)
(clog-tools:clog-builder)

2) In the CLOG-builder web interface, open up a project window, select new, select application template BASIC HTML PROJECT, fill template and enter project name, select where to save the project to.

3) Once the project files are created, they are loadable by any system that is asdf aware and so SBCL and sly should be able to load the project just fine.  Only LEM does not seem to be able to load these new projects.

**SPECIAL OBSERVATIONS:** LEM seems to be able to load any of my old CLOG projects and anything in the ~/common-lisp directory, just not newly created CLOG projects.  I have no idea how to explain this and I am posting this bug here as a preliminary observation that emacs+sly and sbcl can open every single project in ~/common-lisp and only LEM cannot open up new CLOG-projects.

**TROUBLE SHOOTING DONE:** 

* I tried to create as many new CLOG builder projects to see if it is maybe an issue with the type of project being created, however, as they are all templated and proper .asdf files are created, my understanding is that LEM should not have any issues loading the systems.   
* In addition, I tested upper/lower case and using or not using dashes and uncerscored in project names and that made no difference.  
* I also tried creating a new project under different profiles on my Linux and the behaviour is the same.

**DEBUGGER DATA FOR REFERENCE:**

   [Condition of type QUICKLISP-CLIENT:SYSTEM-NOT-FOUND]

Restarts:
 0: [CONTINUE] Try again
 1: [ABORT] Give up on "todo01"
 2: [REGISTER-LOCAL-PROJECTS] Register local projects and try again.
 3: [RETRY] Retry SLIME REPL evaluation request.
 4: [*ABORT] Return to SLIME's top level.
 5: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1007A98003}>)

Backtrace:
  0: ((LABELS QUICKLISP-CLIENT::RECURSE :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) "todo01")
       Locals:
         QL-DIST:NAME = "todo01"
  1: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<FUNCTION (LAMBDA NIL :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) {100456D6FB}>)
       Locals:
         FUN = #<FUNCTION (LAMBDA () :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) {100456D6FB}>
  2: (QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY "todo01")
       Locals:
         ASDF-SYSTEMS = NIL
         NAME = "todo01"
         QUICKLISP-SYSTEMS = NIL
  3: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "todo01" :PROMPT NIL)
       Locals:
         NAME = "todo01"
         PROMPT = NIL
         TRIED-SO-FAR = #<HASH-TABLE :TEST EQUALP :COUNT 0 {100456D603}>
  4: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<unused argument> #<FUNCTION (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {100456D55B}>) [fast-method]
       Locals:
         QL-IMPL-UTIL::FUN = #<FUNCTION (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {100456D55B}>
  5: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QL-IMPL:SBCL T)) #<QL-IMPL:SBCL {1001A93103}> #<FUNCTION (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {100456D55B}>) [fast-m..
       Locals:
         #:%IMPLEMENTATION = #<QL-IMPL:SBCL {1001A93103}>
         SB-PCL::.NEXT-METHOD-CALL. = #S(SB-PCL::FAST-METHOD-CALL :FUNCTION #<FUNCTION (SB-PCL::FAST-METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T))> :PV NIL :NEXT-METHOD-CALL NIL :ARG-INFO (2))
         QL-IMPL-UTIL::FUN = #<FUNCTION (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {100456D55B}>
  6: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) :TODO01 :PROMPT NIL :SILENT NIL :VERBOSE NIL) [fast-method]
       Locals:
         #:.DEFAULTING-TEMP. = NIL
         #:.DEFAULTING-TEMP.#1 = NIL
         #:N-SUPPLIED-7 = 0
         #:N-SUPPLIED-8 = 0
         QUICKLISP-CLIENT::PROMPT = NIL
         QUICKLISP-CLIENT::SILENT = NIL
         QUICKLISP-CLIENT::SYSTEMS = :TODO01
         QUICKLISP-CLIENT::SYSTEMS#1 = (:TODO01)
         QUICKLISP-CLIENT::THING = :TODO01
  7: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<FUNCTION (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {10045689EB}>)
       Locals:
         FUN = #<FUNCTION (LAMBDA () :IN QUICKLISP-CLIENT:QUICKLOAD) {10045689EB}>
  8: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-CLIENT:QUICKLOAD :TODO01) #<NULL-LEXENV>)
       Locals:
         SB-KERNEL:LEXENV = #<NULL-LEXENV>
         SB-IMPL::ORIGINAL-EXP = (QUICKLISP-CLIENT:QUICKLOAD :TODO01)
  9: (EVAL (QUICKLISP-CLIENT:QUICKLOAD :TODO01))
       Locals:
         SB-IMPL::ORIGINAL-EXP = (QUICKLISP-CLIENT:QUICKLOAD :TODO01)
 10: (MICROS::EVAL-REGION "(ql:quickload :todo01)")
       Locals:
         STREAM = #<SB-IMPL::STRING-INPUT-STREAM {7FE95EC6DDE3}>
         STRING = "(ql:quickload :todo01)"
 11: ((LAMBDA NIL :IN MICROS/REPL::REPL-EVAL))
       [No Locals]
 12: (MICROS/REPL::TRACK-PACKAGE #<FUNCTION (LAMBDA NIL :IN MICROS/REPL::REPL-EVAL) {100456894B}>)
 13: (MICROS::CALL-WITH-RETRY-RESTART "Retry SLIME REPL evaluation request." #<FUNCTION (LAMBDA NIL :IN MICROS/REPL::REPL-EVAL) {10045688EB}>)
 14: (MICROS::CALL-WITH-BUFFER-SYNTAX NIL #<FUNCTION (LAMBDA NIL :IN MICROS/REPL::REPL-EVAL) {10045688CB}>)
 15: (MICROS/REPL::REPL-EVAL "(ql:quickload :todo01)")
 16: (MICROS/REPL:LISTENER-EVAL "(ql:quickload :todo01)" :WINDOW-WIDTH 125)
 17: (SB-INT:SIMPLE-EVAL-IN-LEXENV (MICROS/REPL:LISTENER-EVAL "(ql:quickload :todo01)" :WINDOW-WIDTH 125) #<NULL-LEXENV>)
 18: (EVAL (MICROS/REPL:LISTENER-EVAL "(ql:quickload :todo01)" :WINDOW-WIDTH 125))
 19: ((LAMBDA NIL :IN MICROS:EVAL-FOR-EMACS))
 20: (MICROS::CALL-WITH-READTABLE-ALIST #<FUNCTION (LAMBDA NIL :IN MICROS:EVAL-FOR-EMACS) {10045687FB}>)
 21: (MICROS:EVAL-FOR-EMACS (MICROS/REPL:LISTENER-EVAL "(ql:quickload :todo01)" :WINDOW-WIDTH 125) "COMMON-LISP-USER" 10)
 22: (MICROS::PROCESS-REQUESTS NIL)
 23: ((LAMBDA NIL :IN MICROS::HANDLE-REQUESTS))
 24: ((LAMBDA NIL :IN MICROS::HANDLE-REQUESTS))
 25: (MICROS/SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION MICROS:SWANK-DEBUGGER-HOOK> #<FUNCTION (LAMBDA NIL :IN MICROS::HANDLE-REQUESTS) {10053E7FDB}>)
 26: ((FLET MICROS/BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "/home/username/mnt/work/desktop/username/common-lisp/lem/submodules/micros/backend/sbcl.lisp") #<FUNCTION MICROS:SWANK-DEBUGGER-HOOK> #<FUNCTION (LAMBD..
 27: (MICROS::CALL-WITH-BINDINGS ((*STANDARD-INPUT* . #1=#<MICROS/GRAY::SLIME-INPUT-STREAM {1004E512F3}>) (*STANDARD-OUTPUT* . #2=#<MICROS/GRAY::SLIME-OUTPUT-STREAM {1004FB1F73}>) (*TRACE-OUTPUT* . #2#) (*..
 28: (MICROS::HANDLE-REQUESTS #<MICROS::MULTITHREADED-CONNECTION {100489C2B3}> NIL)
 29: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
 30: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
 31: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
 32: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
 33: (SB-THREAD::RUN)
 34: ("foreign function: call_into_lisp_")
 35: ("foreign function: funcall1")

**COMMENTS:**  I have done my best to troubleshoot this and see if it is local to my system.  If I have missed a step or I can do additional trouble shooting I would be happy to do so, just let me know.

Thanks.

**Comment by cxxxr** [comment]
Probably an ASDF initialization timing issue.
Creating a new process with `M-x slime` and then using clog might work.

**Comment by aykaramba** [comment]
Okay.  If I do M-x slime I can load new CLOG projects.  Do you want this issue left open or closed?  Start-lisp-repl cannot load new CLOG projects and other users might eventually run into that.

Thoughts?

**Comment by cxxxr** [comment]
I've committed to a workaround of this issue.
Will it behave as expected?

**Comment by aykaramba** [comment]
I am confirming that this works great.

Thank you very kindly!  If it would be okay to say so, please do not feel like these issues need to be fixed right away or anything.  I am just happy to be able to run LEM and there is no issue with you guys fixing stuff when you can.

Your time and your life is valuable.

As such, this is greatly appreciated!
