### ISSUE TITLE
Ideas to improve the *prompt* buffer to be more like the vertical completion packages in Emacs

### ISSUE THREAD

**Issue by Dima-369** [lem-project/lem#873]
Currently in Lem it looks like this:

![image](https://github.com/lem-project/lem/assets/15002298/ec2e6116-d9a7-4dc9-9031-dc6f74960e26)

One needs to manually invoke the completion via tab:

![image](https://github.com/lem-project/lem/assets/15002298/296d1a25-f86b-4fc8-9710-156fd23b75c5)

In my configured Emacs with https://github.com/minad/vertico, completions are instantly visible, directories are colored and the `1/5` (or here `*/5` since I did not select anything) count is displayed to know how many completion candidates are there.

![image](https://github.com/lem-project/lem/assets/15002298/2bbfeccf-4058-4ac8-8ffe-73dd911b7c38)

`prompt-window.lisp` is the place to modify this behavior, I think, but I am not experienced enough with Lem about implementing this, so just leaving this here. To me this was one of the major steps in migrating many tasks to Emacs once I enabled the vertical completion frameworks in there since they are a joy to navigate :)

Lem would surely benefit from this as well!

**Comment by cianoc** [comment]
I'm interested in working on this.

My Vertico setup also supports some other nice features:
<img width="641" alt="image" src="https://github.com/lem-project/lem/assets/355604/46922d18-ea9b-440f-85ba-3055d585e474">

<img width="1728" alt="image" src="https://github.com/lem-project/lem/assets/355604/091ad211-5240-444c-b257-e9edefc209c6">

<img width="1110" alt="image" src="https://github.com/lem-project/lem/assets/355604/16400e74-2d5c-4d38-a4c9-86c530a8cf6b">

This are implemented with a different library, but I think they are pretty nice.

I'll start by adding a configuration option to have automatic completion, and then when I've got that merged in, I'll look into ways to support colors and more configurable options on what gets displayed as part of the completion.

**Comment by garlic0x1** [comment]
A vertico-style prompt configuration example is provided here: https://lem-project.github.io/usage/configuration/
https://github.com/lem-project/lem/pull/1362
