### ISSUE TITLE
Installation with sbcl problem

### ISSUE THREAD

**Issue by rpx99** [lem-project/lem#879]
Was following the [instructions](https://lem-project.github.io/lem-page/installation/getting-started/#installation-with-sbcl). Unfortunately this error occurs:

`$ sbcl
This is SBCL 2.3.6, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:quickload :lem-ncurses)
To load "lem-ncurses":
  Load 1 ASDF system:
    lem-ncurses
; Loading "lem-ncurses"
..................................................
[package micros/backend]..........................
[package micros/rpc]..............................
[package micros/match]............................
[package micros/mop]..............................
[package micros]..................................
[package micros/source-path-parser]...............
[package micros/source-file-cache]................
[package micros/sbcl].............................
[package micros/gray].............................
..................................................
[package micros/repl].............................
[package micros/swank-api]........................
[package micros/mrepl]............................
[package micros/trace-dialog].....................
[package micros/macrostep]........................
[package micros/pretty-eval]......................
[package micros/trace]............................
[package micros/lsp-api]......; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Lock on package SB-C violated when interning LAMBDA-PARENT while in package
;     LOG4CL-IMPL.
;   See also:
;     The SBCL Manual, Node "Package Locks"
;   
;     (in form starting at line: 99, column: 0, position: 3779)

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {1002700073}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "log4cl" "src" "naming-sbcl">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "log4cl" "src" "naming-sbcl">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "log4cl" "src" "naming-sbcl">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4:                                 Retry ASDF operation.
  5:                                 Retry ASDF operation after resetting the
                                     configuration.
  6: [ABORT                        ] Give up on "lem-ncurses"
  7: [REGISTER-LOCAL-PROJECTS      ] Register local projects and try again.
  8:                                 Exit debugger, returning to top level.

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "log4cl" "src" "naming-sbcl">)))
   error finding frame source: Bogus form-number: the source file has probably
                               changed too much to cope with.
   source: NIL
0] 
`

**Comment by rpx99** [comment]
In Windows an additional problem (seems gcc is required):

`[package cl-charms/low-level].; gcc -o "C:\Users\palm.robert\AppData\Local\cache\common-lisp\sbcl-2.3.2-win-x64\C\Users\palm.robert\quicklisp\dists\quicklisp\software\cl-charms-20221106-git\src\low-level\curses-grovel__grovel-tmp4WJ3B4TE.obj" -c -m64 -IC:/Users/palm.robert/quicklisp/dists/quicklisp/software/cffi-20230214-git/ "C:\Users\palm.robert\AppData\Local\cache\common-lisp\sbcl-2.3.2-win-x64\C\Users\palm.robert\quicklisp\dists\quicklisp\software\cl-charms-20221106-git\src\low-level\curses-grovel__grovel.c"

debugger invoked on a CFFI-GROVEL:GROVEL-ERROR in thread #<THREAD "main thread" RUNNING {10010A01B3}>: Couldn't execute "gcc": Das System kann die angegebene Datei nicht finden.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry #<PROCESS-OP > on #<GROVEL-FILE "cl-charms" "low-level" "curses-grovel">.
  1: [ACCEPT                       ] Continue, treating #<PROCESS-OP > on #<GROVEL-FILE "cl-charms" "low-level" "curses-grovel"> as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
  4:                                 Retry ASDF operation.
  5:                                 Retry ASDF operation after resetting the configuration.
  6: [ABORT                        ] Give up on "cl-charms"
  7:                                 Give up on "lem-ncurses"
  8: [REGISTER-LOCAL-PROJECTS      ] Register local projects and try again.
  9:                                 Exit debugger, returning to top level.

(CFFI-GROVEL:GROVEL-ERROR "~a" #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {10069C43B3}>)
   source: (ERROR (QUOTE GROVEL-ERROR) :FORMAT-CONTROL FORMAT-CONTROL :FORMAT-ARGUMENTS FORMAT-ARGUMENTS)
0]`

**Comment by cxxxr** [comment]
https://github.com/lem-project/lem/issues/628
Please look at this issue.

**Comment by Neshamon** [comment]
> Was following the [instructions](https://lem-project.github.io/lem-page/installation/getting-started/#installation-with-sbcl). Unfortunately this error occurs:
> 
> `$ sbcl
> This is SBCL 2.3.6, an implementation of ANSI Common Lisp.
> More information about SBCL is available at <http://www.sbcl.org/>.
> 
> SBCL is free software, provided as is, with absolutely no warranty.
> It is mostly in the public domain; some portions are provided under
> BSD-style licenses.  See the CREDITS and COPYING files in the
> distribution for more information.
> * (ql:quickload :lem-ncurses)
> To load "lem-ncurses":
>   Load 1 ASDF system:
>     lem-ncurses
> ; Loading "lem-ncurses"
> ..................................................
> [package micros/backend]..........................
> [package micros/rpc]..............................
> [package micros/match]............................
> [package micros/mop]..............................
> [package micros]..................................
> [package micros/source-path-parser]...............
> [package micros/source-file-cache]................
> [package micros/sbcl].............................
> [package micros/gray].............................
> ..................................................
> [package micros/repl].............................
> [package micros/swank-api]........................
> [package micros/mrepl]............................
> [package micros/trace-dialog].....................
> [package micros/macrostep]........................
> [package micros/pretty-eval]......................
> [package micros/trace]............................
> [package micros/lsp-api]......; 
> ; caught ERROR:
> ;   READ error during COMPILE-FILE:
> ;   
> ;     Lock on package SB-C violated when interning LAMBDA-PARENT while in package
> ;     LOG4CL-IMPL.
> ;   See also:
> ;     The SBCL Manual, Node "Package Locks"
> ;   
> ;     (in form starting at line: 99, column: 0, position: 3779)
> 
> debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
> #<THREAD "main thread" RUNNING {1002700073}>:
>   COMPILE-FILE-ERROR while
>   compiling #<CL-SOURCE-FILE "log4cl" "src" "naming-sbcl">
> 
> Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
> 
> restarts (invokable by number or by possibly-abbreviated name):
>   0: [RETRY                        ] Retry
>                                      compiling #<CL-SOURCE-FILE "log4cl" "src" "naming-sbcl">.
>   1: [ACCEPT                       ] Continue, treating
>                                      compiling #<CL-SOURCE-FILE "log4cl" "src" "naming-sbcl">
>                                      as having been successful.
>   2:                                 Retry ASDF operation.
>   3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
>                                      configuration.
>   4:                                 Retry ASDF operation.
>   5:                                 Retry ASDF operation after resetting the
>                                      configuration.
>   6: [ABORT                        ] Give up on "lem-ncurses"
>   7: [REGISTER-LOCAL-PROJECTS      ] Register local projects and try again.
>   8:                                 Exit debugger, returning to top level.
> 
> (UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "log4cl" "src" "naming-sbcl">)))
>    error finding frame source: Bogus form-number: the source file has probably
>                                changed too much to cope with.
>    source: NIL
> 0] 
> `

When compiling nurses, did you clone the git submodules as well? I know sometimes micros doesn't compile  correctly when you don't clone any updates it might've received.

**Comment by Neshamon** [comment]
> In Windows an additional problem (seems gcc is required):
> 
> `[package cl-charms/low-level].; gcc -o "C:\Users\a.b\AppData\Local\cache\common-lisp\sbcl-2.3.2-win-x64\C\Users\a.b\quicklisp\dists\quicklisp\software\cl-charms-20221106-git\src\low-level\curses-grovel__grovel-tmp4WJ3B4TE.obj" -c -m64 -IC:/Users/a.b/quicklisp/dists/quicklisp/software/cffi-20230214-git/ "C:\Users\a.b\AppData\Local\cache\common-lisp\sbcl-2.3.2-win-x64\C\Users\a.b\quicklisp\dists\quicklisp\software\cl-charms-20221106-git\src\low-level\curses-grovel__grovel.c"
> 
> debugger invoked on a CFFI-GROVEL:GROVEL-ERROR in thread #<THREAD "main thread" RUNNING {10010A01B3}>: Couldn't execute "gcc": Das System kann die angegebene Datei nicht finden.
> 
> Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
> 
> restarts (invokable by number or by possibly-abbreviated name):
>   0: [RETRY                        ] Retry #<PROCESS-OP > on #<GROVEL-FILE "cl-charms" "low-level" "curses-grovel">.
>   1: [ACCEPT                       ] Continue, treating #<PROCESS-OP > on #<GROVEL-FILE "cl-charms" "low-level" "curses-grovel"> as having been successful.
>   2:                                 Retry ASDF operation.
>   3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
>   4:                                 Retry ASDF operation.
>   5:                                 Retry ASDF operation after resetting the configuration.
>   6: [ABORT                        ] Give up on "cl-charms"
>   7:                                 Give up on "lem-ncurses"
>   8: [REGISTER-LOCAL-PROJECTS      ] Register local projects and try again.
>   9:                                 Exit debugger, returning to top level.
> 
> (CFFI-GROVEL:GROVEL-ERROR "~a" #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {10069C43B3}>)
>    source: (ERROR (QUOTE GROVEL-ERROR) :FORMAT-CONTROL FORMAT-CONTROL :FORMAT-ARGUMENTS FORMAT-ARGUMENTS)
> 0]`

It also looks like this attempt was compiled with SBCL 2.3.2. I haven't tested it with 2.3.2 but I know that Lem typically compiles correctly with the latest SBCL, which is 2.3.6

**Comment by rpx99** [comment]
Thanks a lot for comments. I will try on windows tomorrow again.

On FreeBSD (with sbcl 2.3.6) I could get around the log4cl issue with the latest cloned git of log4cl into common-lisp folder as described in #628 (thanks for the hint!)

Now I have a different error:

`[package async-process].
debugger invoked on a CFFI:LOAD-FOREIGN-LIBRARY-ERROR in thread
#<THREAD "main thread" RUNNING {10028A8073}>:
  Unable to load foreign library (ASYNC-PROCESS).
  Error opening shared object "libasyncprocess.so":
  Shared object "libasyncprocess.so" not found, required by "sbcl".

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Try loading the foreign library again.
  1: [USE-VALUE                    ] Use another library instead.
  2: [TRY-RECOMPILING              ] Recompile async-process and try loading it again
  3: [RETRY                        ] Retry
                                     loading FASL for #<CL-SOURCE-FILE "async-process" "async-process">.
  4: [ACCEPT                       ] Continue, treating
                                     loading FASL for #<CL-SOURCE-FILE "async-process" "async-process">
                                     as having been successful.
  5:                                 Retry ASDF operation.
  6: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  7:                                 Retry ASDF operation.
  8:                                 Retry ASDF operation after resetting the
                                     configuration.
  9: [ABORT                        ] Give up on "lem-ncurses"
 10: [REGISTER-LOCAL-PROJECTS      ] Register local projects and try again.
 11:                                 Exit debugger, returning to top level.

(CFFI::FL-ERROR "Unable to load foreign library (~A).~%  ~A" ASYNC-PROCESS "Error opening shared object \"libasyncprocess.so\":
  Shared object \"libasyncprocess.so\" not found, required by \"sbcl\".")
   source: (ERROR 'LOAD-FOREIGN-LIBRARY-ERROR :FORMAT-CONTROL CONTROL
                  :FORMAT-ARGUMENTS ARGUMENTS)
0] 

`

**Comment by rpx99** [comment]
When I aborted it continued to build lem ncurses and I also could start lem, but the error was still there.
I could solve it as described in https://github.com/lem-project/lem/issues/560#issuecomment-1648297153

Now it works on FreeBSD. Maybe it can be mentioned in the tips at #628 or even better improved in the https://github.com/lem-project/async-process project ?

**Comment by Neshamon** [comment]
> Thanks a lot for comments. I will try on windows tomorrow again.
> 
> On FreeBSD (with sbcl 2.3.6) I could get around the log4cl issue with the latest cloned git of log4cl into common-lisp folder as described in #628 (thanks for the hint!)
> 
> Now I have a different error (which seems to be an open issue #560 ) ?
> 
> `[package async-process].
> debugger invoked on a CFFI:LOAD-FOREIGN-LIBRARY-ERROR in thread
> #<THREAD "main thread" RUNNING {10028A8073}>:
>   Unable to load foreign library (ASYNC-PROCESS).
>   Error opening shared object "libasyncprocess.so":
>   Shared object "libasyncprocess.so" not found, required by "sbcl".
> 
> Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
> 
> restarts (invokable by number or by possibly-abbreviated name):
>   0: [RETRY                        ] Try loading the foreign library again.
>   1: [USE-VALUE                    ] Use another library instead.
>   2: [TRY-RECOMPILING              ] Recompile async-process and try loading it again
>   3: [RETRY                        ] Retry
>                                      loading FASL for #<CL-SOURCE-FILE "async-process" "async-process">.
>   4: [ACCEPT                       ] Continue, treating
>                                      loading FASL for #<CL-SOURCE-FILE "async-process" "async-process">
>                                      as having been successful.
>   5:                                 Retry ASDF operation.
>   6: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
>                                      configuration.
>   7:                                 Retry ASDF operation.
>   8:                                 Retry ASDF operation after resetting the
>                                      configuration.
>   9: [ABORT                        ] Give up on "lem-ncurses"
>  10: [REGISTER-LOCAL-PROJECTS      ] Register local projects and try again.
>  11:                                 Exit debugger, returning to top level.
> 
> (CFFI::FL-ERROR "Unable to load foreign library (~A).~%  ~A" ASYNC-PROCESS "Error opening shared object \"libasyncprocess.so\":
>   Shared object \"libasyncprocess.so\" not found, required by \"sbcl\".")
>    source: (ERROR 'LOAD-FOREIGN-LIBRARY-ERROR :FORMAT-CONTROL CONTROL
>                   :FORMAT-ARGUMENTS ARGUMENTS)
> 0] 
> 
> `
> 

From my experience, any .so files typically need to be installed by your distro's package manager, (e.g libsdl2-2.0.0-dev on debian 12 for sdl2)

If the package is already installed, you may have to digging for it and add it to your path if SBCL can't find it

**Comment by rpx99** [comment]
> From my experience, any .so files typically need to be installed by your distro's package manager, (e.g libsdl2-2.0.0-dev on debian 12 for sdl2)
> 
> If the package is already installed, you may have to digging for it and add it to your path if SBCL can't find it

Thanks. Well, think in this case it may "need" extension in
async-process/src/async-process.lisp and async-process/static to support BSD or riscv64 arch.

**Comment by rpx99** [comment]
Decided to skip it on windows as it seems to be too much of a hassle.

**Comment by cxxxr** [comment]
This issue is closed for now.
Please let me know if there is anything else.
