### ISSUE TITLE
Cannot enter quick command

### ISSUE THREAD

**Issue by cchase88** [lem-project/lem#883]
When pressing comma (,) to enter a Lem "quick command" a small window appears as expected but after entering a command I cannot enter it (pressing the [Enter] key does nothing). I've tried "ls", "pwd" and the other commands listed in the [REPL section of the documentation](https://lem-project.github.io/lem-page/usage/common_lisp/#repl) with no success.

I have Lem version 2.0.0 and I'm running it on Windows 10.

**Comment by cchase88** [comment]
I've just installed Lem 2.1.0 and experience the same issue. The command prompt no longer appears in its own window and now appears as a line on the REPL, but I cannot enter the command as expected.

![image](https://github.com/lem-project/lem/assets/3112290/38c8307a-5557-40c0-98da-f28a49de170c)

**Comment by cxxxr** [comment]
This feature was probably added later than 2.1

**Comment by cxxxr** [comment]
@cchase88 Has this been resolved?
