### ISSUE TITLE
[windows] Starting system shell and Slime service fails

### ISSUE THREAD

**Issue by tmheath** [lem-project/lem#895]
This morning I have installed Lem via the windows binary
from the release. Starting both the Shell and Slime fails...
I am able to use the built-in repl and slime-connect does
in fact work. Not sure if this is just an issue where Lem
cannot launch external processes.

`create-process failed ("ros" "-s "swank" "run"
Backtrace...
23 ((FLET "WITHOUT-INTERRUPTS-BODY-138" :IN SB-THREAD::RUN))
24: (SB-Thread::RUN)
25: ("foreign function: #x14003EBE5")
26: ("foreign function: #x14000685A")`

`C:/system32/cmd.exe is not a Lisp string or pointer.
Backtrace...
23 ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
24: (SB-Thread::RUN)
25: ("foreign function: #x14003EBE5")
26: ("foreign function: #x14000685A")`

Full information not included... Don't yet understand how to get the displayed trace into the clipboard. Says Press Space to close, closes during alt typing but not space. The issue is minor and doesn't really bother me though. C-x 0 just closes it fine.

**Comment by cxxxr** [comment]
Thank you for the report.
This is probably due to the assumption that sbcl and ros are installed.

Probably, the solution is to bundle sbcl.
I would like to solve this.

**Comment by tmheath** [comment]
I have no idea about the structure of the project. I'm
at work right now. To the aim of avoiding tying to a
specific implementation do you think I might be able
to manage reimplementing the swank stuff using the
below library?

https://github.com/brown/swank-client

I'm kind of worried that being an ignorant newb I'm
mostly just serving as a distraction here.

**Comment by cxxxr** [comment]
The following is probably the best way to make it work in your environment.

1. Instlal common lisp implementation
2. Install [micros](https://github.com/lem-project/micros) so that it can be read from (1)
3. Start (1) and launch micros server
   e.g. start sbcl and run `(ql:quickloads :micors)` and `(micros:create-server :dont-close t)`
4. slime-connect from lem.

> I'm kind of worried that being an ignorant newb I'm
mostly just serving as a distraction here.

No, no, no need to worry at all, We welcome you.
I appreciate the feedback on lem.

**Comment by tmheath** [comment]
You think storing a default launch command into a system environment variable for windows could work and if not specified try sbcl, try ros, finally start a swank server on it's own thread internally in the case of a failure (not very useful due to just being able to open the repl)?

The fix you provided works just fine... I think I could automate a dirty fix on me end until I update.
