### ISSUE TITLE
[Windows] Dired Mode Infunctional

### ISSUE THREAD

**Issue by tmheath** [lem-project/lem#897]
Opening a directory shows last modified date/time... No names show.

**Comment by vindarel** [comment]
mmh… 

How did you install Lem?

If you run 

    (lem:list-directory "./") ;; or another directory path

can you see all the files? I see a list like

```
(…
#P"/home/vince/lisp-projects/lem/package.json"
 #P"/home/vince/lisp-projects/lem/picture-test.jpg")
```

Then we could try:

    (mapcar #'enough-namestring *)  ;; run against the previous list result

I see like

```
(…
"package.json"
 "picture-test.jpg")
```

(I worked a bit on the directory mode, no Windows experience though)

**Comment by tmheath** [comment]
CL-USER> (lem:list-directory "./")
(#P"C:/Users/Tim.Heath/common-lisp/EMC Video Player/" #P"C:/Users/Tim.Heath/common-lisp/cl-emc/"
 #P"C:/Users/Tim.Heath/common-lisp/lem/")
CL-USER> (mapcar #'enough-namestring (lem:list-directory "./"))
("EMC Video Player/" "cl-emc/" "lem/")
CL-USER> 

Results of running the suggested commands... Installed lem via the prebuilt binary, extracted, just worked from the extracted folder. I did one modification where I added cd %~dp0 to the launching cmd file because without that it was not starting from an external directory. I was going to make a pull request with that change, just haven't gotten around to it.

I work on Windows, but at home I run linux, the experience at home with this has been much nicer (typical with software). The hard time I have in doing this stuff is that I'm running linux trying to work on windows stuff, can't give this time at work (I ought to spin up a vm).

**Comment by tmheath** [comment]
I re-ran the command with a text file added, I realized I had no files there. It saw the text file.

**Comment by Sasanidas** [comment]
Ping @tmheath , is this issue solved?

**Comment by tmheath** [comment]
@Sasanidas I have not updated Lem, I stopped using it from Windows.
The issue with the version still installed on this pc is that in dired mode, the entry show without any filenames.
![lem](https://github.com/lem-project/lem/assets/85769253/35304ee4-2f4d-4d24-98b6-658984d6b4cd)
If this has since been fixed I don't know, I'm not using lisp for anything at work for the moment.

**Comment by Sasanidas** [comment]
I see, I'll close this issue then, if in the future you want to try again on windows and happens feel free to open it again :+1:

**Comment by tmheath** [comment]
![lem-2 1](https://github.com/lem-project/lem/assets/85769253/41da8b33-72db-4710-8158-d7adafb16e66)
I have updated Lem to the binary release 2.1, the issue remains present for Windows.
My focus for the next while needs to be getting a release 1.0 version of the docx library
ready because I need it for my work. Otherwise I might ask for where I ought to look
to fix this. I'm not sure if this is large enough a problem at this point to warrant effort
to fix.
