### ISSUE TITLE
powerful fuzzy-completion like fzf

### ISSUE THREAD

**Issue by cxxxr** [lem-project/lem#926]

**Comment by vindarel** [comment]
FWIW, a fuzzy matcher for strings: https://github.com/vindarel/fuzzy-match this was extracted from Next/Nyxt. It uses some string matching algorithm, with more manual selection to get a "natural" result. Some benchmarking and efficiency work was done.

I didn't try using it with Lem yet.

**Comment by Sasanidas** [comment]
Seems fuzzy match is also thinking about fzf https://github.com/vindarel/fuzzy-match/blob/e46ca41ef4641461f7be006782e3cfdcf73ba98a/fuzzy-match.lisp#L57C16-L57C16 😄

**Comment by jcs090218** [comment]
Here are some fuzzy matching algorithms I know but not in Common-Lisp. Some can be ported to Common-Lisp easily. 🤔 

- [flex](https://github.com/jcs-elpa/flex)
- [flx](https://github.com/lewang/flx) / [flx-rs](https://github.com/jcs-elpa/flx-rs) (I prefer this)
- [flxy](https://github.com/jcs-elpa/flxy)
- [fuz.el](https://github.com/rustify-emacs/fuz.el) / [fuz-bin](https://github.com/jcs-elpa/fuz-bin) - `clangd` and `skim`
- [liquidmetal](https://github.com/jcs-elpa/liquidmetal)
- [sublime-fuzzy](https://github.com/jcs-elpa/sublime-fuzzy)

**Comment by cxxxr** [comment]
merge with https://github.com/lem-project/lem/issues/1441
