### ISSUE TITLE
Break error when evaluating a line using `lisp-eval-at-point`

### ISSUE THREAD

**Issue by Sasanidas** [lem-project/lem#987]
When using the function `lisp-eval-at-point` (or the key combination of it) it breaks the editor entering an eternal loop:

![fermin@fdebian: ~-quicklisp-local-projects-lem_001](https://github.com/lem-project/lem/assets/26670956/39113348-4b8b-484a-af92-69b326056687)

It seems like it has something to do with the spinner (maybe related to the new refactor overlay? https://github.com/lem-project/lem/pull/983)

Ping @cxxxr

**Comment by masatoi** [comment]
It seems trivial bug. I made PR #988 for this.

**Comment by cxxxr** [comment]
I think I broke it in https://github.com/lem-project/lem/pull/983
